// EXIT: 0
// OUTPUT: 544
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

int f0(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10, int p11) {
    if (((p7 / 16) >= p2)) {
        p3 = ((p1 & 255) << 4);
    } else {
        p4 = (p7 + -76);
    }
    p5 = -64;
    p4 = (((p10 - 94) & 255) << 3);
    return p0;
}

int f1(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10, int p11) {
    p5 = p3;
    return p3;
}

int f2(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8) {
    p7 = (((p3 & 255) << 3) - p4);
    for (int i27 = 0; i27 < 3; i27++) {
        p5 = ((p5 & 1023) ^ 497);
        p4 = ((p1 & 1023) ^ 596);
        p7 = p1;
    }
    p0 = p6;
    return (p4 - ((p8 & 1023) | 269));
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = -42;
    int v1 = -11;
    int v2 = 47;
    int v3 = 25;
    int v4 = -44;
    int v5 = -38;
    int v6 = 22;
    int v7 = -43;
    int v8 = -29;
    int v9 = 0;
    double d0 = 26.0;
    double d1 = 23.0;
    double d2 = -15.0;
    double d3 = -26.0;
    double d4 = -27.0;
    double d5 = -12.0;
    if ((((80 % 5) * 57) >= (v6 % 2))) {
        if (((v5 % -6) != v6)) {
            if ((v9 >= v2)) {
                if ((20 != -33)) {
                    v1 = v7;
                    if ((v2 > v3)) {
                        for (int i9 = 0; i9 < 4; i9++) {
                            v6 = v9;
                            v4 = v0;
                        }
                    } else {
                        for (int i47 = 0; i47 < 2; i47++) {
                            if ((11 >= v8)) {
                                arr[(54) & 7] = v2;
                            } else {
                                v5 = v4;
                                v9 = -74;
                            }
                        }
                    }
                } else {
                    for (int i91 = 0; i91 < 4; i91++) {
                        v9 = v2;
                        if ((v9 >= v7)) {
                            arr[(v6) & 7] = v1;
                        } else {
                            v9 = -29;
                            v9 = 86;
                        }
                        v2 = v2;
                    }
                    for (int i33 = 0; i33 < 6; i33++) {
                        if ((v2 > v9)) {
                            arr[((v1 + 57)) & 7] = v5;
                            v3 = i33;
                        } else {
                            arr[((36 * -38)) & 7] = v8;
                            if ((v7 <= 44)) {
                                arr[(-78) & 7] = v8;
                            } else {
                                if ((v7 < v8)) {
                                    v5 = v7;
                                } else {
                                    if ((v5 < 10)) {
                                        v3 = v6;
                                    } else {
                                        v4 = v5;
                                    }
                                    v0 = i33;
                                }
                                arr[(v5) & 7] = v4;
                            }
                        }
                        v2 = v5;
                        arr[(v0) & 7] = v8;
                    }
                }
                v5 = v4;
            } else {
                if ((v1 > v1)) {
                    v8 = v9;
                    v2 = v9;
                } else {
                    v5 = v7;
                    v7 = v9;
                }
            }
            if ((v8 < v5)) {
                arr[((v2 + v8)) & 7] = v1;
                arr[((-23 % 3)) & 7] = v9;
            } else {
                v1 = -97;
            }
        } else {
            v8 = (v3 * v6);
            arr[(((v6 & 255) >> 2)) & 7] = (61 % 5);
        }
    } else {
        v1 = (((v6 & 1023) & 537) % 11);
    }
    arr[(v6) & 7] = ((((-23 % -6) - ((v9 & 255) << 2)) & 1023) & 997);
    if (((-68 - v6) == (((v0 * v1) & 255) << 4))) {
        v4 = v9;
        v7 = (v0 / 5);
    } else {
        v5 = (v4 + (v9 - v6));
    }
    v3 = f1(-20, v0, ((v4 & 1023) ^ 919), ((-34 & 255) >> 0), ((v4 & 255) << 0), ((v4 & 255) >> 4), v1, (v9 * -37), ((v4 & 255) << 1), (-95 % -3), ((v4 & 1023) | 664), (v6 % -3));
    v6 = f2(((v8 & 255) << 0), ((v4 & 255) >> 2), v5, v2, (v2 / 16), ((v0 & 1023) | 305), ((v0 & 1023) | 218), (v6 * v6), ((-57 & 1023) | 685));
    d0 = (d0 + (d5 - d2));
    d1 = (d1 + (-30.0 + -32.0));
    d2 = (d2 + (d5 - d0));
    d3 = (d3 + (d1 + 28.0));
    d4 = (d4 + d5);
    d5 = (d5 + (39.0 + d3));
    v4 = ((((-43 / 16) & 1023) | 443) % 2);
    v6 = ((((v2 * v6) + (v7 + 27)) & 255) >> 3);
    v6 = f2(((-87 & 1023) & 491), ((v6 & 1023) | 759), ((v7 & 1023) | 774), ((v3 & 255) >> 0), ((v2 & 1023) | 756), 42, v1, ((v3 & 1023) | 652), v7);
    v2 = f2(((-34 & 1023) & 479), ((v7 & 1023) | 901), ((v6 & 1023) | 165), v3, ((-17 & 1023) ^ 177), ((v8 & 1023) | 342), ((v0 & 1023) | 483), ((-92 & 1023) ^ 683), ((v8 & 255) << 0));
    d0 = (d0 + d4);
    d1 = (d1 + d0);
    d2 = (d2 + (d1 * -25.0));
    d3 = (d3 + (d0 - d3));
    d4 = (d4 + d2);
    d5 = (d5 + (d2 - d3));
    for (int i76 = 0; i76 < 1; i76++) {
        if ((((v9 & 255) >> 0) == ((v8 & 255) >> 2))) {
            v6 = ((v8 & 1023) | 188);
            if ((-78 > v7)) {
                v5 = v3;
                v9 = v1;
            } else {
                v6 = -94;
                arr[((21 - 59)) & 7] = v6;
            }
        } else {
            v5 = ((v7 & 1023) ^ 581);
            v8 = ((v9 & 255) << 2);
        }
    }
    for (int i71 = 0; i71 < 1; i71++) {
        v0 = v9;
    }
    v6 = f0((-57 % 11), -49, (v8 % 7), (52 / -6), ((v8 & 1023) & 751), v1, 66, ((v6 & 255) >> 1), v9, v1, v2, (v7 + -91));
    v0 = f2(((v7 & 1023) & 633), v8, ((v8 & 1023) & 817), (-81 + -30), (4 - -24), (25 - v1), v2, v6, ((v8 & 1023) & 308));
    d0 = (d0 + d4);
    d1 = (d1 + (((v6 & 1023) ^ 903) & 63));
    d2 = (d2 + (d0 + d2));
    d3 = (d3 + d5);
    d4 = (d4 + (v8 & 63));
    d5 = (d5 + (d0 * d5));
    if (((64 % -3) <= v3)) {
        if (((-24 - -22) == v1)) {
            v1 = ((v3 & 255) >> 1);
        } else {
            v7 = arr[(v4) & 7];
            v5 = ((v5 & 255) >> 2);
        }
        if ((((v5 & 255) >> 1) > v0)) {
            v4 = ((v1 & 255) << 4);
            v8 = arr[(v8) & 7];
        } else {
            v9 = (v0 % 3);
            if ((v2 <= v2)) {
                if ((-30 > v2)) {
                    arr[(((v6 & 1023) ^ 423)) & 7] = v5;
                } else {
                    v2 = v1;
                    v0 = v9;
                }
                if ((v2 > -71)) {
                    for (int i74 = 0; i74 < 2; i74++) {
                        arr[(((v9 & 1023) | 522)) & 7] = v6;
                        v9 = -50;
                        v3 = v6;
                    }
                    v8 = v2;
                } else {
                    if ((v6 < v6)) {
                        for (int i0 = 0; i0 < 1; i0++) {
                            v4 = v9;
                            v8 = 72;
                            if ((v0 >= v5)) {
                                v5 = -13;
                                v8 = v6;
                            } else {
                                v1 = 59;
                                if ((v0 == v5)) {
                                    arr[(v5) & 7] = v6;
                                    if ((v9 < v4)) {
                                        v9 = v6;
                                        v5 = -39;
                                    } else {
                                        if ((v1 < 35)) {
                                            v6 = v6;
                                        } else {
                                            if ((19 <= -54)) {
                                                arr[((v2 + -69)) & 7] = v6;
                                                v6 = v4;
                                            } else {
                                                v7 = 91;
                                            }
                                        }
                                        v1 = v3;
                                    }
                                } else {
                                    v0 = v8;
                                    v3 = -81;
                                }
                            }
                        }
                    } else {
                        v2 = v5;
                    }
                }
            } else {
                v7 = -53;
                v0 = v3;
            }
        }
    } else {
        if ((v8 <= ((19 & 1023) & 875))) {
            v4 = (v3 * 74);
        } else {
            for (int i84 = 0; i84 < 2; i84++) {
                if ((v0 == 24)) {
                    if ((v2 <= v3)) {
                        arr[((i84 % 3)) & 7] = -33;
                        v1 = 27;
                    } else {
                        v3 = -97;
                    }
                    v9 = v8;
                } else {
                    if ((39 <= v9)) {
                        arr[((v9 + v2)) & 7] = -69;
                        if ((v3 >= v7)) {
                            v3 = -41;
                            v8 = v9;
                        } else {
                            if ((v6 < 93)) {
                                v6 = 55;
                                v8 = -15;
                            } else {
                                v9 = v9;
                            }
                            v1 = 3;
                        }
                    } else {
                        if ((52 <= 24)) {
                            v3 = v8;
                            v2 = -9;
                        } else {
                            v0 = -67;
                        }
                    }
                    v0 = v0;
                }
                arr[(v7) & 7] = v2;
                v9 = v2;
            }
        }
    }
    v0 = v6;
    v3 = f1(((v6 & 1023) & 1000), v9, 27, (v9 * 91), (v9 + v1), v6, (v2 * v7), ((v9 & 1023) | 315), (-64 - v4), ((v9 & 255) >> 0), (v3 % 16), v2);
    v0 = f2(v2, ((v0 & 1023) ^ 987), (v0 / 2), ((v3 & 1023) & 866), ((v5 & 1023) ^ 539), ((v1 & 255) >> 0), v4, (v1 % 7), (-71 % -3));
    d0 = (d0 + d5);
    d1 = (d1 + d2);
    d2 = (d2 + d4);
    d3 = (d3 + (v2 & 63));
    d4 = (d4 + d5);
    d5 = (d5 + (d3 * -13.0));
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != 3927539.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
