// EXIT: 0
// OUTPUT: 1571
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

int f0(double p0, double p1, double p2, double p3, int p4, double p5, int p6, int p7, int p8, int p9, int p10) {
    for (int i73 = 0; i73 < 2; i73++) {
        if ((p4 > 20)) {
            if ((p10 < p10)) {
                p8 = p9;
            } else {
                p10 = i73;
                p7 = -70;
            }
            p8 = p6;
        } else {
            p9 = p8;
            p6 = i73;
        }
        if ((i73 < p6)) {
            p8 = p7;
        } else {
            if ((p9 != p8)) {
                p10 = p4;
                p9 = p9;
            } else {
                p4 = p4;
                p7 = p4;
            }
            p6 = p10;
        }
        p10 = p6;
    }
    return p4;
}

int f1(double p0, int p1, double p2, double p3, int p4, double p5, int p6, int p7, int p8) {
    for (int i97 = 0; i97 < 1; i97++) {
        p7 = ((p8 & 1023) ^ 301);
    }
    for (int i4 = 0; i4 < 2; i4++) {
        p7 = (p1 / 5);
    }
    for (int i13 = 0; i13 < 4; i13++) {
        p8 = (p8 / 2);
        p1 = p6;
    }
    return ((p8 & 1023) & 456);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 21;
    int v1 = -45;
    int v2 = -10;
    int v3 = 37;
    int v4 = -4;
    int v5 = -5;
    int v6 = -2;
    int v7 = 14;
    int v8 = -33;
    int v9 = -47;
    double d0 = 9.0;
    double d1 = 10.0;
    double d2 = -9.0;
    double d3 = -17.0;
    double d4 = 30.0;
    double d5 = 22.0;
    if (((((v7 & 255) >> 0) / 7) != -64)) {
        if ((((v6 & 255) << 4) < ((v3 & 255) >> 1))) {
            if ((v6 >= v2)) {
                v3 = v8;
            } else {
                v1 = v2;
                v0 = v1;
            }
        } else {
            v3 = ((-13 & 255) >> 2);
            arr[((v3 % 8)) & 7] = -59;
        }
        if ((v2 <= (49 - 21))) {
            if ((-67 <= 80)) {
                v8 = v0;
            } else {
                v9 = v2;
                v1 = v4;
            }
            for (int i90 = 0; i90 < 4; i90++) {
                v3 = v4;
                if ((i90 <= 75)) {
                    v2 = v4;
                    v0 = v6;
                } else {
                    v1 = v1;
                    v9 = v2;
                }
            }
        } else {
            if ((-74 <= v7)) {
                v1 = v8;
                arr[(v5) & 7] = v3;
            } else {
                v5 = -40;
                v0 = v1;
            }
        }
    } else {
        v8 = (((v3 * v8) & 255) >> 1);
    }
    v6 = f1(d1, (v5 * v1), (d2 - -35.0), (d0 - d4), v6, (d4 - d4), -44, ((-62 & 1023) & 941), ((v9 & 255) << 1));
    v4 = f0((d0 * 12.0), (d2 + d0), (d3 + d1), (d1 * d5), (v0 - -96), (((v5 & 1023) | 311) & 63), v3, (v6 % 4), v2, ((25 & 1023) & 918), (-23 - v9));
    d0 = (d0 + (-33.0 + d1));
    d1 = (d1 + (d4 + 5.0));
    d2 = (d2 + (-28.0 - d5));
    d3 = (d3 + (d1 + -27.0));
    d4 = (d4 + (d4 * d5));
    d5 = (d5 + d3);
    arr[(((v4 & 255) >> 0)) & 7] = 63;
    if ((((v8 + 31) % 7) >= ((-29 - v0) / 5))) {
        for (int i63 = 0; i63 < 6; i63++) {
            v1 = ((49 & 1023) | 462);
            v2 = (v3 / 4);
            if ((60 <= v2)) {
                v5 = 6;
            } else {
                v3 = v3;
                v2 = 52;
            }
        }
    } else {
        for (int i38 = 0; i38 < 2; i38++) {
            v7 = ((37 & 1023) ^ 236);
            v6 = (75 + v7);
            v5 = i38;
        }
        v7 = ((v4 & 1023) ^ 919);
    }
    for (int i64 = 0; i64 < 5; i64++) {
        v9 = v9;
        if ((v0 != ((20 & 255) >> 3))) {
            if ((39 >= v8)) {
                v3 = 27;
                v5 = -95;
            } else {
                v6 = i64;
            }
            v7 = (v8 / 7);
        } else {
            v3 = ((v4 & 1023) ^ 550);
            v8 = (v5 - v6);
        }
    }
    v2 = f0(d1, (d4 * d0), (v8 & 63), -10.0, (-4 - 100), d5, ((v1 & 1023) | 814), ((v0 & 255) >> 4), (v1 * v0), ((v9 & 1023) | 303), v2);
    v3 = f0((d2 * d4), (d4 + d4), ((v5 * 42) & 63), d2, ((v1 & 1023) ^ 97), (d2 - d4), v2, ((70 & 1023) & 747), ((24 & 255) << 3), (v0 / -6), ((v9 & 255) >> 4));
    d0 = (d0 + d0);
    d1 = (d1 + (((26 & 255) << 3) & 63));
    d2 = (d2 + (d0 * 3.0));
    d3 = (d3 + ((-1 / -6) & 63));
    d4 = (d4 + d0);
    d5 = (d5 + d3);
    if ((v0 != (((v9 & 1023) ^ 325) / 2))) {
        v3 = (v7 * (v5 % 11));
        if (((v3 / 8) < ((v8 & 1023) | 200))) {
            if ((-45 != v8)) {
                if ((v9 == 74)) {
                    arr[((95 % 11)) & 7] = v8;
                } else {
                    v9 = v2;
                    v1 = v3;
                }
                v7 = v1;
            } else {
                v2 = 12;
            }
            if ((v6 < v4)) {
                for (int i76 = 0; i76 < 3; i76++) {
                    if ((v3 <= 30)) {
                        if ((v9 != v6)) {
                            v7 = v3;
                        } else {
                            v3 = 28;
                            v0 = -73;
                        }
                    } else {
                        arr[(((v7 & 1023) & 505)) & 7] = v4;
                        v8 = -93;
                    }
                }
                v2 = v0;
            } else {
                v1 = 30;
            }
        } else {
            v0 = ((25 & 255) << 1);
            for (int i28 = 0; i28 < 2; i28++) {
                v9 = v8;
            }
        }
    } else {
        for (int i30 = 0; i30 < 1; i30++) {
            v2 = -44;
            v7 = (v8 % 4);
            v0 = (-28 * v0);
        }
    }
    if ((((((v5 & 1023) | 27) & 255) << 4) == (((v9 + v4) & 255) << 0))) {
        if ((v4 <= (v0 / 3))) {
            for (int i32 = 0; i32 < 3; i32++) {
                v4 = v4;
                arr[((v7 * v4)) & 7] = v6;
                if ((v2 != v5)) {
                    v8 = v9;
                } else {
                    v9 = v4;
                }
            }
        } else {
            if ((-91 != v6)) {
                v9 = v9;
            } else {
                v6 = v4;
                arr[(v6) & 7] = v5;
            }
        }
    } else {
        v1 = 61;
        for (int i18 = 0; i18 < 6; i18++) {
            v8 = ((-66 & 1023) ^ 364);
            v9 = (i18 / 5);
            v0 = v8;
        }
    }
    v9 = f1((d1 - 38.0), ((v4 & 1023) & 89), d0, (v4 & 63), (v9 + v7), (d2 - d1), (v9 % 4), ((76 & 1023) & 427), (81 % 7));
    v0 = f1((d1 + 6.0), (v1 * 61), (v8 & 63), (d3 * d5), v4, -1.0, v0, (-21 - v0), (26 - 100));
    d0 = (d0 + (d3 * d2));
    d1 = (d1 + d0);
    d2 = (d2 + d5);
    d3 = (d3 + (-35 & 63));
    d4 = (d4 + (d0 - -28.0));
    d5 = (d5 + 7.0);
    v3 = ((v5 & 1023) ^ 548);
    if ((v5 <= (((v5 & 1023) & 939) % -3))) {
        if (((94 - 88) > 58)) {
            v0 = v2;
        } else {
            if ((v3 > v8)) {
                if ((v7 == v5)) {
                    v8 = v9;
                    if ((86 < v0)) {
                        v1 = -58;
                        for (int i67 = 0; i67 < 4; i67++) {
                            arr[(v2) & 7] = -45;
                            v5 = i67;
                            v5 = v0;
                        }
                    } else {
                        if ((v5 < v9)) {
                            if ((v7 >= v2)) {
                                arr[(v0) & 7] = 91;
                                arr[(((v3 & 1023) | 387)) & 7] = v8;
                            } else {
                                v2 = -90;
                            }
                        } else {
                            arr[(((v6 & 255) >> 1)) & 7] = -19;
                            if ((v9 != v7)) {
                                if ((v5 > v4)) {
                                    v9 = v1;
                                } else {
                                    v7 = v2;
                                }
                            } else {
                                for (int i51 = 0; i51 < 2; i51++) {
                                    v2 = -5;
                                    v4 = v3;
                                    v3 = i51;
                                }
                                for (int i90 = 0; i90 < 3; i90++) {
                                    v8 = v3;
                                    v9 = v8;
                                    v4 = v1;
                                }
                            }
                        }
                        arr[((23 / 16)) & 7] = v1;
                    }
                } else {
                    v0 = v4;
                    v6 = 55;
                }
                if ((92 == 10)) {
                    v4 = v5;
                    v4 = v0;
                } else {
                    v4 = v5;
                    v2 = v4;
                }
            } else {
                v3 = -37;
                v1 = v9;
            }
            v7 = (v0 + -18);
        }
    } else {
        for (int i9 = 0; i9 < 3; i9++) {
            arr[(v3) & 7] = ((v1 & 1023) | 628);
        }
        v3 = v9;
    }
    v1 = v3;
    v9 = f1(d3, (v7 - v9), 22.0, d1, ((v8 & 255) << 4), (d0 - 33.0), ((v7 & 255) >> 2), ((v0 & 255) >> 2), ((v5 & 1023) ^ 895));
    d0 = (d0 + (-11 & 63));
    d1 = (d1 + ((27 / 5) & 63));
    d2 = (d2 + (d1 + d1));
    d3 = (d3 + (d1 - d2));
    d4 = (d4 + (d4 * d4));
    d5 = (d5 + d0);
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != 269495.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
