// EXIT: 0
// OUTPUT: 1178
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

int f0(int p0, int p1, double p2, double p3, int p4, double p5, int p6, int p7, int p8) {
    if ((p8 > (p1 - p8))) {
        for (int i94 = 0; i94 < 5; i94++) {
            if ((i94 < p7)) {
                p6 = 64;
                if ((p1 > p0)) {
                    p0 = p6;
                    p8 = p7;
                } else {
                    p6 = 2;
                }
            } else {
                p7 = p7;
            }
            if ((p4 <= p0)) {
                p7 = 17;
            } else {
                p7 = 91;
            }
        }
        p8 = (p7 - p8);
    } else {
        for (int i25 = 0; i25 < 1; i25++) {
            if ((28 >= p7)) {
                if ((p7 >= p8)) {
                    if ((p1 != 88)) {
                        if ((p0 <= p7)) {
                            p7 = p6;
                        } else {
                            p7 = p4;
                            if ((p7 > p0)) {
                                p0 = -36;
                                p0 = 92;
                            } else {
                                p8 = 35;
                                if ((i25 >= p7)) {
                                    p0 = p8;
                                    p6 = 48;
                                } else {
                                    p0 = p1;
                                }
                            }
                        }
                        p7 = 10;
                    } else {
                        if ((p0 <= p8)) {
                            p0 = 98;
                        } else {
                            if ((p6 <= p1)) {
                                p0 = 70;
                                p1 = p0;
                            } else {
                                p6 = 95;
                                if ((p8 != -77)) {
                                    p1 = p8;
                                } else {
                                    p0 = 12;
                                    p7 = p7;
                                }
                            }
                        }
                    }
                    p8 = p1;
                } else {
                    p0 = p7;
                }
                if ((-58 == p4)) {
                    if ((p7 == p6)) {
                        p0 = -18;
                        p4 = 53;
                    } else {
                        p0 = 29;
                        p7 = p6;
                    }
                    p4 = p8;
                } else {
                    p0 = i25;
                    p0 = p4;
                }
            } else {
                p8 = p8;
                p6 = -12;
            }
            p7 = p0;
            p6 = i25;
        }
        p0 = ((p8 & 1023) | 956);
    }
    return ((p7 + 84) + ((p0 & 1023) & 33));
}

double f1(int p0, int p1, int p2, double p3, double p4, double p5, int p6, int p7, double p8, int p9) {
    p0 = ((p1 % 5) + p1);
    if ((p0 <= p0)) {
        p9 = p6;
    } else {
        for (int i40 = 0; i40 < 3; i40++) {
            p6 = p7;
            if ((p7 <= p7)) {
                p1 = -6;
            } else {
                p2 = p2;
                p0 = p9;
            }
            p9 = p0;
        }
    }
    return (((p9 & 1023) & 896) & 63);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 9;
    int v1 = -35;
    int v2 = -16;
    int v3 = -15;
    int v4 = -16;
    int v5 = -40;
    int v6 = 27;
    int v7 = 4;
    int v8 = 35;
    int v9 = -42;
    double d0 = 0.0;
    double d1 = -2.0;
    double d2 = -8.0;
    double d3 = 8.0;
    double d4 = 18.0;
    double d5 = -19.0;
    arr[(v1) & 7] = v3;
    d2 = f1((-54 + -33), (v0 * v4), v6, (d3 - -28.0), (d5 - d5), d1, (v3 - -83), (26 / 11), d0, v1);
    d0 = f1(((-48 & 255) >> 3), ((v2 & 1023) & 515), (v6 + v4), (-21.0 * d4), d2, d3, (v0 % 3), (v6 / 2), (d1 * -21.0), ((0 & 1023) | 339));
    d0 = (d0 + (d3 + d0));
    d1 = (d1 + d0);
    d2 = (d2 + -22.0);
    d3 = (d3 + (((v7 & 1023) ^ 620) & 63));
    d4 = (d4 + d3);
    d5 = (d5 + 39.0);
    if ((v7 <= (v4 / 11))) {
        v3 = ((v7 & 1023) | 12);
        for (int i56 = 0; i56 < 3; i56++) {
            v3 = ((v5 & 1023) ^ 258);
            v5 = ((v3 & 255) << 0);
            if ((v7 == v0)) {
                arr[((v8 * v6)) & 7] = i56;
                v9 = 42;
            } else {
                v2 = v0;
            }
        }
    } else {
        v3 = 22;
    }
    v2 = f0((56 - v3), ((v5 & 255) << 0), d2, -29.0, v1, d5, ((v2 & 1023) & 573), -43, (v9 - v8));
    v8 = f0(v2, ((v2 & 1023) | 465), d0, d3, (v2 / 5), (d4 - d1), ((v0 & 255) << 3), v9, ((v8 & 1023) & 184));
    d0 = (d0 + (v3 & 63));
    d1 = (d1 + d2);
    d2 = (d2 + d1);
    d3 = (d3 + d1);
    d4 = (d4 + (32.0 - d5));
    d5 = (d5 + (v9 & 63));
    if ((v4 > (((v2 & 1023) & 337) % -6))) {
        if (((56 % 2) > (v0 / 2))) {
            v0 = (v1 - 9);
            v4 = v8;
        } else {
            for (int i16 = 0; i16 < 6; i16++) {
                if ((v8 >= 28)) {
                    v4 = v9;
                    if ((-41 <= v3)) {
                        if ((v3 != i16)) {
                            v6 = v0;
                        } else {
                            v2 = -60;
                        }
                    } else {
                        v5 = v4;
                        v8 = 15;
                    }
                } else {
                    arr[(((-6 & 1023) ^ 344)) & 7] = v5;
                    v1 = v7;
                }
            }
        }
        if ((58 >= (-59 % 2))) {
            v0 = ((v7 & 255) << 4);
        } else {
            v4 = (83 * v0);
            v7 = arr[(3) & 7];
        }
    } else {
        v2 = ((((v5 & 1023) & 624) & 1023) ^ 516);
        v5 = (((v7 % 2) & 1023) | 839);
    }
    v4 = f0(((-9 & 1023) & 98), -46, -35.0, (d1 * -25.0), (94 + v4), d5, (v9 + v3), v6, v7);
    d0 = f1(-84, (v7 - v1), (v9 % 4), ((v3 * v5) & 63), (d0 + d5), (-8.0 + d0), ((v8 & 255) >> 2), ((v6 & 255) >> 2), (v8 & 63), v5);
    d0 = (d0 + (d5 - d5));
    d1 = (d1 + (d4 * -16.0));
    d2 = (d2 + 11.0);
    d3 = (d3 + d2);
    d4 = (d4 + (11.0 + d4));
    d5 = (d5 + d3);
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != -1072.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
