// EXIT: 0
// OUTPUT: -28
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

double f0(int p0, double p1, double p2, double p3, double p4, double p5, int p6, int p7) {
    if (((p7 + 25) == (p6 * p6))) {
        p0 = 22;
        p6 = p0;
    } else {
        if ((p7 < p0)) {
            p0 = -5;
        } else {
            if ((p7 >= p6)) {
                for (int i84 = 0; i84 < 5; i84++) {
                    p0 = -50;
                }
                p7 = p0;
            } else {
                p7 = p6;
            }
        }
        p6 = p6;
    }
    return p3;
}

int f1(double p0, int p1, double p2, double p3, double p4, double p5, double p6, double p7, int p8) {
    p8 = ((((p8 & 255) >> 2) & 255) << 2);
    p1 = -10;
    p8 = p1;
    return 77;
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = -8;
    int v1 = 24;
    int v2 = -38;
    int v3 = -3;
    int v4 = 29;
    int v5 = 23;
    int v6 = -22;
    int v7 = -35;
    int v8 = -39;
    int v9 = -38;
    int v10 = 4;
    int v11 = 11;
    int v12 = 47;
    int v13 = -14;
    int v14 = 10;
    int v15 = 12;
    double d0 = 17.0;
    double d1 = 15.0;
    double d2 = -22.0;
    double d3 = -9.0;
    double d4 = 13.0;
    double d5 = -23.0;
    double d6 = -11.0;
    double d7 = -21.0;
    double d8 = -7.0;
    double d9 = -18.0;
    double d10 = -13.0;
    double d11 = 14.0;
    for (int i86 = 0; i86 < 3; i86++) {
        v0 = (((-3 % 5) & 255) >> 0);
        v3 = (((v14 & 255) >> 3) / 2);
    }
    d11 = f0(((v15 & 1023) & 516), d6, (d8 + d0), (16.0 + d1), (d9 - d8), (v5 & 63), (v2 + v15), ((v9 & 1023) & 625));
    d0 = (d0 + (d4 + d4));
    d1 = (d1 + d7);
    d2 = (d2 + (d8 - d6));
    d3 = (d3 + (d7 - d8));
    d4 = (d4 + (d11 * d5));
    d5 = (d5 + (-10.0 * d4));
    d6 = (d6 + ((v10 + 89) & 63));
    d7 = (d7 + (-23.0 * d11));
    d8 = (d8 + (d10 - d5));
    d9 = (d9 + (d3 - d0));
    d10 = (d10 + (d5 - d7));
    d11 = (d11 + d2);
    v8 = v0;
    v6 = f1((d11 - 14.0), -4, 9.0, (d4 + d8), d1, (v3 & 63), d9, d7, 91);
    d9 = f0(-23, d2, (d1 + -24.0), (d11 - 18.0), (d6 + d0), (d10 - d6), ((66 & 255) >> 4), ((v13 & 1023) ^ 507));
    d0 = (d0 + (d10 * d11));
    d1 = (d1 + -34.0);
    d2 = (d2 + (d4 - -22.0));
    d3 = (d3 + (d1 + -39.0));
    d4 = (d4 + (d10 - d7));
    d5 = (d5 + (d6 + 39.0));
    d6 = (d6 + d0);
    d7 = (d7 + d1);
    d8 = (d8 + 21.0);
    d9 = (d9 + 29.0);
    d10 = (d10 + (d6 * 7.0));
    d11 = (d11 + -34.0);
    if ((v4 != ((((v5 & 1023) & 777) & 255) << 4))) {
        v1 = (v13 - ((80 & 1023) | 844));
    } else {
        if ((v5 != (v5 / -6))) {
            arr[((v2 + v9)) & 7] = ((v14 & 255) >> 2);
        } else {
            v4 = (v5 + 53);
        }
    }
    for (int i79 = 0; i79 < 3; i79++) {
        v4 = v12;
        v4 = v0;
    }
    d4 = f0(((v2 & 255) >> 4), (d11 - d9), (((-47 & 1023) ^ 450) & 63), (d2 - d2), (d11 - d11), (d11 - d11), ((100 & 1023) & 927), v12);
    d10 = f0(((v15 & 1023) ^ 819), (d8 - 6.0), d8, (v0 & 63), d1, (v4 & 63), v15, ((v0 & 1023) & 564));
    d0 = (d0 + (2.0 - d7));
    d1 = (d1 + (6.0 * 33.0));
    d2 = (d2 + d10);
    d3 = (d3 + ((v10 + 80) & 63));
    d4 = (d4 + (-20.0 - d5));
    d5 = (d5 + (d1 - -6.0));
    d6 = (d6 + d2);
    d7 = (d7 + (d0 - -33.0));
    d8 = (d8 + (d7 - -6.0));
    d9 = (d9 + (((-83 & 1023) ^ 848) & 63));
    d10 = (d10 + (d5 - d9));
    d11 = (d11 + (38.0 - d7));
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != 300436.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
