// EXIT: 0
// OUTPUT: 4025
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8) {
    for (int i83 = 0; i83 < 1; i83++) {
        if ((p6 >= 47)) {
            if ((p0 <= p5)) {
                if ((p5 == p8)) {
                    p2 = p3;
                    p6 = i83;
                } else {
                    if ((p0 != p8)) {
                        if ((p3 <= p6)) {
                            p1 = p1;
                        } else {
                            if ((p4 != p5)) {
                                p0 = i83;
                                if ((i83 <= -95)) {
                                    if ((p1 <= p1)) {
                                        p5 = i83;
                                    } else {
                                        p3 = p6;
                                        p0 = -69;
                                    }
                                    p4 = p1;
                                } else {
                                    p0 = p7;
                                    p2 = p2;
                                }
                            } else {
                                if ((p6 > p5)) {
                                    p3 = p0;
                                    p7 = -81;
                                } else {
                                    p3 = p5;
                                    p2 = p0;
                                }
                            }
                            p2 = p7;
                        }
                    } else {
                        p1 = p2;
                    }
                    p3 = p8;
                }
            } else {
                p8 = p3;
            }
        } else {
            p0 = p2;
            p2 = p6;
        }
    }
    if ((((47 & 1023) & 396) >= ((-7 & 255) >> 0))) {
        p1 = p3;
    } else {
        for (int i56 = 0; i56 < 1; i56++) {
            if ((p7 >= i56)) {
                p2 = p2;
            } else {
                if ((p3 != p5)) {
                    if ((-22 >= p6)) {
                        p7 = p7;
                    } else {
                        p8 = p0;
                        p0 = p8;
                    }
                    p1 = p2;
                } else {
                    p0 = p8;
                }
                p8 = 90;
            }
        }
        p7 = p7;
    }
    for (int i9 = 0; i9 < 1; i9++) {
        p8 = (74 - p5);
    }
    return ((((p1 & 255) << 4) & 1023) | 566);
}

int f1(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8) {
    for (int i56 = 0; i56 < 3; i56++) {
        p8 = p5;
    }
    if ((p3 > -26)) {
        for (int i99 = 0; i99 < 1; i99++) {
            p0 = -55;
            p0 = -87;
            p5 = p1;
        }
        if ((p2 > p1)) {
            if ((p7 >= p7)) {
                for (int i99 = 0; i99 < 1; i99++) {
                    p6 = p4;
                }
            } else {
                if ((-23 < p4)) {
                    p0 = p1;
                } else {
                    if ((48 != p0)) {
                        if ((p5 >= p6)) {
                            if ((p3 != p5)) {
                                p8 = p7;
                            } else {
                                if ((63 >= p3)) {
                                    p1 = p6;
                                    p0 = p2;
                                } else {
                                    p5 = p6;
                                }
                                p1 = p0;
                            }
                            p8 = p8;
                        } else {
                            p3 = p2;
                            if ((p0 != p0)) {
                                if ((p2 <= p6)) {
                                    if ((p6 >= p2)) {
                                        p3 = p8;
                                    } else {
                                        p5 = p2;
                                    }
                                    if ((p1 == p4)) {
                                        for (int i54 = 0; i54 < 4; i54++) {
                                            p4 = i54;
                                            p8 = p2;
                                            p6 = 94;
                                        }
                                        if ((p8 != 96)) {
                                            p8 = p7;
                                            p6 = p4;
                                        } else {
                                            p3 = p8;
                                        }
                                    } else {
                                        if ((-96 > 19)) {
                                            p5 = p2;
                                        } else {
                                            if ((p1 >= p0)) {
                                                p0 = p3;
                                                p7 = p6;
                                            } else {
                                                if ((-69 == p2)) {
                                                    p0 = p0;
                                                } else {
                                                    p3 = 36;
                                                }
                                                if ((-11 != p6)) {
                                                    if ((p5 <= p3)) {
                                                        if ((p1 >= p5)) {
                                                            p7 = 25;
                                                            if ((p3 >= p5)) {
                                                                p3 = 89;
                                                            } else {
                                                                p8 = p8;
                                                                for (int i60 = 0; i60 < 4; i60++) {
                                                                    p4 = p5;
                                                                    if ((p7 > p5)) {
                                                                        p2 = p4;
                                                                        p6 = p4;
                                                                    } else {
                                                                        p4 = 45;
                                                                        p5 = 91;
                                                                    }
                                                                    if ((p7 != 27)) {
                                                                        p0 = -84;
                                                                        if ((p7 == 53)) {
                                                                            p1 = -80;
                                                                        } else {
                                                                            p6 = p8;
                                                                            p6 = -9;
                                                                        }
                                                                    } else {
                                                                        p7 = p8;
                                                                        if ((p0 == p0)) {
                                                                            if ((p6 < p6)) {
                                                                                if ((3 != -60)) {
                                                                                    if ((p4 != p6)) {
                                                                                        p0 = p6;
                                                                                    } else {
                                                                                        p7 = i60;
                                                                                    }
                                                                                } else {
                                                                                    if ((p6 == p1)) {
                                                                                        p5 = p4;
                                                                                    } else {
                                                                                        p3 = p4;
                                                                                    }
                                                                                }
                                                                            } else {
                                                                                p4 = -47;
                                                                            }
                                                                        } else {
                                                                            p8 = 40;
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        } else {
                                                            p5 = -27;
                                                        }
                                                    } else {
                                                        p2 = p2;
                                                        p5 = 81;
                                                    }
                                                    for (int i58 = 0; i58 < 5; i58++) {
                                                        if ((1 >= p2)) {
                                                            p1 = i58;
                                                            p8 = p4;
                                                        } else {
                                                            p2 = p2;
                                                            p4 = -41;
                                                        }
                                                        p6 = p1;
                                                        p5 = 51;
                                                    }
                                                } else {
                                                    p5 = -47;
                                                }
                                            }
                                            for (int i5 = 0; i5 < 6; i5++) {
                                                if ((p0 == i5)) {
                                                    p2 = p8;
                                                } else {
                                                    p4 = 44;
                                                    p5 = p5;
                                                }
                                            }
                                        }
                                        p4 = p8;
                                    }
                                } else {
                                    p2 = -33;
                                    p4 = p5;
                                }
                                p1 = p8;
                            } else {
                                p5 = p4;
                                p0 = -58;
                            }
                        }
                        p6 = p7;
                    } else {
                        if ((23 != p1)) {
                            p1 = p1;
                        } else {
                            for (int i97 = 0; i97 < 2; i97++) {
                                p0 = p2;
                                if ((36 <= -77)) {
                                    p4 = p6;
                                    p1 = p7;
                                } else {
                                    p2 = 33;
                                    p1 = p3;
                                }
                                if ((-88 < -37)) {
                                    if ((p7 == p6)) {
                                        p3 = p5;
                                        if ((p8 < 63)) {
                                            if ((p7 >= -40)) {
                                                p8 = 46;
                                                if ((p7 > -50)) {
                                                    if ((37 <= p4)) {
                                                        p1 = p8;
                                                    } else {
                                                        if ((p7 >= p7)) {
                                                            p7 = p1;
                                                            p3 = p1;
                                                        } else {
                                                            if ((p3 >= 21)) {
                                                                p8 = i97;
                                                                p7 = 28;
                                                            } else {
                                                                p4 = i97;
                                                                if ((p4 < p8)) {
                                                                    if ((p6 > p1)) {
                                                                        p0 = p7;
                                                                    } else {
                                                                        if ((p8 != p6)) {
                                                                            if ((p3 == -4)) {
                                                                                if ((p5 == -78)) {
                                                                                    if ((p4 <= -55)) {
                                                                                        p3 = p5;
                                                                                    } else {
                                                                                        p0 = p8;
                                                                                    }
                                                                                    p4 = p6;
                                                                                } else {
                                                                                    p4 = p4;
                                                                                    p8 = p8;
                                                                                }
                                                                            } else {
                                                                                p8 = p1;
                                                                            }
                                                                        } else {
                                                                            p2 = p2;
                                                                        }
                                                                    }
                                                                } else {
                                                                    p3 = -14;
                                                                }
                                                            }
                                                        }
                                                    }
                                                    if ((p8 <= p6)) {
                                                        p3 = p3;
                                                    } else {
                                                        p7 = p7;
                                                    }
                                                } else {
                                                    if ((p2 == p5)) {
                                                        p0 = p3;
                                                    } else {
                                                        p7 = i97;
                                                        p7 = p2;
                                                    }
                                                }
                                            } else {
                                                p1 = p8;
                                            }
                                            p5 = p6;
                                        } else {
                                            p8 = p7;
                                            p4 = p5;
                                        }
                                    } else {
                                        p6 = p0;
                                    }
                                } else {
                                    p6 = p0;
                                }
                            }
                            p0 = p5;
                        }
                        p3 = p3;
                    }
                }
            }
        } else {
            p6 = p0;
        }
    } else {
        for (int i88 = 0; i88 < 2; i88++) {
            p5 = 7;
            if ((12 <= p0)) {
                if ((-9 <= p5)) {
                    p8 = -4;
                } else {
                    p2 = p4;
                }
            } else {
                p4 = p4;
            }
            p5 = 89;
        }
        for (int i70 = 0; i70 < 6; i70++) {
            p4 = p2;
            p8 = p2;
        }
    }
    if (((p2 % 4) >= (p8 + p5))) {
        p5 = 43;
    } else {
        p8 = p6;
        for (int i71 = 0; i71 < 1; i71++) {
            p5 = -73;
            if ((p3 < p3)) {
                if ((p4 < p6)) {
                    if ((p7 < p8)) {
                        if ((-94 != p4)) {
                            p2 = -40;
                        } else {
                            if ((-64 != 51)) {
                                if ((p0 > p6)) {
                                    p0 = p5;
                                } else {
                                    p3 = i71;
                                    if ((-94 > p7)) {
                                        p7 = -97;
                                        p5 = p3;
                                    } else {
                                        p2 = p5;
                                    }
                                }
                            } else {
                                if ((83 < p2)) {
                                    p6 = -55;
                                } else {
                                    p1 = p6;
                                    p8 = -13;
                                }
                                p8 = p4;
                            }
                            if ((p7 <= p3)) {
                                p2 = -33;
                            } else {
                                p0 = p5;
                                p4 = -76;
                            }
                        }
                    } else {
                        p5 = p4;
                    }
                    p0 = -71;
                } else {
                    p2 = -48;
                    p8 = p1;
                }
                p6 = p6;
            } else {
                p0 = p0;
                p6 = p4;
            }
        }
    }
    return (((-19 * -31) & 1023) & 382);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 2;
    int v1 = 3;
    int v2 = -25;
    int v3 = -17;
    int v4 = 32;
    int v5 = -28;
    int v6 = -25;
    int v7 = 49;
    int v8 = 30;
    int v9 = -1;
    double d0 = -23.0;
    double d1 = 0.0;
    double d2 = -2.0;
    double d3 = -10.0;
    double d4 = -30.0;
    double d5 = -18.0;
    v5 = (75 + ((26 & 255) >> 3));
    v6 = ((-89 & 1023) & 969);
    v2 = f0((v5 / 2), 22, (v6 % 7), v0, v6, ((32 & 255) >> 2), (v3 + v5), ((v1 & 255) << 0), (v7 * v3));
    v4 = f1((v8 * 20), (v6 * v9), (43 - v8), ((v4 & 255) << 4), ((-10 & 1023) & 0), ((-25 & 255) << 0), ((v5 & 1023) & 140), (v0 * v2), ((70 & 1023) ^ 871));
    d0 = (d0 + (d1 + d3));
    d1 = (d1 + (d3 + -13.0));
    d2 = (d2 + (d5 + d3));
    d3 = (d3 + (d4 * d3));
    d4 = (d4 + (d3 + d4));
    d5 = (d5 + ((v9 + v7) & 63));
    if (((((v2 & 1023) | 443) % 11) <= (((v2 / -6) & 1023) & 381))) {
        for (int i36 = 0; i36 < 5; i36++) {
            v7 = (v6 + v8);
            v1 = ((v6 & 1023) | 222);
        }
    } else {
        if ((((29 & 1023) ^ 421) > ((v0 & 255) << 1))) {
            v7 = (73 * v3);
            v5 = arr[(v2) & 7];
        } else {
            for (int i88 = 0; i88 < 5; i88++) {
                v8 = -27;
                v7 = v7;
                v8 = v3;
            }
            v6 = arr[(11) & 7];
        }
        arr[(((v5 & 1023) | 730)) & 7] = (((-78 + -78) & 1023) | 653);
    }
    v2 = f0((v3 - v2), ((v9 & 1023) | 247), 62, -70, (v4 * -30), ((v5 & 255) >> 4), (-20 + v2), v2, v6);
    d0 = (d0 + d1);
    d1 = (d1 + (d5 + d1));
    d2 = (d2 + (-30.0 + d2));
    d3 = (d3 + (d2 * 20.0));
    d4 = (d4 + d0);
    d5 = (d5 + d4);
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != -1294.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
