// EXIT: 0
// OUTPUT: 2154
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10) {
    if (((p10 % -6) == ((p4 & 1023) & 1011))) {
        if ((p0 <= p5)) {
            for (int i94 = 0; i94 < 2; i94++) {
                p8 = p2;
            }
            p9 = p6;
        } else {
            for (int i81 = 0; i81 < 2; i81++) {
                p10 = p4;
            }
            if ((p7 == 98)) {
                if ((27 > p8)) {
                    for (int i64 = 0; i64 < 4; i64++) {
                        p10 = p6;
                        p0 = -29;
                        if ((p1 != p9)) {
                            p4 = 64;
                            p1 = p2;
                        } else {
                            p5 = i64;
                            p4 = -31;
                        }
                    }
                } else {
                    if ((-85 >= p4)) {
                        if ((-10 != 0)) {
                            p2 = p8;
                        } else {
                            p10 = p0;
                            if ((p4 <= p3)) {
                                for (int i66 = 0; i66 < 1; i66++) {
                                    p4 = p3;
                                }
                                p2 = p8;
                            } else {
                                p10 = p6;
                            }
                        }
                        p9 = -75;
                    } else {
                        p6 = p6;
                    }
                }
            } else {
                p10 = -46;
            }
        }
    } else {
        p2 = (p7 % 11);
        p8 = ((p3 & 1023) ^ 1020);
    }
    for (int i48 = 0; i48 < 2; i48++) {
        p1 = ((p6 & 1023) ^ 330);
        p10 = ((p6 & 1023) ^ 524);
    }
    p4 = ((((p3 & 255) << 0) & 255) >> 4);
    return (((p5 & 1023) & 785) / 2);
}

int f1(int p0, int p1, int p2, int p3, int p4, int p5, int p6) {
    for (int i62 = 0; i62 < 3; i62++) {
        p6 = ((p0 & 1023) ^ 7);
        if ((-88 > i62)) {
            p0 = p3;
        } else {
            if ((p5 == i62)) {
                p0 = i62;
            } else {
                if ((p0 <= p4)) {
                    p3 = p6;
                    p2 = 32;
                } else {
                    if ((p1 <= p0)) {
                        p4 = p0;
                    } else {
                        p4 = p6;
                    }
                    p5 = 100;
                }
                p2 = p3;
            }
            p2 = p4;
        }
        p5 = (i62 * p6);
    }
    return (((p4 - p6) & 1023) ^ 147);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = -32;
    int v1 = 2;
    int v2 = -40;
    int v3 = 38;
    int v4 = -1;
    int v5 = 50;
    int v6 = 44;
    int v7 = 12;
    int v8 = -3;
    int v9 = -41;
    double d0 = 26.0;
    double d1 = 17.0;
    double d2 = -27.0;
    double d3 = 3.0;
    double d4 = -19.0;
    double d5 = 0.0;
    for (int i92 = 0; i92 < 3; i92++) {
        v3 = ((((-100 & 1023) & 720) & 255) << 3);
        v3 = ((v2 % 11) * i92);
        v1 = ((1 / 2) * ((v3 & 255) << 0));
    }
    if ((((((v8 & 255) << 2) & 1023) & 859) == (((v4 & 1023) | 403) + 97))) {
        v8 = v6;
    } else {
        arr[((v5 + 12)) & 7] = 49;
    }
    v0 = f0(v3, v5, v9, v4, v6, (v0 % 3), ((v1 & 1023) & 662), -94, 53, v5, (v9 - -95));
    v0 = f0((v8 - v6), -90, 9, v5, (v5 / 5), (v9 + v2), -72, ((-15 & 1023) ^ 19), ((-33 & 255) >> 4), v2, ((v6 & 1023) | 475));
    d0 = (d0 + -24.0);
    d1 = (d1 + d0);
    d2 = (d2 + (d5 + d3));
    d3 = (d3 + (d3 - d1));
    d4 = (d4 + (d5 * d1));
    d5 = (d5 + d3);
    for (int i52 = 0; i52 < 4; i52++) {
        v2 = ((v4 & 1023) ^ 890);
    }
    arr[((v0 / 3)) & 7] = (((((v5 % 11) & 255) << 2) & 1023) | 727);
    if ((((v1 - -59) * ((26 & 1023) ^ 281)) < ((v1 % -6) * ((v1 & 1023) & 540)))) {
        v1 = (v7 % 11);
    } else {
        arr[(((v3 & 1023) | 797)) & 7] = (((85 * v2) & 1023) | 331);
    }
    v9 = f0(v7, ((v4 & 255) >> 4), 68, (v7 % -3), ((v5 & 255) >> 3), v4, v8, (-46 % 7), ((24 & 1023) & 687), -59, (-30 / 8));
    d0 = (d0 + (((v5 & 255) >> 0) & 63));
    d1 = (d1 + (d1 - -25.0));
    d2 = (d2 + (((v6 & 1023) ^ 304) & 63));
    d3 = (d3 + (d1 - d5));
    d4 = (d4 + (d4 * d3));
    d5 = (d5 + d1);
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != -984.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
