// Optimistic coalescing merges every copy whose endpoints do not interfere,
// which is more than this function's graph can take: colouring it comes back
// with `gpr_overshoot=1`, the over-budget value a block parameter, and nothing
// live at that point spillable. Without the un-coalescing retry in
// `allocate_global` it does not compile at all.
//
// One round is enough -- 5 merges denied, out of the whole function's copies.
// It is the only program in `lit`, `bench`, `live`, the corpus or 1352
// generated programs that has ever needed a second attempt.
//
// gen_c.py seed 164, shape args, unreduced: reducing it would very likely
// change which merges the colouring blames, and the shape is the point.
// EXIT: 0
// OUTPUT: -3710
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10, int p11) {
    for (int i9 = 0; i9 < 5; i9++) {
        p10 = i9;
    }
    if (((75 / -6) <= ((10 & 1023) & 856))) {
        if ((p3 >= p4)) {
            if ((-20 > p7)) {
                for (int i27 = 0; i27 < 5; i27++) {
                    p1 = p0;
                }
            } else {
                p10 = p7;
                p0 = p8;
            }
            if ((p8 >= p3)) {
                if ((p3 >= -99)) {
                    if ((p0 == p10)) {
                        if ((p11 >= -93)) {
                            if ((p0 > -84)) {
                                for (int i0 = 0; i0 < 2; i0++) {
                                    if ((p6 >= p0)) {
                                        if ((-7 >= p1)) {
                                            p8 = p5;
                                        } else {
                                            if ((p0 > p8)) {
                                                p10 = p3;
                                            } else {
                                                if ((p4 <= p2)) {
                                                    p0 = i0;
                                                    p6 = p1;
                                                } else {
                                                    p10 = p2;
                                                    p6 = -49;
                                                }
                                                p5 = p5;
                                            }
                                            if ((i0 > p2)) {
                                                p3 = 86;
                                                if ((2 == p5)) {
                                                    p5 = p5;
                                                } else {
                                                    if ((p2 > p11)) {
                                                        if ((-48 > p3)) {
                                                            p6 = -45;
                                                        } else {
                                                            p2 = p0;
                                                        }
                                                    } else {
                                                        if ((p7 == -90)) {
                                                            p2 = p11;
                                                            p6 = p4;
                                                        } else {
                                                            if ((p3 <= p3)) {
                                                                p8 = p9;
                                                                p11 = p10;
                                                            } else {
                                                                if ((99 != 81)) {
                                                                    p11 = p9;
                                                                    p3 = p8;
                                                                } else {
                                                                    p0 = -72;
                                                                }
                                                            }
                                                        }
                                                        p6 = p9;
                                                    }
                                                }
                                            } else {
                                                if ((p0 >= p1)) {
                                                    p3 = p7;
                                                    p8 = p9;
                                                } else {
                                                    p5 = -80;
                                                }
                                            }
                                        }
                                        p3 = -24;
                                    } else {
                                        if ((30 >= p7)) {
                                            if ((p5 <= p10)) {
                                                p2 = p5;
                                                p2 = p10;
                                            } else {
                                                p5 = p7;
                                                if ((p6 == p7)) {
                                                    if ((p0 >= p7)) {
                                                        p8 = p11;
                                                        p2 = p7;
                                                    } else {
                                                        if ((i0 <= p1)) {
                                                            p8 = 13;
                                                            p10 = -20;
                                                        } else {
                                                            p9 = p4;
                                                        }
                                                    }
                                                    if ((i0 > p4)) {
                                                        p11 = p7;
                                                    } else {
                                                        p0 = i0;
                                                    }
                                                } else {
                                                    if ((p7 <= 29)) {
                                                        if ((21 == p7)) {
                                                            p1 = p0;
                                                        } else {
                                                            p5 = p5;
                                                            p4 = i0;
                                                        }
                                                    } else {
                                                        p2 = p2;
                                                    }
                                                }
                                            }
                                        } else {
                                            if ((p5 <= p5)) {
                                                p7 = 43;
                                            } else {
                                                if ((p2 != p3)) {
                                                    p3 = -5;
                                                } else {
                                                    if ((i0 == p5)) {
                                                        p10 = 52;
                                                        p11 = i0;
                                                    } else {
                                                        p4 = p7;
                                                        if ((p11 <= p0)) {
                                                            if ((-49 < p1)) {
                                                                p8 = -27;
                                                            } else {
                                                                if ((p8 <= p7)) {
                                                                    p2 = p0;
                                                                } else {
                                                                    p9 = p9;
                                                                }
                                                            }
                                                            p7 = -70;
                                                        } else {
                                                            p6 = p9;
                                                            p3 = p0;
                                                        }
                                                    }
                                                }
                                            }
                                            if ((-79 < p10)) {
                                                p2 = p1;
                                            } else {
                                                p8 = p1;
                                            }
                                        }
                                        p1 = p3;
                                    }
                                }
                                if ((p8 == p1)) {
                                    p9 = p3;
                                } else {
                                    if ((p10 != -91)) {
                                        p2 = 1;
                                    } else {
                                        for (int i97 = 0; i97 < 4; i97++) {
                                            p1 = p7;
                                            if ((85 >= -46)) {
                                                if ((p7 == p0)) {
                                                    if ((p4 == p7)) {
                                                        if ((i97 == p1)) {
                                                            p8 = p0;
                                                            p3 = p1;
                                                        } else {
                                                            if ((p6 == i97)) {
                                                                if ((-9 >= -78)) {
                                                                    if ((i97 != 46)) {
                                                                        p10 = 68;
                                                                    } else {
                                                                        p8 = p10;
                                                                    }
                                                                    if ((p5 <= p2)) {
                                                                        p10 = p3;
                                                                        p6 = p4;
                                                                    } else {
                                                                        p2 = p8;
                                                                    }
                                                                } else {
                                                                    p1 = -24;
                                                                    if ((p2 == p3)) {
                                                                        p6 = p2;
                                                                        p4 = p8;
                                                                    } else {
                                                                        if ((p10 == p9)) {
                                                                            p4 = p8;
                                                                            p0 = p6;
                                                                        } else {
                                                                            if ((p5 != 85)) {
                                                                                if ((52 >= p0)) {
                                                                                    if ((p5 == p5)) {
                                                                                        p5 = p1;
                                                                                        if ((i97 != p7)) {
                                                                                            if ((p5 != 7)) {
                                                                                                p2 = 12;
                                                                                            } else {
                                                                                                p1 = p11;
                                                                                            }
                                                                                            if ((29 > p9)) {
                                                                                                if ((87 >= p10)) {
                                                                                                    p8 = p2;
                                                                                                    p7 = p9;
                                                                                                } else {
                                                                                                    p8 = 63;
                                                                                                }
                                                                                                p0 = p7;
                                                                                            } else {
                                                                                                p10 = 63;
                                                                                                if ((p9 <= p6)) {
                                                                                                    p6 = p4;
                                                                                                    if ((i97 <= p5)) {
                                                                                                        if ((12 >= -59)) {
                                                                                                            if ((i97 == p0)) {
                                                                                                                p1 = p4;
                                                                                                                p4 = -22;
                                                                                                            } else {
                                                                                                                p8 = 40;
                                                                                                                if ((p1 <= i97)) {
                                                                                                                    p8 = 3;
                                                                                                                    if ((p4 > p6)) {
                                                                                                                        p4 = p11;
                                                                                                                    } else {
                                                                                                                        p9 = p2;
                                                                                                                        p9 = p8;
                                                                                                                    }
                                                                                                                } else {
                                                                                                                    if ((p8 <= p10)) {
                                                                                                                        if ((p3 >= p2)) {
                                                                                                                            if ((p11 < p2)) {
                                                                                                                                p2 = p9;
                                                                                                                                p2 = p7;
                                                                                                                            } else {
                                                                                                                                p9 = p8;
                                                                                                                                if ((p9 > p7)) {
                                                                                                                                    p11 = i97;
                                                                                                                                } else {
                                                                                                                                    if ((7 != p8)) {
                                                                                                                                        p10 = p7;
                                                                                                                                    } else {
                                                                                                                                        p3 = p10;
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                            if ((26 <= 81)) {
                                                                                                                                if ((p2 <= p5)) {
                                                                                                                                    if ((-25 <= p1)) {
                                                                                                                                        p11 = p3;
                                                                                                                                    } else {
                                                                                                                                        p5 = p4;
                                                                                                                                        p8 = p9;
                                                                                                                                    }
                                                                                                                                    p8 = p4;
                                                                                                                                } else {
                                                                                                                                    p5 = p3;
                                                                                                                                }
                                                                                                                            } else {
                                                                                                                                p5 = p0;
                                                                                                                            }
                                                                                                                        } else {
                                                                                                                            if ((p5 > p10)) {
                                                                                                                                p9 = p11;
                                                                                                                            } else {
                                                                                                                                if ((p7 < p1)) {
                                                                                                                                    p1 = p0;
                                                                                                                                    p3 = p1;
                                                                                                                                } else {
                                                                                                                                    p11 = p6;
                                                                                                                                }
                                                                                                                                p7 = p7;
                                                                                                                            }
                                                                                                                        }
                                                                                                                        p1 = -1;
                                                                                                                    } else {
                                                                                                                        p1 = p3;
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        } else {
                                                                                                            p2 = -39;
                                                                                                            p10 = p10;
                                                                                                        }
                                                                                                    } else {
                                                                                                        p7 = 38;
                                                                                                    }
                                                                                                } else {
                                                                                                    p2 = p7;
                                                                                                }
                                                                                            }
                                                                                        } else {
                                                                                            if ((-51 == p3)) {
                                                                                                if ((p10 > p11)) {
                                                                                                    p1 = p4;
                                                                                                } else {
                                                                                                    p9 = i97;
                                                                                                }
                                                                                            } else {
                                                                                                p0 = p0;
                                                                                                if ((18 < p3)) {
                                                                                                    p4 = -62;
                                                                                                    p10 = p4;
                                                                                                } else {
                                                                                                    p8 = p6;
                                                                                                    p1 = p5;
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    } else {
                                                                                        if ((42 <= -54)) {
                                                                                            p7 = p2;
                                                                                        } else {
                                                                                            if ((i97 >= p2)) {
                                                                                                p5 = -18;
                                                                                            } else {
                                                                                                p7 = p0;
                                                                                                p8 = p5;
                                                                                            }
                                                                                        }
                                                                                        p11 = p1;
                                                                                    }
                                                                                    p10 = -49;
                                                                                } else {
                                                                                    if ((p9 <= p6)) {
                                                                                        p2 = p7;
                                                                                    } else {
                                                                                        if ((p10 < 72)) {
                                                                                            p8 = p1;
                                                                                        } else {
                                                                                            if ((p0 == p3)) {
                                                                                                p0 = p0;
                                                                                                if ((57 < -15)) {
                                                                                                    p3 = 36;
                                                                                                } else {
                                                                                                    if ((i97 != p10)) {
                                                                                                        p1 = p2;
                                                                                                        if ((p6 < p2)) {
                                                                                                            if ((p0 == i97)) {
                                                                                                                p0 = p8;
                                                                                                            } else {
                                                                                                                p10 = 2;
                                                                                                                if ((i97 == i97)) {
                                                                                                                    if ((-88 < p9)) {
                                                                                                                        if ((25 >= p7)) {
                                                                                                                            if ((p5 > p3)) {
                                                                                                                                p6 = p8;
                                                                                                                                if ((16 == p5)) {
                                                                                                                                    p0 = p6;
                                                                                                                                } else {
                                                                                                                                    p11 = p5;
                                                                                                                                }
                                                                                                                            } else {
                                                                                                                                p9 = 73;
                                                                                                                                p10 = p4;
                                                                                                                            }
                                                                                                                            if ((p2 <= p5)) {
                                                                                                                                if ((44 > p0)) {
                                                                                                                                    p8 = p3;
                                                                                                                                } else {
                                                                                                                                    p2 = p3;
                                                                                                                                    p8 = p11;
                                                                                                                                }
                                                                                                                            } else {
                                                                                                                                p2 = -75;
                                                                                                                                if ((p8 <= p5)) {
                                                                                                                                    if ((-35 == p5)) {
                                                                                                                                        p11 = 86;
                                                                                                                                    } else {
                                                                                                                                        if ((-85 < p0)) {
                                                                                                                                            p3 = -82;
                                                                                                                                        } else {
                                                                                                                                            p11 = i97;
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                } else {
                                                                                                                                    p1 = p11;
                                                                                                                                    p5 = p11;
                                                                                                                                }
                                                                                                                            }
                                                                                                                        } else {
                                                                                                                            p11 = 74;
                                                                                                                        }
                                                                                                                        p11 = 64;
                                                                                                                    } else {
                                                                                                                        if ((p0 < i97)) {
                                                                                                                            p0 = p10;
                                                                                                                            p10 = p0;
                                                                                                                        } else {
                                                                                                                            if ((p6 <= p8)) {
                                                                                                                                if ((65 <= 80)) {
                                                                                                                                    p4 = p0;
                                                                                                                                    if ((p5 > -63)) {
                                                                                                                                        p8 = p9;
                                                                                                                                    } else {
                                                                                                                                        if ((p3 >= p4)) {
                                                                                                                                            p7 = p2;
                                                                                                                                        } else {
                                                                                                                                            if ((p3 >= p5)) {
                                                                                                                                                p2 = p1;
                                                                                                                                            } else {
                                                                                                                                                p6 = 86;
                                                                                                                                            }
                                                                                                                                            p11 = p10;
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                } else {
                                                                                                                                    p2 = p5;
                                                                                                                                    p6 = p1;
                                                                                                                                }
                                                                                                                            } else {
                                                                                                                                if ((i97 == p11)) {
                                                                                                                                    p1 = p5;
                                                                                                                                } else {
                                                                                                                                    p3 = -87;
                                                                                                                                    p7 = p5;
                                                                                                                                }
                                                                                                                                p0 = -1;
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                    if ((p5 > 78)) {
                                                                                                                        p6 = p2;
                                                                                                                        if ((p3 <= -14)) {
                                                                                                                            p3 = 64;
                                                                                                                        } else {
                                                                                                                            if ((p3 > -75)) {
                                                                                                                                p7 = p11;
                                                                                                                            } else {
                                                                                                                                p10 = p10;
                                                                                                                            }
                                                                                                                        }
                                                                                                                    } else {
                                                                                                                        p1 = p7;
                                                                                                                        p9 = -82;
                                                                                                                    }
                                                                                                                } else {
                                                                                                                    if ((p6 >= p10)) {
                                                                                                                        p6 = -19;
                                                                                                                        p10 = p0;
                                                                                                                    } else {
                                                                                                                        if ((63 < p7)) {
                                                                                                                            if ((p7 >= 56)) {
                                                                                                                                p8 = p8;
                                                                                                                            } else {
                                                                                                                                p3 = p8;
                                                                                                                            }
                                                                                                                        } else {
                                                                                                                            p3 = p10;
                                                                                                                            p6 = p1;
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                            p10 = p6;
                                                                                                        } else {
                                                                                                            p8 = p10;
                                                                                                            p6 = 11;
                                                                                                        }
                                                                                                    } else {
                                                                                                        if ((-82 <= p5)) {
                                                                                                            p1 = p0;
                                                                                                            p11 = p3;
                                                                                                        } else {
                                                                                                            p8 = p1;
                                                                                                            p2 = -48;
                                                                                                        }
                                                                                                        p1 = -88;
                                                                                                    }
                                                                                                }
                                                                                            } else {
                                                                                                if ((-34 < -46)) {
                                                                                                    p7 = p2;
                                                                                                } else {
                                                                                                    p2 = i97;
                                                                                                    p7 = -72;
                                                                                                }
                                                                                            }
                                                                                            if ((-100 >= p3)) {
                                                                                                p6 = 35;
                                                                                                p8 = p8;
                                                                                            } else {
                                                                                                p5 = p3;
                                                                                            }
                                                                                        }
                                                                                        p6 = i97;
                                                                                    }
                                                                                }
                                                                                if ((-49 == 87)) {
                                                                                    p5 = 15;
                                                                                    p8 = p5;
                                                                                } else {
                                                                                    p5 = p6;
                                                                                    p9 = 33;
                                                                                }
                                                                            } else {
                                                                                p1 = i97;
                                                                                p8 = p7;
                                                                            }
                                                                            p2 = p5;
                                                                        }
                                                                        p3 = -31;
                                                                    }
                                                                }
                                                                p4 = i97;
                                                            } else {
                                                                if ((p9 != p9)) {
                                                                    if ((p4 != -18)) {
                                                                        if ((i97 > 32)) {
                                                                            if ((p10 != p2)) {
                                                                                p0 = p7;
                                                                            } else {
                                                                                p6 = p0;
                                                                                if ((-78 > -67)) {
                                                                                    if ((p3 > p3)) {
                                                                                        if ((p6 == p11)) {
                                                                                            p8 = p6;
                                                                                            p7 = p7;
                                                                                        } else {
                                                                                            p2 = p5;
                                                                                        }
                                                                                        if ((35 < -99)) {
                                                                                            if ((p7 < p5)) {
                                                                                                if ((i97 <= p11)) {
                                                                                                    p10 = p10;
                                                                                                    p3 = p6;
                                                                                                } else {
                                                                                                    p2 = -74;
                                                                                                }
                                                                                            } else {
                                                                                                if ((-40 >= 44)) {
                                                                                                    p10 = 51;
                                                                                                    p0 = p3;
                                                                                                } else {
                                                                                                    p1 = -86;
                                                                                                }
                                                                                            }
                                                                                            p0 = p10;
                                                                                        } else {
                                                                                            if ((p4 > p4)) {
                                                                                                if ((p4 > p11)) {
                                                                                                    p3 = p9;
                                                                                                } else {
                                                                                                    p2 = i97;
                                                                                                }
                                                                                            } else {
                                                                                                p7 = 43;
                                                                                                p11 = -83;
                                                                                            }
                                                                                            p11 = i97;
                                                                                        }
                                                                                    } else {
                                                                                        p7 = p3;
                                                                                        p5 = i97;
                                                                                    }
                                                                                    p0 = p8;
                                                                                } else {
                                                                                    p11 = -64;
                                                                                    p2 = 48;
                                                                                }
                                                                            }
                                                                            if ((p10 == p7)) {
                                                                                p2 = -22;
                                                                            } else {
                                                                                if ((47 == -82)) {
                                                                                    if ((-51 != 100)) {
                                                                                        if ((p6 != p5)) {
                                                                                            p4 = p2;
                                                                                        } else {
                                                                                            p3 = -6;
                                                                                            p0 = p0;
                                                                                        }
                                                                                    } else {
                                                                                        if ((p11 <= p11)) {
                                                                                            if ((p0 <= -25)) {
                                                                                                p10 = p3;
                                                                                            } else {
                                                                                                p4 = p3;
                                                                                            }
                                                                                            p8 = 84;
                                                                                        } else {
                                                                                            if ((p10 > p8)) {
                                                                                                if ((i97 > -72)) {
                                                                                                    p9 = p4;
                                                                                                } else {
                                                                                                    p9 = p1;
                                                                                                }
                                                                                            } else {
                                                                                                p10 = 99;
                                                                                            }
                                                                                            p0 = p4;
                                                                                        }
                                                                                        if ((p9 >= p9)) {
                                                                                            if ((-1 == -58)) {
                                                                                                p7 = p3;
                                                                                                p9 = p4;
                                                                                            } else {
                                                                                                p5 = p10;
                                                                                            }
                                                                                            p4 = p11;
                                                                                        } else {
                                                                                            if ((-90 >= -58)) {
                                                                                                if ((81 > -22)) {
                                                                                                    p10 = p0;
                                                                                                } else {
                                                                                                    p5 = -93;
                                                                                                    p8 = p9;
                                                                                                }
                                                                                            } else {
                                                                                                p0 = -55;
                                                                                                if ((p2 >= p2)) {
                                                                                                    p3 = 62;
                                                                                                    if ((p10 > p6)) {
                                                                                                        p5 = -58;
                                                                                                    } else {
                                                                                                        p6 = -64;
                                                                                                    }
                                                                                                } else {
                                                                                                    p6 = p10;
                                                                                                }
                                                                                            }
                                                                                            p11 = p4;
                                                                                        }
                                                                                    }
                                                                                    if ((p5 >= p7)) {
                                                                                        p3 = p2;
                                                                                    } else {
                                                                                        p4 = 90;
                                                                                        if ((p7 > p5)) {
                                                                                            p6 = 55;
                                                                                        } else {
                                                                                            if ((p7 > 15)) {
                                                                                                p9 = -96;
                                                                                            } else {
                                                                                                p0 = p8;
                                                                                                p8 = p6;
                                                                                            }
                                                                                            p9 = p9;
                                                                                        }
                                                                                    }
                                                                                } else {
                                                                                    p2 = p3;
                                                                                    p5 = p3;
                                                                                }
                                                                            }
                                                                        } else {
                                                                            p4 = p0;
                                                                        }
                                                                        if ((p10 != p10)) {
                                                                            if ((29 == p10)) {
                                                                                p5 = p3;
                                                                            } else {
                                                                                p0 = p9;
                                                                            }
                                                                        } else {
                                                                            p11 = p10;
                                                                            if ((p1 < 27)) {
                                                                                p7 = p0;
                                                                            } else {
                                                                                p3 = 93;
                                                                            }
                                                                        }
                                                                    } else {
                                                                        if ((p2 >= p1)) {
                                                                            p9 = p11;
                                                                            p1 = p7;
                                                                        } else {
                                                                            p10 = p9;
                                                                            if ((p6 > 83)) {
                                                                                p9 = p9;
                                                                                if ((64 >= p11)) {
                                                                                    p8 = p4;
                                                                                    if ((p9 == 29)) {
                                                                                        p2 = p7;
                                                                                        if ((-50 < p10)) {
                                                                                            p9 = 74;
                                                                                            p0 = p1;
                                                                                        } else {
                                                                                            p8 = p4;
                                                                                        }
                                                                                    } else {
                                                                                        if ((i97 != p2)) {
                                                                                            p2 = p7;
                                                                                            p8 = p0;
                                                                                        } else {
                                                                                            p9 = p5;
                                                                                        }
                                                                                        p10 = -17;
                                                                                    }
                                                                                } else {
                                                                                    if ((p3 != p3)) {
                                                                                        p3 = p6;
                                                                                        if ((p8 >= -40)) {
                                                                                            p6 = p2;
                                                                                            p3 = p4;
                                                                                        } else {
                                                                                            p10 = p4;
                                                                                            p9 = -10;
                                                                                        }
                                                                                    } else {
                                                                                        p4 = p11;
                                                                                        if ((p1 != p10)) {
                                                                                            if ((-95 < 8)) {
                                                                                                p1 = 44;
                                                                                            } else {
                                                                                                p9 = 89;
                                                                                            }
                                                                                            p3 = -16;
                                                                                        } else {
                                                                                            if ((p9 == p7)) {
                                                                                                p8 = p4;
                                                                                                if ((p0 <= p0)) {
                                                                                                    p9 = p8;
                                                                                                    p0 = p10;
                                                                                                } else {
                                                                                                    p5 = p10;
                                                                                                }
                                                                                            } else {
                                                                                                p1 = p7;
                                                                                            }
                                                                                            if ((20 == -79)) {
                                                                                                p11 = 96;
                                                                                                p4 = p11;
                                                                                            } else {
                                                                                                p2 = p10;
                                                                                                p5 = 73;
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                    p8 = 83;
                                                                                }
                                                                            } else {
                                                                                p8 = p7;
                                                                            }
                                                                        }
                                                                        p2 = -80;
                                                                    }
                                                                    p0 = p1;
                                                                } else {
                                                                    p3 = p8;
                                                                    if ((p5 <= i97)) {
                                                                        p10 = p1;
                                                                    } else {
                                                                        p8 = 53;
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    } else {
                                                        p9 = 27;
                                                    }
                                                } else {
                                                    p1 = p5;
                                                }
                                                if ((p10 == -42)) {
                                                    p3 = p8;
                                                    if ((p0 > -51)) {
                                                        p2 = 24;
                                                        p1 = p0;
                                                    } else {
                                                        if ((p1 >= p3)) {
                                                            p0 = p3;
                                                            p7 = p11;
                                                        } else {
                                                            p7 = p7;
                                                            p2 = p9;
                                                        }
                                                        p6 = p9;
                                                    }
                                                } else {
                                                    p8 = p9;
                                                }
                                            } else {
                                                p11 = p8;
                                            }
                                        }
                                        if ((p8 >= p9)) {
                                            p7 = p4;
                                        } else {
                                            p11 = p5;
                                        }
                                    }
                                    p7 = p11;
                                }
                            } else {
                                p1 = -94;
                            }
                        } else {
                            p0 = p6;
                        }
                        if ((p2 >= p1)) {
                            p10 = 16;
                        } else {
                            for (int i44 = 0; i44 < 5; i44++) {
                                p5 = p9;
                                if ((-62 <= 33)) {
                                    p6 = -10;
                                } else {
                                    p0 = p6;
                                }
                            }
                        }
                    } else {
                        for (int i12 = 0; i12 < 6; i12++) {
                            p1 = p7;
                            p2 = 8;
                            p10 = p4;
                        }
                    }
                } else {
                    for (int i10 = 0; i10 < 3; i10++) {
                        p8 = p0;
                        p0 = p1;
                    }
                    p2 = p7;
                }
            } else {
                p10 = p5;
            }
        } else {
            if ((p5 == p2)) {
                p10 = p3;
            } else {
                for (int i70 = 0; i70 < 6; i70++) {
                    if ((p0 < p0)) {
                        p9 = p3;
                    } else {
                        p0 = p7;
                        p9 = p10;
                    }
                }
            }
        }
    } else {
        if ((p2 != p7)) {
            for (int i70 = 0; i70 < 4; i70++) {
                p2 = 25;
                p6 = 66;
                p2 = p10;
            }
        } else {
            if ((-4 == p0)) {
                p5 = -23;
            } else {
                p8 = p3;
                p2 = 40;
            }
        }
    }
    return p1;
}

int f1(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10) {
    p5 = 96;
    p1 = -40;
    p10 = p0;
    return (((p2 & 1023) | 819) - ((p6 & 1023) | 933));
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 29;
    int v1 = -31;
    int v2 = -18;
    int v3 = 1;
    int v4 = -18;
    int v5 = -22;
    int v6 = 33;
    int v7 = 11;
    int v8 = -23;
    int v9 = -1;
    double d0 = -6.0;
    double d1 = 10.0;
    double d2 = -27.0;
    double d3 = -11.0;
    double d4 = -8.0;
    double d5 = 7.0;
    arr[(93) & 7] = v1;
    v2 = f1((v1 / 3), ((v0 & 1023) & 63), ((v6 & 255) >> 0), -41, v9, ((v4 & 255) >> 1), (28 / 16), v9, v9, (v0 + 68), ((v6 & 1023) | 937));
    v1 = f0((v7 / 11), v1, ((65 & 1023) & 293), v9, (-26 + v8), (v1 - v1), (v1 * 13), ((v2 & 1023) & 688), ((v1 & 1023) | 912), (v7 + v7), ((38 & 1023) | 93), ((100 & 1023) ^ 687));
    d0 = (d0 + (26.0 * d3));
    d1 = (d1 + (16.0 + d3));
    d2 = (d2 + (d3 * d1));
    d3 = (d3 + (16.0 * d2));
    d4 = (d4 + (v9 & 63));
    d5 = (d5 + (v4 & 63));
    if ((73 >= v6)) {
        for (int i87 = 0; i87 < 4; i87++) {
            v0 = (i87 % -3);
            v2 = (79 + v4);
            v0 = (-52 % 11);
        }
        v3 = (((-95 & 1023) & 400) * (-21 / 2));
    } else {
        v3 = (79 * 73);
        v8 = arr[((99 + 7)) & 7];
    }
    v7 = f1(v9, (v4 / 11), (v2 - v1), (v1 / 8), (-7 - -78), v5, (-47 * v5), (-52 - v1), ((v2 & 1023) & 272), ((v1 & 255) >> 2), -29);
    d0 = (d0 + ((63 + -99) & 63));
    d1 = (d1 + d0);
    d2 = (d2 + (d2 + d5));
    d3 = (d3 + (d1 - d3));
    d4 = (d4 + ((-42 % 4) & 63));
    d5 = (d5 + (-31.0 * d0));
    v1 = (((v5 & 1023) & 163) % 16);
    v8 = f0(v3, ((v6 & 255) >> 0), ((v2 & 1023) | 75), ((v7 & 255) >> 4), ((v8 & 1023) | 917), ((v8 & 255) << 0), ((76 & 1023) | 269), v9, ((99 & 1023) ^ 530), (v8 + v7), (v5 / 4), ((v5 & 1023) ^ 388));
    v8 = f0((v6 % 4), ((v0 & 1023) | 194), -61, v8, (v5 / 16), ((90 & 255) << 0), (v7 * 21), v8, (61 + v5), -43, (-12 * v5), ((v1 & 1023) ^ 368));
    d0 = (d0 + (d3 + d5));
    d1 = (d1 + -14.0);
    d2 = (d2 + d5);
    d3 = (d3 + -10.0);
    d4 = (d4 + (d5 + d5));
    d5 = (d5 + d1);
    v8 = 87;
    v8 = f1(34, (90 % 16), ((v0 & 255) << 0), ((v4 & 1023) & 902), ((v4 & 1023) & 813), v6, ((v4 & 1023) & 428), (v6 * v6), 7, (-13 - 83), ((v2 & 255) << 2));
    d0 = (d0 + (d3 * 13.0));
    d1 = (d1 + -23.0);
    d2 = (d2 + (d5 + d0));
    d3 = (d3 + d2);
    d4 = (d4 + -36.0);
    d5 = (d5 + (d3 + d0));
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != 93150.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
