// EXIT: 0
// OUTPUT: 1244
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9) {
    p5 = (((p0 & 255) << 3) / 8);
    p1 = -57;
    return (((59 & 1023) ^ 993) - ((p1 & 1023) ^ 580));
}

int f1(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, int p10, int p11) {
    for (int i18 = 0; i18 < 2; i18++) {
        p3 = (p10 % 2);
        p2 = 0;
    }
    if (((-35 * p11) < p5)) {
        p6 = (p3 + p7);
        for (int i36 = 0; i36 < 2; i36++) {
            p11 = p9;
            p9 = p2;
        }
    } else {
        if ((-28 != 52)) {
            p7 = p10;
            p6 = p9;
        } else {
            for (int i42 = 0; i42 < 5; i42++) {
                if ((p1 >= p4)) {
                    if ((i42 <= i42)) {
                        p4 = p2;
                        if ((-19 > p9)) {
                            if ((i42 <= p10)) {
                                p4 = 7;
                            } else {
                                p9 = p11;
                            }
                            if ((p5 > p10)) {
                                p9 = p0;
                            } else {
                                if ((p6 != -96)) {
                                    p2 = p2;
                                } else {
                                    p7 = p11;
                                    p4 = p10;
                                }
                                p11 = p1;
                            }
                        } else {
                            if ((p5 <= i42)) {
                                if ((p7 > p11)) {
                                    p4 = p4;
                                    p6 = p9;
                                } else {
                                    if ((i42 < -77)) {
                                        p9 = -83;
                                    } else {
                                        p11 = p4;
                                    }
                                    p11 = 29;
                                }
                                p9 = p1;
                            } else {
                                p0 = -51;
                                if ((p8 == 13)) {
                                    if ((p0 >= p1)) {
                                        p2 = p3;
                                    } else {
                                        p8 = p4;
                                        if ((76 >= p2)) {
                                            p8 = 4;
                                            p2 = 40;
                                        } else {
                                            p1 = 8;
                                        }
                                    }
                                    p11 = 5;
                                } else {
                                    if ((p9 < 88)) {
                                        p9 = p4;
                                    } else {
                                        p4 = p0;
                                        p10 = 52;
                                    }
                                    p2 = p6;
                                }
                            }
                        }
                    } else {
                        p4 = p6;
                        p5 = p3;
                    }
                    p7 = p6;
                } else {
                    p4 = p6;
                    p9 = p1;
                }
                p6 = 1;
            }
            p3 = p8;
        }
    }
    return ((8 & 255) << 2);
}

int f2(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {
    p2 = p3;
    if (((p0 / 4) > p3)) {
        p5 = p1;
        p0 = (p5 + p3);
    } else {
        p1 = p1;
        if ((55 > p2)) {
            for (int i28 = 0; i28 < 2; i28++) {
                p0 = -98;
                if ((p5 <= p4)) {
                    p3 = p2;
                } else {
                    p5 = p2;
                }
            }
        } else {
            p1 = p3;
        }
    }
    return ((((-25 & 1023) | 457) & 1023) & 595);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 6;
    int v1 = 47;
    int v2 = -11;
    int v3 = -30;
    int v4 = 11;
    int v5 = 45;
    int v6 = 28;
    int v7 = 27;
    int v8 = -28;
    int v9 = 46;
    double d0 = 23.0;
    double d1 = 24.0;
    double d2 = 26.0;
    double d3 = -12.0;
    double d4 = -14.0;
    double d5 = 12.0;
    for (int i23 = 0; i23 < 6; i23++) {
        if ((((i23 & 1023) ^ 750) >= ((v2 & 1023) | 84))) {
            v4 = v1;
        } else {
            v9 = (v6 - v8);
            if ((v7 == v7)) {
                v2 = 15;
                arr[((v6 / 8)) & 7] = v3;
            } else {
                v9 = v2;
                v4 = v3;
            }
        }
    }
    v6 = ((12 & 1023) ^ 141);
    v5 = f1((-100 % 3), ((27 & 255) << 0), -51, ((v7 & 1023) | 14), v4, ((v5 & 255) << 4), ((v4 & 1023) & 176), v9, ((v9 & 1023) & 915), ((v0 & 1023) & 36), (77 + v9), (v7 / 16));
    d0 = (d0 + (d0 + d0));
    d1 = (d1 + ((97 - v6) & 63));
    d2 = (d2 + d4);
    d3 = (d3 + d5);
    d4 = (d4 + d3);
    d5 = (d5 + 11.0);
    v6 = (((v6 + v9) * -16) * (v0 % 4));
    if ((v1 != v8)) {
        if ((0 == ((7 & 255) << 4))) {
            for (int i22 = 0; i22 < 3; i22++) {
                v1 = 5;
            }
            arr[(v3) & 7] = ((58 & 255) >> 2);
        } else {
            v4 = arr[(32) & 7];
        }
    } else {
        v7 = ((((v3 & 1023) | 239) & 1023) ^ 896);
    }
    v8 = f0((v4 * -36), -69, ((v3 & 1023) | 1023), (v3 % 11), (v7 + v3), v6, v3, ((44 & 255) << 3), ((v3 & 255) >> 0), ((v0 & 1023) | 446));
    v0 = f2((v2 % 16), ((v7 & 255) >> 2), (v3 % 2), ((v6 & 1023) ^ 408), ((v2 & 1023) | 940), v4, ((23 & 255) << 1), v3);
    d0 = (d0 + (d1 + d1));
    d1 = (d1 + (d1 - d1));
    d2 = (d2 + (d0 * d1));
    d3 = (d3 + (d1 + d5));
    d4 = (d4 + -33.0);
    d5 = (d5 + d5);
    for (int i92 = 0; i92 < 3; i92++) {
        v8 = (((v3 & 255) >> 3) % -3);
        v9 = v7;
        v6 = arr[(((51 & 1023) & 52)) & 7];
    }
    v2 = f2(((v2 & 1023) & 430), (v2 / 16), ((92 & 1023) ^ 726), 59, v5, ((v2 & 255) << 2), v0, (v1 / 4));
    d0 = (d0 + (d5 - d3));
    d1 = (d1 + (-28.0 + d5));
    d2 = (d2 + d4);
    d3 = (d3 + (-29.0 + d1));
    d4 = (d4 + (d3 * d3));
    d5 = (d5 + (d2 - -24.0));
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != 35947.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
