// EXIT: 0
// OUTPUT: 1930
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(double p0, int p1, int p2, int p3, double p4, double p5, double p6) {
    p1 = (((p1 - p2) & 1023) & 958);
    for (int i32 = 0; i32 < 2; i32++) {
        if ((p3 < -60)) {
            if ((i32 == p1)) {
                if ((p3 >= 97)) {
                    p1 = p2;
                    if ((i32 > i32)) {
                        p3 = i32;
                        p3 = -5;
                    } else {
                        p3 = p1;
                    }
                } else {
                    if ((p3 < p1)) {
                        p1 = p2;
                    } else {
                        p2 = p3;
                    }
                    p2 = -28;
                }
                p3 = p3;
            } else {
                p2 = 20;
            }
            p2 = p3;
        } else {
            if ((43 >= p3)) {
                if ((p1 >= p1)) {
                    if ((p2 >= p3)) {
                        p2 = -62;
                    } else {
                        p3 = p3;
                        p2 = i32;
                    }
                } else {
                    p1 = i32;
                }
            } else {
                p3 = 82;
                p3 = p2;
            }
            if ((i32 >= p2)) {
                p2 = p3;
            } else {
                p1 = p3;
            }
        }
        p1 = (p2 - 90);
    }
    return ((p2 & 1023) | 345);
}

double f1(double p0, double p1, int p2, int p3, int p4, double p5, double p6, double p7) {
    if ((((p2 & 1023) & 590) < ((p2 & 255) >> 2))) {
        for (int i41 = 0; i41 < 5; i41++) {
            p4 = -30;
            p3 = -43;
            p4 = i41;
        }
    } else {
        p4 = ((15 & 1023) & 867);
    }
    for (int i83 = 0; i83 < 6; i83++) {
        p3 = (54 / 2);
    }
    p3 = ((16 / -6) % 11);
    return p1;
}

int f2(double p0, int p1, int p2, double p3, int p4, double p5, int p6, int p7, int p8) {
    for (int i37 = 0; i37 < 3; i37++) {
        if ((i37 <= p4)) {
            p1 = 78;
        } else {
            p1 = p2;
        }
        p4 = (p7 + p6);
        p1 = (p1 / 2);
    }
    p7 = p4;
    return p1;
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = -38;
    int v1 = -19;
    int v2 = 33;
    int v3 = 39;
    int v4 = -29;
    int v5 = 8;
    int v6 = 46;
    int v7 = -41;
    int v8 = -1;
    int v9 = -37;
    double d0 = -26.0;
    double d1 = -1.0;
    double d2 = 19.0;
    double d3 = -10.0;
    double d4 = -25.0;
    double d5 = 14.0;
    v9 = (((((v7 + v3) & 1023) & 158) & 255) << 2);
    v5 = v0;
    v2 = f2((d5 - d3), ((v3 & 255) << 1), (62 + 76), d3, v5, (((v3 & 1023) ^ 47) & 63), (v9 * v7), (v7 + v6), v6);
    d0 = (d0 + (d1 * d0));
    d1 = (d1 + ((v9 % 16) & 63));
    d2 = (d2 + -5.0);
    d3 = (d3 + d1);
    d4 = (d4 + d3);
    d5 = (d5 + d3);
    v0 = (v1 % 11);
    v6 = ((((v7 & 255) >> 2) / 2) * v2);
    v9 = ((v4 & 255) >> 3);
    v4 = f2(d1, (v6 * v0), (v9 + v4), (-34.0 - d3), ((v7 & 255) << 2), (v7 & 63), ((-98 & 255) << 4), v8, ((v2 & 255) << 0));
    v8 = f2((d4 * -30.0), (74 - v3), ((34 & 1023) & 883), (d0 * d2), (v8 + v5), (18.0 + -15.0), (v3 - -99), v4, (v7 * v1));
    d0 = (d0 + (d1 + 9.0));
    d1 = (d1 + (38.0 - -27.0));
    d2 = (d2 + (d2 + -8.0));
    d3 = (d3 + (d5 * d4));
    d4 = (d4 + (d5 - d5));
    d5 = (d5 + (d2 + 29.0));
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != -171.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
