// EXIT: 0
// OUTPUT: 3260
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(int p0, int p1, int p2, int p3, double p4, int p5, int p6, double p7, int p8, int p9, int p10) {
    for (int i38 = 0; i38 < 4; i38++) {
        if ((p0 == i38)) {
            p1 = p1;
        } else {
            p3 = 87;
            p3 = p9;
        }
        p8 = (p5 + p1);
        p5 = p2;
    }
    if ((24 != ((p3 & 255) << 0))) {
        p9 = p6;
    } else {
        for (int i13 = 0; i13 < 4; i13++) {
            p5 = p6;
            p3 = 28;
        }
    }
    return (((p3 & 255) >> 2) + p0);
}

double f1(double p0, int p1, double p2, int p3, double p4, int p5, int p6, double p7, int p8, int p9, double p10, double p11) {
    if ((((58 & 1023) | 650) <= ((68 & 255) << 0))) {
        if ((100 >= p9)) {
            for (int i7 = 0; i7 < 4; i7++) {
                p3 = p5;
                p6 = p9;
                p9 = p1;
            }
        } else {
            p9 = p3;
            p3 = p6;
        }
        p1 = ((-80 & 255) << 1);
    } else {
        p5 = 20;
    }
    if ((((p3 & 1023) ^ 931) <= (p9 / 7))) {
        p5 = (p5 % 4);
        if ((18 < p8)) {
            for (int i62 = 0; i62 < 3; i62++) {
                p6 = p6;
            }
            p8 = p5;
        } else {
            p9 = p5;
            p6 = p8;
        }
    } else {
        p5 = ((p9 & 1023) ^ 90);
        p5 = ((p5 & 1023) ^ 156);
    }
    return (20.0 * (p0 * p4));
}

int f2(int p0, int p1, int p2, int p3, double p4, double p5, double p6, int p7, double p8, double p9, int p10) {
    if ((((57 & 255) >> 4) <= ((p3 & 255) >> 2))) {
        p2 = (p3 * p7);
        p0 = (p3 + p2);
    } else {
        for (int i93 = 0; i93 < 1; i93++) {
            p0 = p7;
            p7 = p10;
            if ((p0 >= p1)) {
                p0 = i93;
            } else {
                if ((-10 == p1)) {
                    if ((p7 <= p1)) {
                        p10 = p10;
                        p7 = p10;
                    } else {
                        p1 = p3;
                    }
                } else {
                    p0 = p3;
                    if ((p3 > p7)) {
                        p10 = p3;
                        p10 = p10;
                    } else {
                        if ((92 <= i93)) {
                            if ((67 < p2)) {
                                if ((p3 <= 27)) {
                                    if ((p0 <= p7)) {
                                        p0 = p1;
                                    } else {
                                        p3 = i93;
                                    }
                                } else {
                                    if ((-88 >= p7)) {
                                        p1 = p2;
                                    } else {
                                        p0 = p1;
                                        p10 = p2;
                                    }
                                }
                                if ((26 != p3)) {
                                    if ((14 <= 77)) {
                                        p2 = p10;
                                        if ((p10 >= p7)) {
                                            p10 = -45;
                                            p2 = p1;
                                        } else {
                                            p0 = 11;
                                        }
                                    } else {
                                        p3 = 53;
                                    }
                                } else {
                                    p10 = p3;
                                }
                            } else {
                                p2 = p7;
                                p7 = p1;
                            }
                        } else {
                            p7 = p7;
                            p2 = p7;
                        }
                    }
                }
                p0 = p0;
            }
        }
        if ((p0 >= p2)) {
            if ((p10 > p3)) {
                p1 = p10;
                p10 = p7;
            } else {
                if ((-58 <= p7)) {
                    p2 = 87;
                    if ((p0 < p1)) {
                        for (int i91 = 0; i91 < 1; i91++) {
                            if ((-39 < p3)) {
                                if ((p2 < p10)) {
                                    if ((p2 != 65)) {
                                        p1 = 96;
                                    } else {
                                        p1 = -2;
                                    }
                                    p7 = 17;
                                } else {
                                    p10 = p3;
                                    p7 = p10;
                                }
                            } else {
                                p1 = p2;
                            }
                            if ((-4 > p1)) {
                                p10 = p1;
                            } else {
                                p10 = 41;
                                if ((i91 != p2)) {
                                    if ((p3 > p0)) {
                                        p3 = p1;
                                    } else {
                                        p0 = p7;
                                        p10 = p10;
                                    }
                                } else {
                                    if ((p3 <= p2)) {
                                        p1 = 47;
                                    } else {
                                        p1 = 38;
                                        if ((p0 != p3)) {
                                            p2 = 93;
                                            p1 = p1;
                                        } else {
                                            if ((p1 <= p0)) {
                                                if ((p0 <= -46)) {
                                                    p3 = 81;
                                                } else {
                                                    p2 = p7;
                                                }
                                            } else {
                                                if ((88 > 22)) {
                                                    p0 = p1;
                                                    p3 = p10;
                                                } else {
                                                    p1 = p3;
                                                }
                                            }
                                            p0 = 28;
                                        }
                                    }
                                    p3 = p2;
                                }
                            }
                            p1 = p10;
                        }
                        p7 = -69;
                    } else {
                        p3 = p2;
                    }
                } else {
                    p10 = -41;
                    p0 = p3;
                }
                for (int i7 = 0; i7 < 6; i7++) {
                    p1 = -43;
                }
            }
            if ((4 < 9)) {
                if ((p7 == p3)) {
                    p1 = p10;
                } else {
                    p0 = p0;
                    p2 = p0;
                }
            } else {
                for (int i69 = 0; i69 < 6; i69++) {
                    p10 = i69;
                    if ((6 <= -78)) {
                        p3 = p2;
                    } else {
                        p2 = p3;
                    }
                    p0 = p2;
                }
            }
        } else {
            p10 = 49;
            if ((p1 == 27)) {
                for (int i43 = 0; i43 < 4; i43++) {
                    if ((p2 < p1)) {
                        p7 = p1;
                        p1 = i43;
                    } else {
                        p0 = p7;
                    }
                    if ((p3 < p1)) {
                        p3 = i43;
                        p10 = 78;
                    } else {
                        p3 = p7;
                    }
                    p10 = p10;
                }
            } else {
                p10 = p0;
                p7 = p10;
            }
        }
    }
    for (int i92 = 0; i92 < 3; i92++) {
        if ((p7 <= -84)) {
            if ((p10 > p7)) {
                if ((22 >= p2)) {
                    p7 = p1;
                } else {
                    p10 = p1;
                    p1 = p1;
                }
                if ((p0 != 73)) {
                    p3 = p3;
                    p3 = p2;
                } else {
                    p10 = p7;
                    p1 = p1;
                }
            } else {
                if ((p3 <= p3)) {
                    p7 = p2;
                } else {
                    p7 = p0;
                    p10 = 54;
                }
                if ((61 == p2)) {
                    p0 = i92;
                } else {
                    p7 = p0;
                    if ((-22 <= p3)) {
                        if ((p3 != 74)) {
                            p2 = 72;
                        } else {
                            if ((p3 == p1)) {
                                p2 = p0;
                            } else {
                                if ((i92 != -85)) {
                                    if ((p10 < 56)) {
                                        p0 = 80;
                                        p1 = i92;
                                    } else {
                                        p1 = 39;
                                    }
                                    p3 = -44;
                                } else {
                                    p7 = -12;
                                }
                                p10 = p3;
                            }
                            p3 = 10;
                        }
                        p1 = p7;
                    } else {
                        p2 = i92;
                        p7 = p0;
                    }
                }
            }
            p3 = 70;
        } else {
            p10 = p2;
        }
    }
    return ((p10 & 255) << 3);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 43;
    int v1 = -18;
    int v2 = -43;
    int v3 = 9;
    int v4 = 28;
    int v5 = -26;
    int v6 = 12;
    int v7 = 4;
    int v8 = 36;
    int v9 = -11;
    int v10 = 0;
    int v11 = 44;
    int v12 = 41;
    int v13 = -43;
    int v14 = 16;
    int v15 = -1;
    double d0 = 5.0;
    double d1 = -11.0;
    double d2 = 10.0;
    double d3 = -22.0;
    double d4 = 4.0;
    double d5 = 26.0;
    double d6 = 7.0;
    double d7 = 11.0;
    double d8 = 3.0;
    double d9 = -18.0;
    double d10 = -8.0;
    double d11 = -5.0;
    v9 = -72;
    v6 = ((v1 & 1023) ^ 684);
    arr[(37) & 7] = -48;
    v3 = f0(((-38 & 1023) | 875), ((v11 & 255) >> 4), v14, ((v15 & 1023) | 663), d5, ((v1 & 1023) & 829), ((v9 & 1023) ^ 733), (d7 - 25.0), ((v1 & 1023) | 169), 79, v6);
    v1 = f0(((v9 & 255) << 4), ((v13 & 1023) ^ 478), ((-76 & 1023) ^ 123), (v1 - 26), (d6 * d0), v7, ((v11 & 1023) | 573), d5, ((-76 & 1023) & 631), (v7 % 16), (v8 - v4));
    d0 = (d0 + -3.0);
    d1 = (d1 + (d8 + d10));
    d2 = (d2 + (d6 - d10));
    d3 = (d3 + (d6 * d11));
    d4 = (d4 + d7);
    d5 = (d5 + d6);
    d6 = (d6 + d2);
    d7 = (d7 + (d10 - -28.0));
    d8 = (d8 + (d11 * -32.0));
    d9 = (d9 + (d0 - d0));
    d10 = (d10 + (-21.0 - d2));
    d11 = (d11 + (d4 + d4));
    for (int i83 = 0; i83 < 2; i83++) {
        v11 = arr[(((v2 & 255) >> 3)) & 7];
        if ((-64 < i83)) {
            if ((v14 > -74)) {
                if ((v3 < v1)) {
                    v5 = v12;
                    v8 = v3;
                } else {
                    v11 = -81;
                }
                v3 = v11;
            } else {
                v14 = i83;
                arr[((-72 + v8)) & 7] = v4;
            }
        } else {
            v14 = ((v1 & 1023) | 224);
        }
    }
    v7 = arr[(((v8 - v13) + ((6 & 1023) ^ 427))) & 7];
    d5 = f1((8.0 + d3), v5, (d4 * d1), (v12 / 4), (d11 + 24.0), 84, ((93 & 1023) & 167), (7.0 - d0), (-47 - v12), v10, (d0 + d11), d1);
    d0 = (d0 + (d9 * -5.0));
    d1 = (d1 + d6);
    d2 = (d2 + (d10 + d2));
    d3 = (d3 + (-25.0 - d7));
    d4 = (d4 + (d4 - d5));
    d5 = (d5 + (d9 * d6));
    d6 = (d6 + (d11 * d2));
    d7 = (d7 + (((v15 & 255) >> 2) & 63));
    d8 = (d8 + (-39.0 - d5));
    d9 = (d9 + ((12 % 3) & 63));
    d10 = (d10 + (d0 - 20.0));
    d11 = (d11 + (d8 * -13.0));
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != -585144.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
