// EXIT: 0
// OUTPUT: 1911
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(int p0, int p1, double p2, double p3, int p4, double p5, int p6, int p7, int p8) {
    if ((p8 > (p1 - p8))) {
        for (int i94 = 0; i94 < 5; i94++) {
            if ((i94 < p7)) {
                p6 = 64;
                if ((p1 > p0)) {
                    p0 = p6;
                    p8 = p7;
                } else {
                    p6 = 2;
                }
            } else {
                p7 = p7;
            }
            if ((p4 <= p0)) {
                p7 = 17;
            } else {
                p7 = 91;
            }
        }
        p8 = (p7 - p8);
    } else {
        for (int i25 = 0; i25 < 1; i25++) {
            if ((28 >= p7)) {
                if ((p7 >= p8)) {
                    if ((p1 != 88)) {
                        if ((p0 <= p7)) {
                            p7 = p6;
                        } else {
                            p7 = p4;
                            if ((p7 > p0)) {
                                p0 = -36;
                                p0 = 92;
                            } else {
                                p8 = 35;
                                if ((i25 >= p7)) {
                                    p0 = p8;
                                    p6 = 48;
                                } else {
                                    p0 = p1;
                                }
                            }
                        }
                        p7 = 10;
                    } else {
                        if ((p0 <= p8)) {
                            p0 = 98;
                        } else {
                            if ((p6 <= p1)) {
                                p0 = 70;
                                p1 = p0;
                            } else {
                                p6 = 95;
                                if ((p8 != -77)) {
                                    p1 = p8;
                                } else {
                                    p0 = 12;
                                    p7 = p7;
                                }
                            }
                        }
                    }
                    p8 = p1;
                } else {
                    p0 = p7;
                }
                if ((-58 == p4)) {
                    if ((p7 == p6)) {
                        p0 = -18;
                        p4 = 53;
                    } else {
                        p0 = 29;
                        p7 = p6;
                    }
                    p4 = p8;
                } else {
                    p0 = i25;
                    p0 = p4;
                }
            } else {
                p8 = p8;
                p6 = -12;
            }
            p7 = p0;
            p6 = i25;
        }
        p0 = ((p8 & 1023) | 956);
    }
    return ((p7 + 84) + ((p0 & 1023) & 33));
}

double f1(int p0, int p1, int p2, double p3, double p4, double p5, int p6, int p7, double p8, int p9) {
    p0 = ((p1 % 5) + p1);
    if ((p0 <= p0)) {
        p9 = p6;
    } else {
        for (int i40 = 0; i40 < 3; i40++) {
            p6 = p7;
            if ((p7 <= p7)) {
                p1 = -6;
            } else {
                p2 = p2;
                p0 = p9;
            }
            p9 = p0;
        }
    }
    return (((p9 & 1023) & 896) & 63);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 9;
    int v1 = -35;
    int v2 = -16;
    int v3 = -15;
    int v4 = -16;
    int v5 = -40;
    int v6 = 27;
    int v7 = 4;
    int v8 = 35;
    int v9 = -42;
    int v10 = 10;
    int v11 = 7;
    int v12 = -5;
    int v13 = 27;
    int v14 = 47;
    int v15 = -28;
    double d0 = 22.0;
    double d1 = -2.0;
    double d2 = -30.0;
    double d3 = 2.0;
    double d4 = 4.0;
    double d5 = -14.0;
    double d6 = -17.0;
    double d7 = -4.0;
    double d8 = -11.0;
    double d9 = 11.0;
    double d10 = -24.0;
    double d11 = -29.0;
    if ((v12 == ((-33 & 1023) ^ 757))) {
        v1 = -22;
        v2 = ((((70 & 1023) & 193) & 1023) | 909);
    } else {
        arr[(((v2 & 1023) ^ 270)) & 7] = -83;
        if ((v12 > v2)) {
            v1 = ((-38 & 255) << 3);
        } else {
            v13 = arr[(v5) & 7];
            if ((-25 <= -72)) {
                v1 = v7;
                v11 = v4;
            } else {
                for (int i20 = 0; i20 < 4; i20++) {
                    v8 = v11;
                    if ((v3 >= v0)) {
                        arr[(((28 & 255) >> 3)) & 7] = v0;
                    } else {
                        v10 = 99;
                        v12 = v15;
                    }
                    v0 = v12;
                }
                v9 = -59;
            }
        }
    }
    v3 = f0((55 * 45), v9, d6, 39.0, -8, d7, (v10 / 7), (v2 + v10), ((v6 & 1023) & 728));
    d0 = (d0 + (6.0 - 4.0));
    d1 = (d1 + (d9 + d7));
    d2 = (d2 + (d7 - 22.0));
    d3 = (d3 + d4);
    d4 = (d4 + (39.0 * 31.0));
    d5 = (d5 + d2);
    d6 = (d6 + (((v1 & 255) << 3) & 63));
    d7 = (d7 + (d8 * d8));
    d8 = (d8 + (((v8 & 1023) | 742) & 63));
    d9 = (d9 + (d4 + d2));
    d10 = (d10 + (d7 * d1));
    d11 = (d11 + d11);
    arr[(((v4 & 1023) ^ 224)) & 7] = v12;
    v8 = f0(v4, ((v5 & 1023) | 465), d1, d6, (v4 / 5), (d8 - d3), ((v1 & 255) << 3), v4, (v13 / 4));
    d0 = (d0 + d10);
    d1 = (d1 + d4);
    d2 = (d2 + d2);
    d3 = (d3 + d2);
    d4 = (d4 + (32.0 - d10));
    d5 = (d5 + (v4 & 63));
    d6 = (d6 + (24.0 * -8.0));
    d7 = (d7 + ((v12 * v5) & 63));
    d8 = (d8 + (-97 & 63));
    d9 = (d9 + (d0 + d8));
    d10 = (d10 + (((-7 & 255) >> 0) & 63));
    d11 = (d11 + d5);
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != 4572.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
