// EXIT: 0
// OUTPUT: -2051
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(int p0, int p1, double p2, double p3, int p4, int p5, int p6, int p7, double p8, int p9, double p10, int p11) {
    if ((p5 >= ((65 & 1023) & 790))) {
        if ((p4 > p5)) {
            if ((p0 != p5)) {
                p1 = p4;
                for (int i10 = 0; i10 < 6; i10++) {
                    p7 = -47;
                    p7 = i10;
                    p0 = -40;
                }
            } else {
                p1 = p1;
                p5 = -41;
            }
            p11 = p6;
        } else {
            if ((p1 == p5)) {
                if ((7 > p5)) {
                    p4 = 18;
                } else {
                    p1 = -54;
                }
                for (int i22 = 0; i22 < 5; i22++) {
                    p7 = -23;
                }
            } else {
                if ((p11 > p9)) {
                    if ((p5 <= p1)) {
                        if ((p5 == -57)) {
                            p9 = p7;
                        } else {
                            p9 = p4;
                            p11 = -10;
                        }
                        p1 = p1;
                    } else {
                        if ((p0 != p9)) {
                            p1 = p7;
                            for (int i9 = 0; i9 < 2; i9++) {
                                if ((p5 != p9)) {
                                    p4 = p7;
                                } else {
                                    p4 = p9;
                                }
                                if ((74 <= p11)) {
                                    p6 = p5;
                                } else {
                                    if ((p5 < p7)) {
                                        if ((0 > 47)) {
                                            p4 = -90;
                                            p5 = i9;
                                        } else {
                                            if ((53 < -47)) {
                                                if ((i9 >= -86)) {
                                                    p1 = p11;
                                                } else {
                                                    p5 = p7;
                                                }
                                            } else {
                                                p4 = p5;
                                                p11 = -21;
                                            }
                                            if ((p6 < i9)) {
                                                if ((p7 < p7)) {
                                                    if ((-60 < i9)) {
                                                        p11 = 65;
                                                    } else {
                                                        if ((-57 >= i9)) {
                                                            p11 = p9;
                                                            if ((i9 > 44)) {
                                                                if ((p11 != -93)) {
                                                                    p4 = 43;
                                                                    if ((p6 > p0)) {
                                                                        p1 = i9;
                                                                        if ((-60 <= 97)) {
                                                                            if ((p11 != p11)) {
                                                                                p0 = p5;
                                                                                p0 = p1;
                                                                            } else {
                                                                                p7 = p4;
                                                                                if ((i9 != 42)) {
                                                                                    p9 = p7;
                                                                                } else {
                                                                                    p5 = 70;
                                                                                }
                                                                            }
                                                                            if ((-38 == 17)) {
                                                                                if ((39 == 86)) {
                                                                                    p7 = p4;
                                                                                    if ((35 > 21)) {
                                                                                        p0 = -74;
                                                                                    } else {
                                                                                        p6 = p9;
                                                                                        if ((49 == p7)) {
                                                                                            p1 = p6;
                                                                                            p9 = p5;
                                                                                        } else {
                                                                                            p4 = p1;
                                                                                        }
                                                                                    }
                                                                                } else {
                                                                                    p4 = p6;
                                                                                }
                                                                            } else {
                                                                                p6 = p11;
                                                                                p1 = p5;
                                                                            }
                                                                        } else {
                                                                            p7 = p4;
                                                                        }
                                                                    } else {
                                                                        if ((p9 < p11)) {
                                                                            p9 = p0;
                                                                            p1 = p4;
                                                                        } else {
                                                                            if ((p1 == p6)) {
                                                                                p7 = p9;
                                                                                p7 = p6;
                                                                            } else {
                                                                                p0 = p0;
                                                                            }
                                                                        }
                                                                    }
                                                                } else {
                                                                    p5 = p7;
                                                                    p6 = p0;
                                                                }
                                                                p6 = p1;
                                                            } else {
                                                                p1 = p0;
                                                                p6 = p1;
                                                            }
                                                        } else {
                                                            p0 = -75;
                                                        }
                                                    }
                                                } else {
                                                    p1 = i9;
                                                    if ((-89 >= -17)) {
                                                        p4 = 11;
                                                    } else {
                                                        p9 = p7;
                                                        if ((p4 > p0)) {
                                                            if ((p6 >= p7)) {
                                                                p9 = p0;
                                                            } else {
                                                                p5 = -96;
                                                            }
                                                        } else {
                                                            if ((p9 >= -10)) {
                                                                p6 = p9;
                                                                p9 = p6;
                                                            } else {
                                                                p5 = p9;
                                                            }
                                                            p11 = p6;
                                                        }
                                                    }
                                                }
                                            } else {
                                                p9 = p5;
                                                p1 = -9;
                                            }
                                        }
                                        p7 = -2;
                                    } else {
                                        p6 = p9;
                                    }
                                }
                            }
                        } else {
                            p4 = p0;
                            if ((p1 >= -11)) {
                                p11 = p0;
                                p5 = -32;
                            } else {
                                if ((43 < p0)) {
                                    p11 = p0;
                                    if ((35 == 26)) {
                                        p6 = -50;
                                        p9 = p6;
                                    } else {
                                        p9 = p1;
                                    }
                                } else {
                                    p0 = p4;
                                    p5 = p1;
                                }
                                p6 = p11;
                            }
                        }
                    }
                    for (int i56 = 0; i56 < 1; i56++) {
                        if ((p5 != p11)) {
                            p11 = p9;
                        } else {
                            p5 = -38;
                            p6 = p0;
                        }
                        if ((p5 > i56)) {
                            p4 = p6;
                            if ((34 >= p1)) {
                                p5 = p11;
                                p9 = p4;
                            } else {
                                p0 = p6;
                            }
                        } else {
                            p5 = p1;
                            p5 = p4;
                        }
                        p11 = p0;
                    }
                } else {
                    p9 = p5;
                    p5 = p7;
                }
                if ((2 != p4)) {
                    p6 = p7;
                    if ((p11 < p5)) {
                        if ((p9 < p9)) {
                            if ((p9 < p11)) {
                                p5 = p9;
                            } else {
                                p9 = -75;
                            }
                        } else {
                            if ((83 <= 14)) {
                                p9 = -47;
                                for (int i77 = 0; i77 < 3; i77++) {
                                    p11 = p9;
                                    p5 = -63;
                                }
                            } else {
                                p5 = p5;
                                for (int i76 = 0; i76 < 3; i76++) {
                                    p1 = p11;
                                    p7 = p1;
                                    if ((p0 <= p9)) {
                                        p5 = p1;
                                    } else {
                                        if ((p4 > p11)) {
                                            if ((p0 == -11)) {
                                                if ((6 > p0)) {
                                                    p6 = p0;
                                                    if ((p0 < p7)) {
                                                        if ((p0 == i76)) {
                                                            if ((-32 != 41)) {
                                                                p4 = -23;
                                                                p6 = p6;
                                                            } else {
                                                                p0 = p7;
                                                                if ((p11 != -30)) {
                                                                    p1 = -74;
                                                                    p7 = p11;
                                                                } else {
                                                                    p1 = 55;
                                                                }
                                                            }
                                                        } else {
                                                            p0 = i76;
                                                        }
                                                        p0 = p1;
                                                    } else {
                                                        p11 = p11;
                                                        p11 = p9;
                                                    }
                                                } else {
                                                    p1 = p9;
                                                }
                                                if ((p0 >= 81)) {
                                                    if ((p6 > -39)) {
                                                        p0 = -66;
                                                    } else {
                                                        p6 = p1;
                                                    }
                                                    p1 = p6;
                                                } else {
                                                    if ((-53 < p5)) {
                                                        if ((-38 > p5)) {
                                                            if ((p4 < p6)) {
                                                                p4 = p11;
                                                                if ((p6 == p4)) {
                                                                    p1 = p4;
                                                                } else {
                                                                    p7 = p5;
                                                                }
                                                            } else {
                                                                if ((p0 > -82)) {
                                                                    p6 = p9;
                                                                } else {
                                                                    p11 = p5;
                                                                }
                                                            }
                                                            p0 = p5;
                                                        } else {
                                                            p6 = 78;
                                                        }
                                                        p9 = p9;
                                                    } else {
                                                        if ((p1 < p1)) {
                                                            if ((67 > -100)) {
                                                                p0 = 100;
                                                            } else {
                                                                p1 = 30;
                                                            }
                                                            p1 = p0;
                                                        } else {
                                                            p5 = p4;
                                                            p5 = p7;
                                                        }
                                                    }
                                                    p0 = p11;
                                                }
                                            } else {
                                                p6 = p9;
                                            }
                                            p4 = p0;
                                        } else {
                                            p0 = 24;
                                            if ((p5 >= -30)) {
                                                p0 = p5;
                                                p11 = 75;
                                            } else {
                                                p1 = p0;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    } else {
                        p6 = -29;
                        p5 = p9;
                    }
                } else {
                    if ((p6 == p4)) {
                        if ((p7 < p5)) {
                            p5 = p1;
                        } else {
                            if ((p9 < p0)) {
                                p1 = p5;
                                p5 = -12;
                            } else {
                                p11 = p11;
                                p11 = p4;
                            }
                            for (int i12 = 0; i12 < 4; i12++) {
                                p5 = -48;
                            }
                        }
                    } else {
                        p1 = p4;
                    }
                    p7 = p4;
                }
            }
            p1 = p5;
        }
        p6 = (-40 * p6);
    } else {
        p1 = ((-77 & 1023) | 60);
        p5 = ((p1 & 255) >> 1);
    }
    for (int i80 = 0; i80 < 4; i80++) {
        if ((7 == p6)) {
            p1 = p11;
        } else {
            p9 = p7;
        }
        p11 = ((p5 & 1023) & 905);
        p4 = ((p4 & 1023) | 334);
    }
    if (((p9 + p1) >= (p7 + -44))) {
        if ((p9 > p7)) {
            for (int i5 = 0; i5 < 3; i5++) {
                if ((1 < p0)) {
                    p1 = p1;
                    p11 = p4;
                } else {
                    if ((p0 > p5)) {
                        if ((p7 >= p4)) {
                            if ((p5 > p1)) {
                                if ((p0 != p0)) {
                                    p7 = -64;
                                    p1 = 38;
                                } else {
                                    if ((p5 < p9)) {
                                        if ((p1 != p6)) {
                                            p0 = i5;
                                        } else {
                                            p0 = p4;
                                        }
                                        p1 = p1;
                                    } else {
                                        if ((p11 >= p9)) {
                                            p6 = p6;
                                            if ((p0 <= p7)) {
                                                if ((p9 <= p7)) {
                                                    p11 = p1;
                                                    p4 = p9;
                                                } else {
                                                    p4 = p0;
                                                }
                                                p6 = 18;
                                            } else {
                                                p9 = p0;
                                            }
                                        } else {
                                            if ((55 >= p7)) {
                                                p7 = p7;
                                                p1 = p0;
                                            } else {
                                                p0 = 99;
                                            }
                                        }
                                        p1 = p5;
                                    }
                                    p11 = -66;
                                }
                                if ((p7 < 30)) {
                                    p9 = p1;
                                } else {
                                    p11 = 3;
                                    p7 = p6;
                                }
                            } else {
                                p4 = p6;
                            }
                        } else {
                            p6 = p4;
                        }
                        p6 = p4;
                    } else {
                        p4 = i5;
                    }
                }
                p6 = p4;
            }
        } else {
            for (int i6 = 0; i6 < 3; i6++) {
                p0 = -87;
                if ((p5 > -1)) {
                    p0 = p0;
                } else {
                    if ((p9 != p7)) {
                        p7 = -99;
                        p0 = p6;
                    } else {
                        p6 = p11;
                        p0 = p7;
                    }
                }
                if ((p1 >= i6)) {
                    p11 = p0;
                } else {
                    p11 = p5;
                }
            }
        }
    } else {
        if ((p7 != p11)) {
            p11 = -48;
            for (int i86 = 0; i86 < 1; i86++) {
                p0 = p11;
                p4 = p7;
                if ((i86 <= i86)) {
                    p11 = i86;
                } else {
                    p1 = 63;
                }
            }
        } else {
            p6 = p11;
        }
    }
    return ((p1 & 255) << 1);
}

double f1(double p0, int p1, int p2, double p3, double p4, double p5, int p6) {
    if ((-35 < p6)) {
        p1 = (p6 - p1);
        p6 = ((p1 & 255) >> 2);
    } else {
        for (int i18 = 0; i18 < 3; i18++) {
            p1 = p1;
        }
    }
    if ((((p6 & 1023) ^ 279) == p6)) {
        for (int i73 = 0; i73 < 2; i73++) {
            p2 = -34;
        }
        p6 = p6;
    } else {
        p1 = ((p1 & 255) >> 3);
        p6 = p6;
    }
    p6 = ((p2 - p1) + ((p6 & 255) << 0));
    return ((p1 * p2) & 63);
}

double f2(double p0, int p1, double p2, int p3, int p4, double p5, double p6, double p7) {
    p4 = (((p1 % 16) & 1023) ^ 186);
    p4 = p1;
    p3 = (27 + ((p4 & 255) << 4));
    return p2;
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 12;
    int v1 = -30;
    int v2 = -2;
    int v3 = 21;
    int v4 = -33;
    int v5 = 4;
    int v6 = -32;
    int v7 = 43;
    int v8 = -3;
    int v9 = -30;
    int v10 = -19;
    int v11 = 41;
    int v12 = -3;
    int v13 = -26;
    int v14 = -29;
    int v15 = -6;
    double d0 = -23.0;
    double d1 = 12.0;
    double d2 = 27.0;
    double d3 = 2.0;
    double d4 = -7.0;
    double d5 = 17.0;
    double d6 = 4.0;
    double d7 = 5.0;
    double d8 = 16.0;
    double d9 = 3.0;
    double d10 = 6.0;
    double d11 = -8.0;
    v7 = -39;
    arr[(((v5 & 255) >> 2)) & 7] = (((((v4 / -6) & 1023) | 541) & 1023) & 562);
    v9 = ((((28 & 255) << 4) & 255) << 4);
    d3 = f2((d0 - d8), ((v2 & 255) << 4), (d8 * -17.0), (-89 / 2), ((v12 & 255) >> 1), (d6 - 9.0), (-96 & 63), d3);
    d0 = f1((d7 - d6), -49, 29, (-19.0 * -6.0), (d8 - d1), d2, (v9 - v0));
    d0 = (d0 + d9);
    d1 = (d1 + (v5 & 63));
    d2 = (d2 + (d6 * d4));
    d3 = (d3 + (18.0 + d3));
    d4 = (d4 + d2);
    d5 = (d5 + d5);
    d6 = (d6 + ((v1 - -88) & 63));
    d7 = (d7 + (d1 - -14.0));
    d8 = (d8 + (d9 * d1));
    d9 = (d9 + (d4 + d9));
    d10 = (d10 + (d9 - 24.0));
    d11 = (d11 + d7);
    arr[((v6 % 2)) & 7] = (((((v6 % 16) & 255) >> 4) & 255) >> 3);
    v3 = f0(-52, (-50 % 4), -21.0, (d1 - 21.0), (v12 - v7), v2, -100, ((48 & 255) << 0), (d6 + d8), ((v6 & 1023) | 101), d6, v7);
    d0 = (d0 + (d0 * d4));
    d1 = (d1 + d10);
    d2 = (d2 + (d10 - d9));
    d3 = (d3 + 18.0);
    d4 = (d4 + d10);
    d5 = (d5 + (d3 - d7));
    d6 = (d6 + (-5.0 + d1));
    d7 = (d7 + (d4 * d0));
    d8 = (d8 + (d0 - d4));
    d9 = (d9 + (d1 * d4));
    d10 = (d10 + d6);
    d11 = (d11 + (d7 + d3));
    if ((((v0 * v5) % 11) == v1)) {
        v14 = (v2 * (-76 - v12));
        v5 = v4;
    } else {
        for (int i6 = 0; i6 < 6; i6++) {
            v9 = arr[(v4) & 7];
            if ((83 == -56)) {
                v1 = -84;
                if ((v14 != v15)) {
                    v3 = 36;
                    v5 = v6;
                } else {
                    v2 = 41;
                }
            } else {
                v4 = v1;
                v6 = 60;
            }
        }
    }
    d6 = f1(d6, (59 / 2), ((v0 & 1023) ^ 531), (d1 - d2), (d0 + 29.0), -3.0, v1);
    d2 = f1((d4 * -15.0), (v0 - v14), ((22 & 1023) ^ 460), ((v0 - v0) & 63), d10, d10, ((v12 & 255) << 0));
    d0 = (d0 + (d0 - 32.0));
    d1 = (d1 + d9);
    d2 = (d2 + (0.0 - d4));
    d3 = (d3 + (d1 * d0));
    d4 = (d4 + (-38.0 * d10));
    d5 = (d5 + d3);
    d6 = (d6 + (d0 * d6));
    d7 = (d7 + (d5 * 1.0));
    d8 = (d8 + (d2 + d3));
    d9 = (d9 + ((v6 + -26) & 63));
    d10 = (d10 + (d8 * d9));
    d11 = (d11 + d2);
    for (int i25 = 0; i25 < 3; i25++) {
        arr[((62 + v5)) & 7] = (((v14 / 11) & 255) >> 4);
        v7 = ((((v5 & 1023) ^ 431) & 1023) ^ 148);
        v7 = (((82 & 1023) | 476) % -6);
    }
    if ((((-1 / 2) - (v11 % 11)) != ((88 & 1023) | 508))) {
        v1 = v12;
    } else {
        v8 = ((21 & 255) >> 1);
    }
    for (int i87 = 0; i87 < 6; i87++) {
        v3 = arr[((v9 % 4)) & 7];
        v6 = (36 * (-81 + v2));
    }
    v10 = f0(((-47 & 255) << 2), (v5 + v12), ((v0 + v4) & 63), ((80 * v12) & 63), (v10 % 11), (v3 - 88), (v11 + v11), (v4 + v1), ((v10 % 16) & 63), ((-48 & 1023) | 667), (d5 + d7), (0 - v0));
    d0 = (d0 + d10);
    d1 = (d1 + (d8 - d7));
    d2 = (d2 + 18.0);
    d3 = (d3 + (-27.0 - 28.0));
    d4 = (d4 + (d1 - d9));
    d5 = (d5 + (-11.0 - d11));
    d6 = (d6 + d11);
    d7 = (d7 + ((v1 * -59) & 63));
    d8 = (d8 + (12.0 * d4));
    d9 = (d9 + (v12 & 63));
    d10 = (d10 + (((-98 & 1023) ^ 493) & 63));
    d11 = (d11 + d11);
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != -25204427.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
