// EXIT: 0
// OUTPUT: -818
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

double f0(double p0, double p1, double p2, int p3, double p4, int p5, double p6, int p7, double p8, int p9, double p10, double p11) {
    p3 = -31;
    return ((p6 * p6) * (7.0 - p2));
}

int f1(double p0, double p1, int p2, double p3, double p4, int p5, double p6, double p7, int p8, int p9) {
    for (int i89 = 0; i89 < 1; i89++) {
        p5 = ((p8 & 255) << 4);
    }
    if ((((-42 & 1023) | 534) < ((p2 & 1023) & 608))) {
        p8 = p5;
        p8 = 50;
    } else {
        for (int i42 = 0; i42 < 1; i42++) {
            p5 = p8;
            if ((p8 >= 69)) {
                if ((i42 >= p5)) {
                    if ((p9 >= 72)) {
                        p5 = i42;
                    } else {
                        p5 = 28;
                        if ((p9 == p2)) {
                            if ((p9 <= -22)) {
                                p9 = -36;
                                p5 = -45;
                            } else {
                                p5 = p2;
                                p2 = -47;
                            }
                        } else {
                            p2 = 97;
                        }
                    }
                    if ((14 == p5)) {
                        p8 = -22;
                        p2 = p9;
                    } else {
                        if ((p2 < -3)) {
                            p9 = 73;
                        } else {
                            p2 = p8;
                        }
                    }
                } else {
                    p9 = i42;
                    if ((22 == p2)) {
                        p9 = -61;
                    } else {
                        p2 = i42;
                    }
                }
                if ((p2 > p8)) {
                    if ((-100 > p5)) {
                        p5 = -26;
                        if ((p9 <= p2)) {
                            p8 = p8;
                        } else {
                            p5 = p8;
                            p8 = p8;
                        }
                    } else {
                        if ((91 >= -50)) {
                            if ((p9 != p8)) {
                                if ((p9 >= p8)) {
                                    p2 = p2;
                                } else {
                                    p9 = p8;
                                    p8 = -86;
                                }
                            } else {
                                if ((p9 < p2)) {
                                    p8 = p9;
                                } else {
                                    p8 = 77;
                                }
                                p9 = -69;
                            }
                            p2 = -54;
                        } else {
                            p8 = -37;
                        }
                    }
                } else {
                    if ((p8 < p9)) {
                        p5 = p8;
                    } else {
                        if ((-65 >= i42)) {
                            p9 = 74;
                        } else {
                            if ((p9 > i42)) {
                                p8 = p9;
                                if ((p9 >= i42)) {
                                    p2 = p5;
                                    p8 = p2;
                                } else {
                                    p5 = i42;
                                    p8 = p9;
                                }
                            } else {
                                p5 = p2;
                            }
                            if ((p9 <= 36)) {
                                p8 = -77;
                            } else {
                                p9 = i42;
                            }
                        }
                    }
                }
            } else {
                p5 = p9;
            }
        }
        p5 = (p8 / 16);
    }
    return (((p8 & 255) << 4) - ((p9 & 255) << 4));
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 39;
    int v1 = 20;
    int v2 = -9;
    int v3 = 21;
    int v4 = 45;
    int v5 = 47;
    int v6 = -17;
    int v7 = -7;
    int v8 = 31;
    int v9 = 1;
    int v10 = 15;
    int v11 = 24;
    int v12 = 27;
    int v13 = -43;
    int v14 = -45;
    int v15 = 7;
    double d0 = -5.0;
    double d1 = 10.0;
    double d2 = 19.0;
    double d3 = -27.0;
    double d4 = -30.0;
    double d5 = 9.0;
    double d6 = 22.0;
    double d7 = -14.0;
    double d8 = 21.0;
    double d9 = 5.0;
    double d10 = 19.0;
    double d11 = -7.0;
    v6 = ((((-27 & 1023) ^ 980) * (v0 / -3)) + (v14 / 4));
    v1 = (((v8 + v0) - ((v9 & 255) >> 3)) + (v15 + v9));
    d10 = f0((-26.0 + d11), (d2 + d3), (d5 * 2.0), ((v3 & 255) << 1), (d4 * d9), ((v14 & 255) << 2), (d9 + -30.0), v11, (d3 * d11), v1, -22.0, (9.0 + d10));
    d0 = (d0 + (v0 & 63));
    d1 = (d1 + (d5 - 34.0));
    d2 = (d2 + d4);
    d3 = (d3 + d4);
    d4 = (d4 + (14.0 + d9));
    d5 = (d5 + -20.0);
    d6 = (d6 + d4);
    d7 = (d7 + d4);
    d8 = (d8 + ((-68 + v6) & 63));
    d9 = (d9 + (15.0 - 26.0));
    d10 = (d10 + (d5 * d11));
    d11 = (d11 + d8);
    if (((((v5 / -6) & 1023) & 96) < ((v4 & 1023) & 591))) {
        v2 = arr[(((v5 & 1023) | 582)) & 7];
        v3 = v7;
    } else {
        for (int i2 = 0; i2 < 1; i2++) {
            v10 = v13;
            if ((v2 == 47)) {
                if ((-1 >= v11)) {
                    arr[((v7 / 11)) & 7] = -11;
                    v0 = v4;
                } else {
                    v14 = 54;
                    if ((v1 >= v10)) {
                        arr[(((v15 & 1023) | 797)) & 7] = v12;
                        v8 = -32;
                    } else {
                        v10 = v14;
                        v15 = 26;
                    }
                }
                v2 = -71;
            } else {
                if ((-38 == -18)) {
                    v7 = 90;
                    v14 = 53;
                } else {
                    if ((v14 >= -63)) {
                        v15 = -20;
                        v6 = 3;
                    } else {
                        v4 = v0;
                        v15 = v3;
                    }
                }
            }
            v9 = (v14 + v11);
        }
    }
    if (((((v9 + v12) & 255) >> 2) <= v7)) {
        v8 = (((-72 / 8) & 1023) & 72);
    } else {
        for (int i86 = 0; i86 < 3; i86++) {
            v0 = ((-5 & 1023) ^ 719);
        }
        if (((-74 % 5) < (v15 + v9))) {
            if ((v3 <= v14)) {
                v12 = v8;
                v14 = v14;
            } else {
                if ((-24 == v11)) {
                    if ((v7 == 33)) {
                        for (int i67 = 0; i67 < 6; i67++) {
                            v11 = v12;
                            arr[(v5) & 7] = 22;
                        }
                    } else {
                        v7 = v9;
                        for (int i89 = 0; i89 < 4; i89++) {
                            v1 = v11;
                        }
                    }
                } else {
                    v15 = v13;
                }
                if ((v10 <= v13)) {
                    v11 = v12;
                    v11 = v5;
                } else {
                    if ((-51 != v9)) {
                        v11 = v13;
                    } else {
                        for (int i98 = 0; i98 < 5; i98++) {
                            v4 = v3;
                        }
                    }
                }
            }
        } else {
            if ((92 >= -94)) {
                v2 = v14;
                for (int i61 = 0; i61 < 6; i61++) {
                    arr[(((-39 & 1023) | 315)) & 7] = -66;
                    v5 = v13;
                    v13 = v11;
                }
            } else {
                for (int i33 = 0; i33 < 6; i33++) {
                    v8 = 58;
                    v13 = 97;
                }
                v1 = v5;
            }
            v2 = v4;
        }
    }
    v5 = f1((d1 - d1), (d10 * d10), ((87 & 255) >> 2), (-6.0 * d7), -38.0, v13, (d4 + 37.0), d1, 5, (5 + v1));
    d0 = (d0 + (-40.0 + d5));
    d1 = (d1 + d7);
    d2 = (d2 + d8);
    d3 = (d3 + d3);
    d4 = (d4 + (d9 + d4));
    d5 = (d5 + (38.0 + d4));
    d6 = (d6 + ((v8 % 3) & 63));
    d7 = (d7 + d11);
    d8 = (d8 + d5);
    d9 = (d9 + (39.0 * 1.0));
    d10 = (d10 + (d7 + -14.0));
    d11 = (d11 + (d6 + d4));
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != -6701.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
