// EXIT: 0
// OUTPUT: 3693
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(int p0, int p1, double p2, int p3, double p4, double p5, int p6, int p7, double p8, int p9) {
    p9 = p6;
    for (int i60 = 0; i60 < 6; i60++) {
        p1 = i60;
    }
    p1 = (((p3 - p1) & 255) >> 4);
    return ((((p6 & 1023) | 289) & 255) << 3);
}

int f1(int p0, double p1, double p2, int p3, int p4, int p5, double p6, int p7) {
    p5 = ((p5 & 255) >> 3);
    return (((-47 & 255) >> 4) + p7);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 28;
    int v1 = 32;
    int v2 = -6;
    int v3 = 0;
    int v4 = 22;
    int v5 = -14;
    int v6 = -7;
    int v7 = -8;
    int v8 = -22;
    int v9 = 50;
    int v10 = -12;
    int v11 = -32;
    int v12 = 35;
    int v13 = 27;
    int v14 = -17;
    int v15 = -8;
    double d0 = 14.0;
    double d1 = 16.0;
    double d2 = -22.0;
    double d3 = 20.0;
    double d4 = -14.0;
    double d5 = 15.0;
    double d6 = -17.0;
    double d7 = 10.0;
    double d8 = -30.0;
    double d9 = -22.0;
    double d10 = -18.0;
    double d11 = 27.0;
    v12 = (v4 - ((v13 & 1023) ^ 622));
    arr[(((18 & 1023) | 472)) & 7] = ((((v7 & 1023) | 441) & 1023) ^ 798);
    v2 = f0(((v6 & 1023) | 206), ((24 & 1023) & 70), ((28 + 26) & 63), ((v3 & 255) >> 4), (d2 - 29.0), d5, (v5 / -3), ((v15 & 255) >> 0), (d0 * -1.0), ((v5 & 1023) | 893));
    v6 = f0(v15, ((v14 & 255) >> 0), (d2 - d6), v10, ((v3 + v3) & 63), (d11 + d7), -59, -72, d5, v3);
    d0 = (d0 + 2.0);
    d1 = (d1 + (40.0 * d8));
    d2 = (d2 + (((39 & 1023) ^ 1012) & 63));
    d3 = (d3 + (-6.0 - d10));
    d4 = (d4 + d7);
    d5 = (d5 + d5);
    d6 = (d6 + (d2 - -13.0));
    d7 = (d7 + (d5 + d6));
    d8 = (d8 + (26.0 + 2.0));
    d9 = (d9 + d4);
    d10 = (d10 + d10);
    d11 = (d11 + (35.0 + d0));
    arr[((22 * v5)) & 7] = (((((v3 & 255) << 4) & 255) >> 2) % 2);
    if ((((v12 & 1023) ^ 111) > ((-55 & 1023) | 34))) {
        v0 = v2;
    } else {
        arr[(-57) & 7] = ((v3 & 1023) ^ 192);
        v2 = v7;
    }
    if (((((v12 & 255) << 0) / 7) >= (v13 * (v12 / 3)))) {
        v3 = arr[((v0 - 91)) & 7];
        v8 = v8;
    } else {
        arr[(((v12 & 255) >> 1)) & 7] = ((((v15 & 255) << 1) & 255) >> 3);
    }
    v4 = f1(((v10 & 255) >> 1), (d2 * -31.0), (d6 * 20.0), v13, (v14 - v1), v10, d2, (v5 + -24));
    v15 = f0(v13, v10, (d2 - d11), ((v3 & 1023) | 1001), d4, d8, ((v5 & 1023) | 223), v8, (18.0 * -32.0), ((v0 & 255) << 1));
    d0 = (d0 + (4.0 + 8.0));
    d1 = (d1 + d0);
    d2 = (d2 + d10);
    d3 = (d3 + (-39.0 * d6));
    d4 = (d4 + (d11 + -40.0));
    d5 = (d5 + d8);
    d6 = (d6 + ((69 * v3) & 63));
    d7 = (d7 + (d7 - d1));
    d8 = (d8 + (v4 & 63));
    d9 = (d9 + d11);
    d10 = (d10 + d10);
    d11 = (d11 + (d4 - 12.0));
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != 576.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
