// EXIT: 0
// OUTPUT: 1411
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

int f0(int p0, int p1, double p2, double p3, int p4, double p5, int p6, double p7, int p8, double p9, double p10) {
    p8 = ((p0 & 255) >> 4);
    return ((24 - p8) % 16);
}

int f1(double p0, double p1, int p2, double p3, int p4, int p5, int p6, int p7) {
    for (int i56 = 0; i56 < 1; i56++) {
        p2 = (p6 / 8);
        p4 = 56;
        p2 = ((p4 & 1023) | 979);
    }
    return p5;
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = -8;
    int v1 = 33;
    int v2 = -40;
    int v3 = 30;
    int v4 = -48;
    int v5 = 29;
    int v6 = -30;
    int v7 = 48;
    int v8 = -41;
    int v9 = 22;
    int v10 = -47;
    int v11 = -2;
    int v12 = -35;
    int v13 = 37;
    int v14 = -17;
    int v15 = -45;
    double d0 = 30.0;
    double d1 = 5.0;
    double d2 = -16.0;
    double d3 = 7.0;
    double d4 = 10.0;
    double d5 = 5.0;
    double d6 = 2.0;
    double d7 = 22.0;
    double d8 = -2.0;
    double d9 = -8.0;
    double d10 = -14.0;
    double d11 = -2.0;
    for (int i44 = 0; i44 < 6; i44++) {
        v10 = ((((v15 & 1023) & 631) & 1023) ^ 421);
    }
    arr[(((v13 & 1023) | 599)) & 7] = (((((27 & 1023) ^ 320) & 1023) ^ 199) + (((v9 & 1023) | 608) % -3));
    v6 = ((((-11 & 255) << 2) & 1023) ^ 1008);
    v5 = f0((40 - v14), ((v14 & 1023) ^ 180), d5, d5, v5, (d0 + d4), ((-100 & 1023) ^ 150), (d6 - d3), ((v14 & 1023) & 432), (d6 * d2), (d0 - -14.0));
    v1 = f1((-38.0 - d5), (36.0 - d7), v14, 25.0, (-6 * v3), v0, ((v1 & 1023) | 14), 37);
    d0 = (d0 + (d9 * d6));
    d1 = (d1 + d1);
    d2 = (d2 + (d8 - -5.0));
    d3 = (d3 + (d9 - d10));
    d4 = (d4 + ((v15 + v7) & 63));
    d5 = (d5 + (d6 * d11));
    d6 = (d6 + (-19.0 - d6));
    d7 = (d7 + ((20 % -3) & 63));
    d8 = (d8 + (d1 + d11));
    d9 = (d9 + (d11 - d1));
    d10 = (d10 + (15.0 * d0));
    d11 = (d11 + -3.0);
    if (((-75 % 2) == -80)) {
        arr[((v13 * v15)) & 7] = ((v14 & 255) << 1);
    } else {
        if ((-46 < v8)) {
            for (int i46 = 0; i46 < 3; i46++) {
                v15 = 97;
                v4 = v1;
                arr[(((44 & 255) >> 2)) & 7] = v3;
            }
        } else {
            v1 = ((-90 & 1023) & 602);
        }
    }
    if ((94 >= ((34 + v9) + ((v3 & 1023) | 641)))) {
        if ((-28 >= ((v10 & 255) << 0))) {
            v8 = ((v3 & 1023) | 576);
        } else {
            if ((v2 <= v13)) {
                if ((v15 != -75)) {
                    arr[(((-98 & 255) << 2)) & 7] = v8;
                    for (int i18 = 0; i18 < 2; i18++) {
                        arr[((v4 * -91)) & 7] = v14;
                    }
                } else {
                    if ((v14 >= v7)) {
                        for (int i2 = 0; i2 < 1; i2++) {
                            arr[((v6 * v6)) & 7] = v13;
                        }
                        v12 = v7;
                    } else {
                        v10 = -96;
                        arr[(-30) & 7] = v0;
                    }
                }
                v14 = v3;
            } else {
                v8 = 47;
                arr[(((v13 & 255) >> 4)) & 7] = 99;
            }
        }
    } else {
        v9 = (((v11 * v2) & 1023) & 585);
        for (int i40 = 0; i40 < 1; i40++) {
            v12 = ((i40 & 1023) | 757);
        }
    }
    v9 = f1((d2 * d1), (d2 * -8.0), ((28 & 1023) ^ 12), d9, ((10 & 255) >> 3), (v15 * v11), ((81 & 1023) & 993), (v1 % 3));
    v12 = f0((v3 / 8), ((v3 & 1023) & 1001), d4, (-17 & 63), ((62 & 1023) ^ 819), (d0 + d4), ((v14 & 1023) ^ 1002), (((14 & 1023) ^ 697) & 63), ((v8 & 1023) & 252), (d8 + -39.0), (((-99 & 1023) ^ 765) & 63));
    d0 = (d0 + (d8 + d2));
    d1 = (d1 + d9);
    d2 = (d2 + ((98 * v13) & 63));
    d3 = (d3 + (d8 - -11.0));
    d4 = (d4 + d1);
    d5 = (d5 + (d2 - -6.0));
    d6 = (d6 + d10);
    d7 = (d7 + (((84 & 255) >> 1) & 63));
    d8 = (d8 + (d9 - 25.0));
    d9 = (d9 + ((v12 % 11) & 63));
    d10 = (d10 + (((v9 & 255) << 3) & 63));
    d11 = (d11 + (d9 + 12.0));
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != 526.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
