// KNOWN FAILING -- wrong value at -O0. Do not "fix" by weakening it.
//
//   cc -O0 and cc -O2   442
//   blitz -O0            432
//   blitz -O1            cannot allocate registers
//
// ONE TERM IS WRONG: v11, arriving as 1 where 11 belongs, which is the whole 10
// of the discrepancy. `read_frame.py --sum-chain` reads every term off the
// unmodified binary, and `cc` compiled with the printf split into one call per
// term gives the reference values to compare against -- v11 is the only
// disagreement.
//
// v11 is `(((v13 / 7) & 1023) | 11)`, assigned every iteration of the first loop.
// An OR with 11 cannot produce 1, so the term is not that expression's result at
// all. v13 is -3 throughout that loop, so the value is 11 every time.
//
// TRACED to a single store, each step read off the running binary:
//
//   v11's term       <- slot 139, reloaded
//   slot 139         <- v303 = BlockParam(23, 24), spilled in b23
//   b23's p24        <- b22's terminator arg, reloaded from slot 110
//   slot 110         <- v220 = BlockParam(22, 12), spilled in b22
//   b22's p12        <- class 403 on both edges, reloaded from slot 18
//   slot 18          <- the ROUTED PARAMETER b1#26, which is v11 across the loop
//
// and slot 18 is where it goes wrong. The preheader stores 23, v11's initialiser,
// correctly. The latch then stores the LOOP COUNTER -- 0 on the first iteration,
// 1 on the second -- into v11's slot, and every later read of v11 sees it.
//
// WHERE TO PICK UP. The latch's terminator argument at position 26 resolves via
// the per-block snapshot to `v690 = BlockParam(19, 26)`, allocated RBP
// (`BLITZ_DEBUG=phi` now prints which of the two sources answered each argument).
// The emitted store reads RCX, not RBP, so the store's source is not that
// operand's register: either coalescing renamed it onto something unrelated, or
// the store was built from a different argument than position 26. Settle that
// first -- it is one question, and the answer names the pass.
//
// gen_c.py seed 18, shape pressure, saved unreduced: reducing this program once
// before drifted onto a different bug, and the term-level localisation does not
// need it smaller.
//
// EXIT: 0
// OUTPUT: 442
// EXIT: 0
// OUTPUT: 442
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

double f0(double p0, double p1, double p2, int p3, double p4, int p5, int p6) {
    p3 = ((((p6 & 1023) & 1014) & 255) << 3);
    return (((p3 & 1023) & 768) & 63);
}

int f1(int p0, double p1, int p2, int p3, double p4, int p5, double p6, int p7) {
    if (((p7 * p0) >= (p0 % 2))) {
        p5 = -99;
        p7 = p2;
    } else {
        if ((p3 <= -24)) {
            p3 = -86;
            p0 = p5;
        } else {
            p2 = p3;
        }
    }
    p5 = ((-61 + -96) / 4);
    if (((p7 / 8) <= p2)) {
        for (int i44 = 0; i44 < 1; i44++) {
            if ((p2 < -99)) {
                p3 = p7;
                p5 = i44;
            } else {
                p0 = 51;
            }
            p3 = i44;
        }
        for (int i84 = 0; i84 < 5; i84++) {
            p3 = i84;
            p0 = p7;
        }
    } else {
        p2 = p7;
        p2 = ((p0 & 1023) & 792);
    }
    return ((p2 / 2) / -6);
}

double f2(double p0, double p1, double p2, double p3, int p4, int p5, double p6, int p7, int p8) {
    p8 = -97;
    for (int i19 = 0; i19 < 6; i19++) {
        p5 = ((p7 & 255) >> 1);
        p7 = p4;
        p7 = -56;
    }
    return ((p6 - p2) - (((p8 & 255) << 3) & 63));
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 41;
    int v1 = 5;
    int v2 = -29;
    int v3 = 27;
    int v4 = 26;
    int v5 = -44;
    int v6 = 25;
    int v7 = 21;
    int v8 = -33;
    int v9 = 1;
    int v10 = -41;
    int v11 = 23;
    int v12 = 4;
    int v13 = -3;
    int v14 = 37;
    int v15 = -20;
    double d0 = 14.0;
    double d1 = 8.0;
    double d2 = -25.0;
    double d3 = -15.0;
    double d4 = -22.0;
    double d5 = -6.0;
    double d6 = -22.0;
    double d7 = 17.0;
    double d8 = 4.0;
    double d9 = -3.0;
    double d10 = -27.0;
    double d11 = -24.0;
    for (int i99 = 0; i99 < 2; i99++) {
        v11 = (((v13 / 7) & 1023) | 11);
        if ((((87 & 255) >> 3) < 45)) {
            if ((85 <= v10)) {
                v2 = 31;
                v7 = v5;
            } else {
                if ((v2 == 27)) {
                    v3 = -5;
                } else {
                    arr[(((v15 & 1023) | 575)) & 7] = i99;
                    if ((88 != v10)) {
                        v3 = -27;
                        v14 = v2;
                    } else {
                        arr[(((v1 & 1023) & 610)) & 7] = v2;
                        arr[(((v9 & 255) << 2)) & 7] = v10;
                    }
                }
                arr[(v2) & 7] = v15;
            }
            v10 = i99;
        } else {
            v7 = (-12 - v8);
            if ((-41 <= i99)) {
                v14 = v7;
                v10 = v0;
            } else {
                v11 = v7;
                v1 = i99;
            }
        }
        arr[((v7 - v9)) & 7] = arr[(((-80 & 255) << 4)) & 7];
    }
    v6 = f1((36 / -6), d10, 98, v15, d7, (-51 - v12), 38.0, ((-100 & 255) >> 1));
    d0 = (d0 + d7);
    d1 = (d1 + d11);
    d2 = (d2 + (-33.0 + 10.0));
    d3 = (d3 + -30.0);
    d4 = (d4 + d8);
    d5 = (d5 + (d2 * d8));
    d6 = (d6 + (-13.0 + 20.0));
    d7 = (d7 + ((1 - -57) & 63));
    d8 = (d8 + (d10 + d5));
    d9 = (d9 + (((v6 & 1023) & 735) & 63));
    d10 = (d10 + (d6 * 6.0));
    d11 = (d11 + (d7 + d9));
    if ((v1 > (((v6 % 7) & 255) << 1))) {
        v3 = arr[(((-66 & 1023) ^ 812)) & 7];
    } else {
        v1 = ((((6 & 1023) | 720) & 1023) & 930);
        v13 = 77;
    }
    d5 = f2((d6 * -37.0), ((-30 - v6) & 63), ((v3 * v4) & 63), (d2 - d3), ((v7 & 255) >> 2), v0, d11, -98, v12);
    d8 = f2((d9 + d2), (35.0 - d1), (((-27 & 1023) ^ 142) & 63), ((98 + 95) & 63), (v11 / 11), ((v11 & 1023) ^ 570), -2.0, ((v4 & 1023) | 63), ((11 & 255) << 4));
    d0 = (d0 + d7);
    d1 = (d1 + (35.0 - 11.0));
    d2 = (d2 + (17.0 * d11));
    d3 = (d3 + d2);
    d4 = (d4 + d3);
    d5 = (d5 + d0);
    d6 = (d6 + 39.0);
    d7 = (d7 + (((v13 & 1023) & 1012) & 63));
    d8 = (d8 + -5.0);
    d9 = (d9 + (34.0 + d8));
    d10 = (d10 + d0);
    d11 = (d11 + (d1 * d9));
    for (int i36 = 0; i36 < 4; i36++) {
        if ((v2 <= (-11 / 2))) {
            v0 = ((v4 & 1023) & 514);
        } else {
            v15 = 51;
        }
    }
    v13 = v9;
    d11 = f2((d10 + d4), d7, (-39.0 * d10), d4, (v7 / 16), (v2 * v6), (d2 + d11), (v3 + v8), ((-1 & 1023) | 742));
    d7 = f0((d5 * 39.0), d8, (d1 * -35.0), (v1 - 33), (d9 + -20.0), (30 + -66), 96);
    d0 = (d0 + (d6 * d0));
    d1 = (d1 + (((v1 & 255) >> 4) & 63));
    d2 = (d2 + d8);
    d3 = (d3 + (12.0 - d1));
    d4 = (d4 + d8);
    d5 = (d5 + d8);
    d6 = (d6 + d10);
    d7 = (d7 + (d8 - d1));
    d8 = (d8 + d6);
    d9 = (d9 + d7);
    d10 = (d10 + (d9 - d5));
    d11 = (d11 + d1);
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != 6156.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
