// KNOWN FAILING -- unreduced reproducer. Do not "fix" by weakening it.
//
//   cc -O0 and cc -O2   2014
//   blitz -O0            exits 3 (the program's own guard rejected its float sum)
//   blitz -O1            cannot allocate registers (ROADMAP P0)
//
// tests/fuzz/gen_c.py seed 32, shape mixed, saved verbatim: the generator was
// fixed after this (loop counters are no longer assignment targets), so the
// same seed no longer produces this program. Not yet reduced.
//
// EXIT: 0
// OUTPUT: 2014
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

double f0(int p0, int p1, double p2, int p3, double p4, double p5, double p6, int p7, double p8, double p9, int p10, int p11) {
    p11 = (p11 * ((-63 & 1023) & 345));
    p3 = (((84 - p1) & 1023) & 8);
    return -21.0;
}

int f1(double p0, int p1, double p2, int p3, int p4, double p5, double p6, double p7) {
    p3 = p4;
    p3 = ((-26 & 255) << 3);
    p4 = (((74 & 255) >> 0) + (p4 % -6));
    return 93;
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 2;
    int v1 = 20;
    int v2 = -29;
    int v3 = 12;
    int v4 = 27;
    int v5 = 1;
    int v6 = 7;
    int v7 = 33;
    int v8 = 1;
    int v9 = -19;
    double d0 = 27.0;
    double d1 = -18.0;
    double d2 = -3.0;
    double d3 = 9.0;
    double d4 = -3.0;
    double d5 = 19.0;
    v6 = (((v3 * v5) & 255) << 2);
    if (((((v9 * v6) & 1023) ^ 807) < v5)) {
        arr[(v5) & 7] = (((v4 & 255) << 3) % 11);
    } else {
        arr[(-65) & 7] = v1;
        v9 = (v8 - ((62 & 255) << 3));
    }
    d0 = f0(64, -60, -4.0, (v3 % 3), (d2 * -36.0), (((-11 & 255) >> 2) & 63), d5, (-7 - 55), d1, -37.0, ((v6 & 1023) ^ 313), v8);
    v4 = f1(d4, ((v7 & 1023) & 627), (d5 + 35.0), v9, (24 * v0), 32.0, d5, d1);
    d0 = (d0 + d3);
    d1 = (d1 + (((v0 & 1023) ^ 712) & 63));
    d2 = (d2 + (d2 - d1));
    d3 = (d3 + (d3 - d0));
    d4 = (d4 + (d5 + d4));
    d5 = (d5 + (d4 + d4));
    if (((((v5 % -6) & 1023) | 96) == (v6 * v3))) {
        v7 = ((((v9 & 1023) | 525) & 1023) & 868);
        if (((v5 % 2) == ((34 & 255) << 1))) {
            for (int i37 = 0; i37 < 5; i37++) {
                v3 = v4;
                v3 = v4;
                v7 = -74;
            }
        } else {
            arr[((v3 / 2)) & 7] = v0;
        }
    } else {
        for (int i11 = 0; i11 < 1; i11++) {
            arr[((-15 * 17)) & 7] = ((v3 & 1023) ^ 670);
        }
    }
    d0 = f0((v2 - v2), ((v2 & 1023) ^ 945), ((v5 / -3) & 63), (v1 * 77), d5, (d2 * d2), (39.0 - d3), ((v4 & 255) >> 0), (d0 + d4), (d5 * 30.0), -29, (-64 / 4));
    d0 = (d0 + (d1 * d1));
    d1 = (d1 + (d3 * d0));
    d2 = (d2 + (d1 * -1.0));
    d3 = (d3 + d1);
    d4 = (d4 + d3);
    d5 = (d5 + (40.0 * d4));
    for (int i21 = 0; i21 < 5; i21++) {
        v3 = v6;
        v4 = (((-15 + v8) & 255) >> 3);
        v6 = (((v5 + v6) & 1023) ^ 949);
    }
    v9 = ((v9 & 1023) ^ 673);
    v0 = f1(14.0, v8, (d0 * d2), v8, ((v8 & 255) << 2), d5, d2, (((v4 & 1023) & 146) & 63));
    v3 = f1((d3 - d3), ((53 & 1023) & 208), -23.0, v9, ((-68 & 255) << 0), d4, d5, (v4 & 63));
    d0 = (d0 + d5);
    d1 = (d1 + d3);
    d2 = (d2 + (v3 & 63));
    d3 = (d3 + 29.0);
    d4 = (d4 + d5);
    d5 = (d5 + 23.0);
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != 163210.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
