// KNOWN FAILING -- unreduced reproducer. Do not "fix" by weakening it.
//
//   cc -O0 and cc -O2   816
//   blitz -O0            exits 3 (the program's own guard rejected its float sum)
//   blitz -O1            cannot allocate registers (ROADMAP P0)
//
// tests/fuzz/gen_c.py seed 16, shape mixed, saved verbatim: the generator was
// fixed after this (loop counters are no longer assignment targets), so the
// same seed no longer produces this program. Not yet reduced.
//
// EXIT: 0
// OUTPUT: 816
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

double f0(double p0, double p1, double p2, double p3, int p4, int p5, int p6) {
    for (int i84 = 0; i84 < 5; i84++) {
        i84 = ((87 & 255) >> 1);
        p6 = ((i84 & 255) << 1);
    }
    p6 = 72;
    return (p0 + (p3 + -20.0));
}

int f1(int p0, double p1, double p2, int p3, double p4, int p5, int p6, int p7, double p8, double p9, double p10) {
    for (int i1 = 0; i1 < 5; i1++) {
        p3 = (57 / 7);
    }
    p6 = p0;
    if (((p0 % -3) >= ((p7 & 255) >> 3))) {
        p0 = (p3 - p7);
        if ((97 < p6)) {
            for (int i26 = 0; i26 < 3; i26++) {
                p3 = 29;
            }
            for (int i27 = 0; i27 < 1; i27++) {
                if ((p5 < p3)) {
                    if ((i27 > p7)) {
                        i27 = p5;
                        p7 = -97;
                    } else {
                        if ((p3 != p6)) {
                            if ((p3 != p6)) {
                                p7 = -37;
                            } else {
                                if ((-52 <= p3)) {
                                    if ((i27 > p0)) {
                                        p5 = p3;
                                        p6 = -63;
                                    } else {
                                        if ((p5 < p6)) {
                                            p7 = p5;
                                            i27 = -14;
                                        } else {
                                            if ((-65 >= 49)) {
                                                i27 = -84;
                                                p5 = -87;
                                            } else {
                                                p6 = p0;
                                                p7 = -33;
                                            }
                                        }
                                    }
                                } else {
                                    p0 = p0;
                                    p5 = p6;
                                }
                            }
                            p6 = -85;
                        } else {
                            p3 = p5;
                        }
                        i27 = 72;
                    }
                } else {
                    if ((p6 >= p7)) {
                        p5 = p7;
                    } else {
                        if ((p0 >= 69)) {
                            if ((p3 != 17)) {
                                p3 = p0;
                            } else {
                                p3 = p0;
                                p0 = p3;
                            }
                        } else {
                            if ((-55 <= p3)) {
                                p3 = p6;
                            } else {
                                if ((-54 >= p5)) {
                                    i27 = p6;
                                } else {
                                    i27 = -83;
                                    i27 = p6;
                                }
                            }
                        }
                        if ((p6 == p3)) {
                            i27 = -66;
                            p5 = 49;
                        } else {
                            p6 = p0;
                        }
                    }
                }
                p0 = -23;
                p5 = 11;
            }
        } else {
            if ((p7 <= p5)) {
                if ((p6 == -7)) {
                    p7 = p3;
                    for (int i54 = 0; i54 < 5; i54++) {
                        if ((91 >= p7)) {
                            i54 = p3;
                        } else {
                            if ((p0 >= 35)) {
                                if ((p0 != p0)) {
                                    i54 = p3;
                                } else {
                                    p3 = i54;
                                    p7 = -76;
                                }
                                if ((p3 <= p6)) {
                                    p7 = -85;
                                    if ((p6 >= p5)) {
                                        p7 = p0;
                                        p6 = i54;
                                    } else {
                                        p6 = 37;
                                        i54 = -37;
                                    }
                                } else {
                                    p7 = p7;
                                    p5 = p5;
                                }
                            } else {
                                p0 = -32;
                            }
                        }
                        p5 = p7;
                        p5 = i54;
                    }
                } else {
                    for (int i17 = 0; i17 < 5; i17++) {
                        if ((-40 > p0)) {
                            if ((p7 >= p7)) {
                                if ((12 >= 38)) {
                                    p7 = p0;
                                    i17 = p3;
                                } else {
                                    p6 = p0;
                                    p7 = i17;
                                }
                                if ((p0 != p0)) {
                                    if ((47 == p7)) {
                                        if ((i17 == p0)) {
                                            p3 = p0;
                                        } else {
                                            if ((p5 != i17)) {
                                                p3 = p6;
                                            } else {
                                                if ((p0 != 60)) {
                                                    p5 = i17;
                                                } else {
                                                    p6 = p6;
                                                    p5 = p5;
                                                }
                                            }
                                            p7 = -5;
                                        }
                                    } else {
                                        i17 = 50;
                                    }
                                } else {
                                    if ((p3 > -12)) {
                                        i17 = p5;
                                    } else {
                                        i17 = p0;
                                        p0 = p5;
                                    }
                                    p6 = p0;
                                }
                            } else {
                                if ((i17 >= p0)) {
                                    if ((-53 <= p5)) {
                                        if ((p0 != p3)) {
                                            i17 = 55;
                                            p7 = 55;
                                        } else {
                                            p0 = -76;
                                            if ((p0 != 48)) {
                                                p5 = p3;
                                                p5 = p5;
                                            } else {
                                                p5 = p0;
                                            }
                                        }
                                        p6 = -45;
                                    } else {
                                        p7 = p5;
                                        p3 = 13;
                                    }
                                    i17 = 60;
                                } else {
                                    p6 = p3;
                                    p7 = 73;
                                }
                                i17 = p6;
                            }
                        } else {
                            p3 = -23;
                            p6 = -94;
                        }
                        p7 = p0;
                        i17 = -55;
                    }
                }
                for (int i51 = 0; i51 < 5; i51++) {
                    i51 = p7;
                    i51 = p5;
                    p7 = i51;
                }
            } else {
                for (int i16 = 0; i16 < 1; i16++) {
                    p0 = 9;
                }
            }
            p5 = p6;
        }
    } else {
        for (int i91 = 0; i91 < 3; i91++) {
            p0 = 25;
            p3 = -47;
            p6 = p6;
        }
        p6 = (-46 + p3);
    }
    return ((((p5 & 255) << 3) & 1023) ^ 511);
}

int f2(double p0, double p1, int p2, double p3, double p4, int p5, double p6, int p7, int p8, double p9) {
    if ((((p8 & 255) >> 1) >= ((p2 & 1023) ^ 746))) {
        p7 = (p5 % 4);
    } else {
        p5 = p5;
        p5 = (-63 - p2);
    }
    p8 = p5;
    return ((p5 & 255) << 1);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = -41;
    int v1 = 34;
    int v2 = 35;
    int v3 = -42;
    int v4 = 23;
    int v5 = 34;
    int v6 = -21;
    int v7 = 13;
    int v8 = 50;
    int v9 = -42;
    double d0 = 26.0;
    double d1 = 14.0;
    double d2 = 1.0;
    double d3 = 1.0;
    double d4 = 26.0;
    double d5 = 22.0;
    v0 = ((((v9 % 5) - ((-29 & 255) << 0)) & 1023) & 98);
    d0 = f0((d2 * d1), 13.0, (d2 - d0), (v4 & 63), ((v6 & 255) >> 1), (48 % 4), ((v2 & 1023) | 126));
    d0 = (d0 + (d3 + 33.0));
    d1 = (d1 + (d2 + d2));
    d2 = (d2 + (39.0 * d4));
    d3 = (d3 + (d3 + d3));
    d4 = (d4 + ((-81 / -6) & 63));
    d5 = (d5 + 18.0);
    v4 = (((((v2 & 255) << 3) & 1023) & 604) + v2);
    v8 = f2(d5, d4, v2, ((v6 / 16) & 63), (d3 - d1), (v7 / 4), (d1 + d2), ((v0 & 1023) & 111), (-57 % 16), d4);
    d0 = (d0 + (d5 + d3));
    d1 = (d1 + d5);
    d2 = (d2 + -8.0);
    d3 = (d3 + (d1 - 2.0));
    d4 = (d4 + (d4 + d4));
    d5 = (d5 + d4);
    if ((((v9 - v4) * ((v9 & 1023) & 27)) == v6)) {
        v6 = -97;
        v8 = arr[(v6) & 7];
    } else {
        v9 = v9;
    }
    v3 = f2(d4, (d5 + 7.0), ((v6 & 255) >> 4), (v7 & 63), (d3 - d3), 51, (d3 + d3), v8, v8, d2);
    d0 = (d0 + (d2 + d4));
    d1 = (d1 + d0);
    d2 = (d2 + -22.0);
    d3 = (d3 + d1);
    d4 = (d4 + (v7 & 63));
    d5 = (d5 + (d1 + d1));
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != 7643.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
