// KNOWN FAILING -- reproducer for a real bug. Do not "fix" by weakening it.
//
// Found by tests/fuzz/gen_c.py (seed 5, --size small) on its first run.
//
//   generator interpreter   606
//   gcc -O0                 606
//   clang -O0               606
//   blitz -O1               610      <- silent wrong answer
//   blitz -O0               SIGSEGV  <- exit 139
//
// The program is free of undefined behavior by construction, so all three
// oracles agreeing on 606 makes this a blitz bug rather than a program that
// was entitled to more than one answer.
//
// Reproduce:
//   python3 tests/fuzz/gen_c.py --seed 5 --size small --out /tmp/s5.c
//
// OUTPUT: 606
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

double f0(int p0, int p1, int p2, int p3, int p4, double p5, int p6) {
    p0 = p6;
    return ((40.0 - p5) + (-51 & 63));
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 33;
    int v1 = -22;
    int v2 = 49;
    int v3 = -31;
    double d0 = -29.0;
    double d1 = 18.0;
    double d2 = 8.0;
    v2 = (((v3 / 3) & 1023) & 606);
    d0 = f0(((16 & 255) >> 4), v1, (7 * v0), ((v3 & 1023) | 795), (-87 - 96), (d2 + d0), (v1 / 11));
    d0 = (d0 + d1);
    d1 = (d1 + (d2 - 6.0));
    d2 = (d2 + d0);
    if (((d0 + d1) + d2) != 212.0) { return 3; }
    printf("%d\n", (((((((((((v0 + v1) + v2) + v3) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
