// KNOWN FAILING -- wrong value at -O0, not yet analysed. Do not "fix" by
// weakening it.
//
// blitz -O0 prints -125 where -149 is right.
//
// One of four wrong-value programs the `pressure` shape produces, kept as
// reproducers. Start with `tests/fuzz/perturb.py` to name the wrong terms, then
// confirm each against the unmodified binary with `read_frame.py --sum-chain`:
// perturbation alone flags terms that are artefacts of the probe.
//
// gen_c.py seed 13, shape pressure, saved unreduced.
//
// EXIT: 0
// OUTPUT: -149
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

double f0(double p0, int p1, int p2, int p3, int p4, double p5, int p6) {
    for (int i70 = 0; i70 < 6; i70++) {
        p4 = (p3 % 2);
        p3 = ((p4 & 255) >> 2);
    }
    p2 = (p1 / 7);
    return ((2.0 * p5) + p5);
}

int f1(int p0, int p1, double p2, int p3, int p4, double p5, int p6, double p7, double p8) {
    p0 = (((-67 & 1023) ^ 393) % 2);
    return p0;
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = -36;
    int v1 = -6;
    int v2 = 13;
    int v3 = 47;
    int v4 = -3;
    int v5 = -4;
    int v6 = -48;
    int v7 = -39;
    int v8 = 34;
    int v9 = 8;
    int v10 = 41;
    int v11 = 19;
    int v12 = 9;
    int v13 = 50;
    int v14 = -28;
    int v15 = -24;
    double d0 = -22.0;
    double d1 = 14.0;
    double d2 = 6.0;
    double d3 = 14.0;
    double d4 = 14.0;
    double d5 = 5.0;
    double d6 = -29.0;
    double d7 = 12.0;
    double d8 = -22.0;
    double d9 = 5.0;
    double d10 = -25.0;
    double d11 = -19.0;
    if ((v12 != -13)) {
        v10 = v0;
    } else {
        v3 = ((((-9 & 1023) ^ 130) & 255) >> 2);
    }
    d10 = f0(((v15 + v4) & 63), v1, ((44 & 1023) & 866), ((30 & 1023) | 429), (v11 / 3), d7, (54 % 5));
    d0 = (d0 + d10);
    d1 = (d1 + (d8 + -40.0));
    d2 = (d2 + (((v9 & 1023) & 426) & 63));
    d3 = (d3 + (-10.0 - d6));
    d4 = (d4 + (d3 - d1));
    d5 = (d5 + (d9 - d2));
    d6 = (d6 + (d10 * d10));
    d7 = (d7 + d2);
    d8 = (d8 + d7);
    d9 = (d9 + (d7 - d11));
    d10 = (d10 + (d10 * d2));
    d11 = (d11 + ((-60 - 31) & 63));
    for (int i99 = 0; i99 < 5; i99++) {
        v2 = v3;
    }
    for (int i41 = 0; i41 < 5; i41++) {
        v9 = v2;
        v2 = ((((86 & 255) << 3) & 1023) & 160);
        v2 = (v12 * (-93 % 8));
    }
    v14 = f1(v7, v14, d11, ((v14 & 1023) ^ 195), ((-26 & 1023) ^ 892), ((v15 % 7) & 63), v2, d2, (d5 * d0));
    v13 = f1((v4 + v2), ((v9 & 1023) | 636), d8, ((v15 & 255) >> 0), v7, (-19.0 - d8), ((-12 & 1023) & 298), (v15 & 63), d5);
    d0 = (d0 + d8);
    d1 = (d1 + (d10 * d11));
    d2 = (d2 + (23.0 - -37.0));
    d3 = (d3 + (-40.0 + d6));
    d4 = (d4 + 6.0);
    d5 = (d5 + 31.0);
    d6 = (d6 + (d7 * d6));
    d7 = (d7 + (d11 * d9));
    d8 = (d8 + (-9.0 - d11));
    d9 = (d9 + (((50 & 1023) | 975) & 63));
    d10 = (d10 + (d1 - d10));
    d11 = (d11 + d8);
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != 56044.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
