// KNOWN FAILING -- wrong value at -O0, not yet analysed. Do not "fix" by
// weakening it.
//
// blitz -O0 exits 3: its own float guard rejects the sum, and -O0 and -O1 disagree.
//
// One of four wrong-value programs the `pressure` shape produces, kept as
// reproducers. Start with `tests/fuzz/perturb.py` to name the wrong terms, then
// confirm each against the unmodified binary with `read_frame.py --sum-chain`:
// perturbation alone flags terms that are artefacts of the probe.
//
// gen_c.py seed 3, shape pressure, saved unreduced.
//
// EXIT: 0
// OUTPUT: 1748
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

double f0(int p0, int p1, double p2, double p3, double p4, int p5, double p6, int p7, int p8, int p9) {
    for (int i15 = 0; i15 < 5; i15++) {
        p9 = ((p9 & 255) << 2);
        if ((-76 != -29)) {
            p1 = p9;
        } else {
            if ((59 < -76)) {
                if ((p9 <= 35)) {
                    p9 = p5;
                } else {
                    p7 = p7;
                }
            } else {
                p8 = 15;
                p0 = -91;
            }
            p8 = -33;
        }
        p5 = ((-75 & 255) >> 3);
    }
    for (int i47 = 0; i47 < 4; i47++) {
        p7 = ((p0 & 1023) ^ 767);
        if ((p7 != -88)) {
            p5 = p1;
            if ((i47 == p7)) {
                if ((-9 > p5)) {
                    p7 = 57;
                    p5 = -39;
                } else {
                    if ((p0 <= -5)) {
                        p8 = p9;
                    } else {
                        if ((p7 < p5)) {
                            p5 = p0;
                        } else {
                            p7 = p1;
                        }
                    }
                }
                p9 = p5;
            } else {
                p5 = p9;
            }
        } else {
            p5 = p9;
        }
    }
    if ((((p7 & 255) << 2) <= (p1 % 7))) {
        p9 = p8;
    } else {
        p8 = ((-25 & 255) >> 2);
        for (int i40 = 0; i40 < 1; i40++) {
            p8 = 46;
            p1 = p8;
            p5 = 38;
        }
    }
    return ((p2 + p4) - (p2 - -1.0));
}

double f1(double p0, int p1, int p2, double p3, double p4, int p5, double p6, double p7, int p8) {
    if (((-94 % 4) >= p8)) {
        if ((p2 != p1)) {
            if ((p5 == p5)) {
                if ((p2 < p2)) {
                    if ((44 == -5)) {
                        p2 = p2;
                    } else {
                        if ((p1 < 31)) {
                            p5 = p5;
                            if ((p1 == p1)) {
                                for (int i80 = 0; i80 < 6; i80++) {
                                    p8 = p5;
                                }
                            } else {
                                for (int i49 = 0; i49 < 3; i49++) {
                                    if ((i49 == p8)) {
                                        p1 = 27;
                                        p5 = p1;
                                    } else {
                                        p8 = p1;
                                    }
                                }
                                p1 = p5;
                            }
                        } else {
                            p5 = p5;
                            for (int i28 = 0; i28 < 1; i28++) {
                                p5 = p5;
                                p1 = -56;
                            }
                        }
                    }
                } else {
                    if ((-21 == p2)) {
                        p1 = -8;
                    } else {
                        if ((p1 < 38)) {
                            for (int i76 = 0; i76 < 4; i76++) {
                                p8 = p5;
                                if ((i76 > p1)) {
                                    if ((p8 < -77)) {
                                        p8 = i76;
                                    } else {
                                        if ((i76 == 81)) {
                                            p8 = 79;
                                        } else {
                                            if ((p1 > i76)) {
                                                p8 = p2;
                                                if ((54 >= p1)) {
                                                    p5 = p5;
                                                } else {
                                                    p5 = p5;
                                                }
                                            } else {
                                                p8 = p2;
                                            }
                                            p8 = -73;
                                        }
                                        p1 = 96;
                                    }
                                } else {
                                    p2 = i76;
                                }
                                if ((-55 <= p5)) {
                                    p1 = 2;
                                    if ((p5 == p2)) {
                                        p5 = p8;
                                    } else {
                                        if ((p5 <= 48)) {
                                            if ((p1 != -84)) {
                                                p5 = p5;
                                            } else {
                                                if ((i76 == i76)) {
                                                    p1 = p2;
                                                } else {
                                                    p1 = p5;
                                                }
                                                if ((p2 < -15)) {
                                                    p8 = p2;
                                                } else {
                                                    p1 = p8;
                                                }
                                            }
                                            if ((p8 > p5)) {
                                                p1 = i76;
                                            } else {
                                                if ((i76 != p2)) {
                                                    if ((p8 < p5)) {
                                                        p2 = p2;
                                                    } else {
                                                        p1 = -17;
                                                    }
                                                    if ((p1 > i76)) {
                                                        if ((85 <= -14)) {
                                                            p8 = -5;
                                                        } else {
                                                            if ((p2 > -91)) {
                                                                if ((97 <= p5)) {
                                                                    p2 = p2;
                                                                    if ((p2 >= p8)) {
                                                                        if ((p5 != p8)) {
                                                                            p1 = p2;
                                                                        } else {
                                                                            p2 = -61;
                                                                            if ((p5 > i76)) {
                                                                                p1 = 77;
                                                                            } else {
                                                                                p1 = p5;
                                                                                if ((p2 >= -91)) {
                                                                                    if ((p8 != 21)) {
                                                                                        p2 = p5;
                                                                                    } else {
                                                                                        if ((21 <= p2)) {
                                                                                            p1 = p1;
                                                                                        } else {
                                                                                            p5 = p5;
                                                                                            p8 = p2;
                                                                                        }
                                                                                    }
                                                                                } else {
                                                                                    p8 = -30;
                                                                                    p2 = p8;
                                                                                }
                                                                            }
                                                                        }
                                                                    } else {
                                                                        if ((i76 > p8)) {
                                                                            p8 = i76;
                                                                        } else {
                                                                            p2 = i76;
                                                                        }
                                                                        p1 = p8;
                                                                    }
                                                                } else {
                                                                    p5 = p8;
                                                                }
                                                            } else {
                                                                p2 = i76;
                                                                p2 = i76;
                                                            }
                                                            if ((p5 >= p1)) {
                                                                if ((p5 != p8)) {
                                                                    if ((p8 <= p1)) {
                                                                        p1 = p2;
                                                                    } else {
                                                                        if ((98 == p8)) {
                                                                            if ((p5 > i76)) {
                                                                                p2 = -70;
                                                                            } else {
                                                                                p5 = p5;
                                                                                if ((79 < p8)) {
                                                                                    p8 = p8;
                                                                                    p1 = p8;
                                                                                } else {
                                                                                    if ((p2 < p5)) {
                                                                                        p1 = -78;
                                                                                        p8 = p8;
                                                                                    } else {
                                                                                        p8 = p2;
                                                                                        p5 = i76;
                                                                                    }
                                                                                    p1 = i76;
                                                                                }
                                                                            }
                                                                            if ((p1 >= p2)) {
                                                                                if ((93 < -37)) {
                                                                                    p1 = p5;
                                                                                    if ((p1 > p8)) {
                                                                                        if ((70 > p8)) {
                                                                                            p8 = i76;
                                                                                            p5 = p1;
                                                                                        } else {
                                                                                            if ((p2 == p8)) {
                                                                                                p8 = p2;
                                                                                                p2 = p5;
                                                                                            } else {
                                                                                                p1 = p8;
                                                                                                if ((-34 > p2)) {
                                                                                                    p1 = p1;
                                                                                                } else {
                                                                                                    p1 = i76;
                                                                                                }
                                                                                            }
                                                                                            p8 = p2;
                                                                                        }
                                                                                        p1 = p8;
                                                                                    } else {
                                                                                        if ((-1 != p8)) {
                                                                                            p2 = 46;
                                                                                            p5 = p1;
                                                                                        } else {
                                                                                            if ((p8 == p2)) {
                                                                                                p1 = -97;
                                                                                                p1 = 92;
                                                                                            } else {
                                                                                                if ((p1 == p8)) {
                                                                                                    p2 = -46;
                                                                                                    p8 = p2;
                                                                                                } else {
                                                                                                    p8 = i76;
                                                                                                    p5 = i76;
                                                                                                }
                                                                                                if ((p8 > p8)) {
                                                                                                    p8 = p1;
                                                                                                } else {
                                                                                                    p1 = 47;
                                                                                                    p8 = i76;
                                                                                                }
                                                                                            }
                                                                                            p2 = p8;
                                                                                        }
                                                                                        p8 = p5;
                                                                                    }
                                                                                } else {
                                                                                    p8 = -71;
                                                                                }
                                                                            } else {
                                                                                p8 = p2;
                                                                            }
                                                                        } else {
                                                                            if ((43 != 23)) {
                                                                                p2 = -23;
                                                                                p8 = -39;
                                                                            } else {
                                                                                p8 = i76;
                                                                            }
                                                                        }
                                                                    }
                                                                } else {
                                                                    if ((p1 < p8)) {
                                                                        p8 = p5;
                                                                    } else {
                                                                        p2 = 4;
                                                                        p5 = p1;
                                                                    }
                                                                }
                                                                p2 = p8;
                                                            } else {
                                                                p1 = p8;
                                                                if ((p5 <= p5)) {
                                                                    if ((p2 != p8)) {
                                                                        if ((i76 <= -25)) {
                                                                            p1 = p5;
                                                                            if ((p8 >= p1)) {
                                                                                p8 = -39;
                                                                            } else {
                                                                                p5 = p8;
                                                                            }
                                                                        } else {
                                                                            if ((p2 == 97)) {
                                                                                if ((p8 < 98)) {
                                                                                    if ((p1 == p5)) {
                                                                                        p5 = p1;
                                                                                        p2 = 82;
                                                                                    } else {
                                                                                        p5 = p5;
                                                                                        p1 = -57;
                                                                                    }
                                                                                } else {
                                                                                    p1 = -29;
                                                                                    p5 = p2;
                                                                                }
                                                                            } else {
                                                                                p8 = -56;
                                                                                p2 = p1;
                                                                            }
                                                                        }
                                                                    } else {
                                                                        if ((p5 >= 5)) {
                                                                            if ((p5 != i76)) {
                                                                                if ((p5 <= p1)) {
                                                                                    if ((p8 > p1)) {
                                                                                        p8 = 2;
                                                                                    } else {
                                                                                        p5 = p5;
                                                                                    }
                                                                                } else {
                                                                                    p2 = -67;
                                                                                }
                                                                            } else {
                                                                                p2 = i76;
                                                                                p5 = 8;
                                                                            }
                                                                        } else {
                                                                            p1 = p8;
                                                                            p2 = p1;
                                                                        }
                                                                        p1 = p1;
                                                                    }
                                                                } else {
                                                                    p2 = i76;
                                                                }
                                                            }
                                                        }
                                                        p8 = i76;
                                                    } else {
                                                        if ((p5 == p1)) {
                                                            p1 = p5;
                                                        } else {
                                                            p5 = -54;
                                                            if ((i76 != p8)) {
                                                                p2 = p1;
                                                            } else {
                                                                p5 = 47;
                                                            }
                                                        }
                                                    }
                                                } else {
                                                    p5 = 80;
                                                }
                                            }
                                        } else {
                                            p8 = 94;
                                            if ((p5 >= i76)) {
                                                p5 = i76;
                                            } else {
                                                if ((p8 == p1)) {
                                                    p5 = i76;
                                                    p1 = i76;
                                                } else {
                                                    p2 = 90;
                                                }
                                                if ((i76 == p2)) {
                                                    p1 = p2;
                                                    if ((p5 < 8)) {
                                                        p5 = i76;
                                                    } else {
                                                        p5 = 5;
                                                    }
                                                } else {
                                                    p1 = p2;
                                                    p8 = -57;
                                                }
                                            }
                                        }
                                    }
                                } else {
                                    p5 = p8;
                                }
                            }
                            p5 = p2;
                        } else {
                            for (int i94 = 0; i94 < 1; i94++) {
                                p1 = p8;
                            }
                        }
                    }
                }
                for (int i46 = 0; i46 < 6; i46++) {
                    p1 = 19;
                    if ((-40 == p5)) {
                        if ((i46 == -20)) {
                            p1 = p5;
                            if ((p2 > i46)) {
                                p8 = 63;
                                p5 = p5;
                            } else {
                                p2 = 80;
                                p2 = p5;
                            }
                        } else {
                            p5 = i46;
                            p5 = p2;
                        }
                        p8 = -59;
                    } else {
                        p5 = p8;
                        p5 = 89;
                    }
                }
            } else {
                p1 = p2;
            }
        } else {
            for (int i15 = 0; i15 < 1; i15++) {
                p8 = -30;
                if ((p2 <= p5)) {
                    if ((i15 == p8)) {
                        p8 = -3;
                        p5 = i15;
                    } else {
                        if ((p8 == p5)) {
                            p8 = i15;
                            if ((i15 >= -47)) {
                                p2 = p5;
                                p5 = 46;
                            } else {
                                if ((p1 <= 6)) {
                                    p2 = p1;
                                } else {
                                    p2 = p2;
                                }
                                p2 = 55;
                            }
                        } else {
                            p1 = p1;
                            p2 = -78;
                        }
                        p1 = p2;
                    }
                    p5 = p5;
                } else {
                    p8 = -14;
                    if ((i15 >= p8)) {
                        p5 = p8;
                    } else {
                        p1 = p2;
                        p2 = 38;
                    }
                }
            }
        }
        if ((p5 == p1)) {
            p5 = p8;
            p8 = 4;
        } else {
            p1 = 40;
            p8 = p5;
        }
    } else {
        p8 = ((p2 & 255) << 0);
        if ((p1 > p5)) {
            p5 = p2;
        } else {
            p8 = p5;
            if ((-95 != p1)) {
                for (int i8 = 0; i8 < 3; i8++) {
                    p1 = p8;
                    p2 = i8;
                    p1 = p5;
                }
                for (int i26 = 0; i26 < 2; i26++) {
                    p5 = p2;
                }
            } else {
                p8 = p8;
                if ((p8 == p2)) {
                    p5 = p8;
                    p2 = -98;
                } else {
                    p2 = p2;
                    p2 = 9;
                }
            }
        }
    }
    if ((83 <= 83)) {
        p5 = (p5 * p1);
    } else {
        for (int i58 = 0; i58 < 6; i58++) {
            if ((p1 != 69)) {
                p2 = p2;
                p8 = -3;
            } else {
                p2 = 75;
            }
            p1 = i58;
        }
    }
    return p6;
}

int f2(int p0, double p1, double p2, double p3, int p4, int p5, double p6, double p7, double p8, double p9, double p10, double p11) {
    p5 = (((p0 + -92) & 255) >> 1);
    for (int i16 = 0; i16 < 2; i16++) {
        p5 = ((p0 & 1023) & 651);
        if ((p5 == -18)) {
            p5 = p5;
        } else {
            p0 = p0;
        }
        p5 = ((p5 & 255) >> 1);
    }
    return p4;
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 30;
    int v1 = -46;
    int v2 = -12;
    int v3 = -26;
    int v4 = -34;
    int v5 = 40;
    int v6 = -16;
    int v7 = 47;
    int v8 = -5;
    int v9 = 28;
    int v10 = -44;
    int v11 = -36;
    int v12 = 18;
    int v13 = 13;
    int v14 = -16;
    int v15 = -1;
    double d0 = -7.0;
    double d1 = 29.0;
    double d2 = -10.0;
    double d3 = 25.0;
    double d4 = 13.0;
    double d5 = -22.0;
    double d6 = -16.0;
    double d7 = -28.0;
    double d8 = 10.0;
    double d9 = 9.0;
    double d10 = -13.0;
    double d11 = -24.0;
    arr[(-13) & 7] = v10;
    arr[((-63 * -23)) & 7] = 19;
    v14 = ((((((v15 & 255) >> 0) & 255) >> 3) & 1023) | 937);
    v9 = f2(v15, (d6 - d8), (-13 & 63), d0, v10, (v15 + 40), (d0 * d1), d2, d3, (d1 + d8), -33.0, (35.0 * d11));
    d0 = (d0 + d4);
    d1 = (d1 + (d7 * d8));
    d2 = (d2 + (-4.0 * d1));
    d3 = (d3 + ((-61 / -6) & 63));
    d4 = (d4 + d0);
    d5 = (d5 + (d0 * d10));
    d6 = (d6 + d8);
    d7 = (d7 + (-10.0 + d0));
    d8 = (d8 + (34.0 * -4.0));
    d9 = (d9 + (38.0 * d8));
    d10 = (d10 + (d9 + d11));
    d11 = (d11 + -18.0);
    if ((((((27 & 1023) ^ 392) & 1023) | 153) > (((v7 & 255) >> 1) % 7))) {
        v6 = arr[(((v10 & 255) >> 0)) & 7];
    } else {
        v1 = ((84 & 1023) | 180);
    }
    v10 = (((v4 + (v4 % -3)) & 1023) ^ 528);
    d5 = f1((22.0 + d3), v9, 82, (d8 + d4), d10, (v10 / 4), (d7 - d5), ((v2 % 7) & 63), (v2 - 33));
    d2 = f1((v15 & 63), (v11 / 16), (v9 - v9), (d9 - d2), (d10 - d3), ((-74 & 1023) | 983), (d1 + d2), (-40.0 + d9), ((v8 & 255) << 2));
    d0 = (d0 + (d3 * d9));
    d1 = (d1 + (d11 + d8));
    d2 = (d2 + (((v5 & 255) >> 3) & 63));
    d3 = (d3 + (d6 * d7));
    d4 = (d4 + (d8 * d4));
    d5 = (d5 + (d5 - 20.0));
    d6 = (d6 + d8);
    d7 = (d7 + (d2 - d7));
    d8 = (d8 + (v0 & 63));
    d9 = (d9 + (d11 - d9));
    d10 = (d10 + ((v12 + v4) & 63));
    d11 = (d11 + (v2 & 63));
    v4 = ((((v0 & 1023) | 946) & 255) << 1);
    d3 = f0(((v2 & 1023) ^ 346), -17, (d4 + d11), d7, d4, -23, (d1 * d9), (v11 - v10), (v14 + v12), (v12 + v14));
    d0 = (d0 + d11);
    d1 = (d1 + (31.0 - d6));
    d2 = (d2 + (d9 + d3));
    d3 = (d3 + d11);
    d4 = (d4 + -2.0);
    d5 = (d5 + (d11 * d11));
    d6 = (d6 + d2);
    d7 = (d7 + (d9 * 31.0));
    d8 = (d8 + (17 & 63));
    d9 = (d9 + (d10 * d3));
    d10 = (d10 + d11);
    d11 = (d11 + (d4 * d7));
    v2 = -60;
    v13 = ((v6 % -3) + ((71 / 3) + (62 - v1)));
    if (((((-98 + v8) & 1023) | 323) != (v5 % 2))) {
        v3 = -69;
    } else {
        v3 = v1;
    }
    d1 = f0((v13 * -63), (v9 - v5), (((v5 & 1023) & 572) & 63), (d4 * d3), (d3 - d2), -69, (d7 + d3), (-86 % 16), v3, ((v15 & 1023) ^ 864));
    v12 = f2(13, d1, (d11 * d5), 11.0, -51, v15, -18.0, (d5 * 0.0), d6, (-36.0 + d6), d8, (d9 - d6));
    d0 = (d0 + -40.0);
    d1 = (d1 + (d3 + d9));
    d2 = (d2 + d11);
    d3 = (d3 + (((-80 & 1023) ^ 134) & 63));
    d4 = (d4 + (d7 + 34.0));
    d5 = (d5 + (d10 - -30.0));
    d6 = (d6 + d6);
    d7 = (d7 + (d5 - d11));
    d8 = (d8 + (v10 & 63));
    d9 = (d9 + (d3 - d5));
    d10 = (d10 + (d2 - d6));
    d11 = (d11 + d10);
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != 26318769.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
