#!/usr/bin/env python3
"""Enumerate the SysV argument-passing surface instead of sampling it.

`gen_c.py` samples this space and cannot close it: it emits 7-12 parameter
functions at random and had never once produced an odd number of *stack*
arguments underneath a libc call, which is how a stack-misalignment segfault
survived a corpus of 400 seeds a shape. The space is finite, so it gets walked:

    parameter count 0..16  x  {int, double, mixed}  x  {leaf, calls libc}

Each axis earns its place.

*Count* decides how many arguments land on the stack, and the parity of that
number is what the segfault turned on -- SysV wants ``RSP % 16 == 0`` at a
``call`` and one ``push`` per stack argument leaves an odd count eight out. Pure
integers spill from 7 parameters, pure doubles from 9, and interleaved from 13,
because the two register files are counted separately; 0..16 reaches both
parities of stack count in all three.

*Type* decides which file an argument comes from, and interleaving is not the
same test as either pure form: a mixed signature consumes GPRs and SSE registers
at different rates, so it puts an integer on the stack while SSE registers are
still free.

*Leaf or caller* decides whether the callee's own frame has to be aligned, and
the caller variant makes its libc call **before** it checks its parameters. A
parameter in a caller-saved register that the callee does not preserve is
therefore a wrong value here rather than nowhere -- callee-saved preservation is
the one register property `verify.rs` says it does not check.

Every program is trivially free of undefined behavior: the arguments are
constants, the doubles hold integral values compared for equality, and nothing
is read before it is written.

**A failing program names the parameter.** The callee returns the 1-based index
of the first argument that did not arrive, main prints that, and the predicted
output is 0. So `printed 7, generator predicted 0` says argument 7, with no
second run and no probe.

Usage:
    python3 gen_abi.py --out-dir DIR [--max-params N] [--only STEM]

Prints one generated filename per line, in enumeration order.
"""

import argparse
import os

# Distinct, nonzero, and exactly representable. Distinct so a permutation of the
# arguments cannot go unnoticed; nonzero so a register nothing wrote cannot pass
# by holding a lucky zero; integral so `!=` on a double is exact and no reference
# compiler is entitled to a second answer.
def int_value(i):
    return 1000 + 7 * i


def dbl_value(i):
    v = 100 + 3 * i
    return -v if i % 2 else v


KINDS = ("int", "double", "mixed")
VARIANTS = ("leaf", "call")


def param_types(kind, n):
    if kind == "int":
        return ["int"] * n
    if kind == "double":
        return ["double"] * n
    return ["int" if i % 2 == 0 else "double" for i in range(n)]


def literal(ty, i):
    return f"{int_value(i)}" if ty == "int" else f"{float(dbl_value(i)):.1f}"


def program(kind, n, variant):
    tys = param_types(kind, n)
    params = ", ".join(f"{ty} p{i}" for i, ty in enumerate(tys))
    args = ", ".join(literal(ty, i) for i, ty in enumerate(tys))

    out = ["0"] if variant == "leaf" else [str(n), "0"]
    lines = ["// EXIT: 0"]
    lines += [f"// OUTPUT: {o}" for o in out]
    lines += [
        "// GENERATED by tests/fuzz/gen_abi.py -- do not edit by hand.",
        "//",
        f"// {n} {kind} parameter(s), callee {'calls printf' if variant == 'call' else 'is a leaf'}.",
        "// The callee returns the 1-based index of the first argument that did",
        "// not arrive intact, so a failure names the argument.",
        "//",
        "// Free of undefined behavior by construction: every argument is a",
        "// constant, the doubles hold integral values, and nothing is read",
        "// before it is written.",
        "",
        "extern int printf(char* fmt, ...);",
        "",
        # Without noinline, -O1 inlines the callee and the calling convention is
        # never exercised -- the whole enumeration would pass on a broken ABI.
        f"__attribute__((noinline)) int callee({params}) {{",
    ]
    if variant == "call":
        # Before the checks, not after: the call clobbers every caller-saved
        # register, so a parameter the callee failed to preserve across it is
        # caught here.
        lines.append(f'    printf("%d\\n", {n});')
    for i, ty in enumerate(tys):
        lines.append(f"    if (p{i} != {literal(ty, i)}) {{ return {i + 1}; }}")
    lines += [
        "    return 0;",
        "}",
        "",
        "int main() {",
        f"    int r = callee({args});",
        '    printf("%d\\n", r);',
        "    return 0;",
        "}",
    ]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", required=True)
    ap.add_argument(
        "--max-params",
        type=int,
        default=16,
        help="highest parameter count to emit (default 16, which reaches both "
        "parities of stack-argument count in all three type kinds)",
    )
    ap.add_argument("--only", help="emit just this stem, e.g. abi_n07_int_call")
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    for n in range(args.max_params + 1):
        for kind in KINDS:
            # A mixed signature needs one of each to be mixed at all.
            if kind == "mixed" and n < 2:
                continue
            for variant in VARIANTS:
                stem = f"abi_n{n:02d}_{kind}_{variant}"
                if args.only and stem != args.only:
                    continue
                path = os.path.join(args.out_dir, stem + ".c")
                with open(path, "w") as f:
                    f.write(program(kind, n, variant))
                print(stem)


if __name__ == "__main__":
    main()
