// Regression test: a cross-block-spilled address must be read from its reload.
//
// Found by tests/fuzz/gen_c.py (seed 5, --size small) on its first run, and
// fixed. It used to print 610 at -O1 and SIGSEGV at -O0, against 606 from the
// generator's own interpreter, gcc -O0 and clang -O0.
//
// The eight `&arr[i]` addresses are computed in the entry block and consumed in
// the printf block, so pressure makes the splitter spill four of them across
// the block boundary. Lowering resolves a Load's address through a ClassId --
// there is no VReg operand for an operand rewrite to reach -- against a
// per-block snapshot of the class map taken during linearization, before the
// splitter existed. With the reload segments missing from that snapshot the
// address resolved to the register it occupied *before* the spill:
//
//   mov  rax,QWORD PTR [rsp+0x30]   ; the reload, into RAX
//   mov  ecx,DWORD PTR [rcx]        ; the load, reading RCX
//
// The fix propagates the splitter's committed segments onto every snapshot, in
// final schedule coordinates. See `split::AppliedSplits`.
//
// The program is free of undefined behavior by construction, so all three
// oracles agreeing on 606 made this a blitz bug rather than a program that was
// entitled to more than one answer.
//
// Regenerate with:
//   python3 tests/fuzz/gen_c.py --seed 5 --size small --out /tmp/s5.c
//
// OUTPUT: 606
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

double f0(int p0, int p1, int p2, int p3, int p4, double p5, int p6) {
    p0 = p6;
    return ((40.0 - p5) + (-51 & 63));
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 33;
    int v1 = -22;
    int v2 = 49;
    int v3 = -31;
    double d0 = -29.0;
    double d1 = 18.0;
    double d2 = 8.0;
    v2 = (((v3 / 3) & 1023) & 606);
    d0 = f0(((16 & 255) >> 4), v1, (7 * v0), ((v3 & 1023) | 795), (-87 - 96), (d2 + d0), (v1 / 11));
    d0 = (d0 + d1);
    d1 = (d1 + (d2 - 6.0));
    d2 = (d2 + d0);
    if (((d0 + d1) + d2) != 212.0) { return 3; }
    printf("%d\n", (((((((((((v0 + v1) + v2) + v3) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
