// Regression test: a float sum that the program's own guard rejected, printing 167
// at both levels.
//
// Was KNOWN FAILING -- blitz exited 3 at -O0, the guard's own verdict on a wrong
// sum, and could not allocate at all at -O1 -- against 167 from cc at -O0 and -O2.
// Correct at both levels since the block-parameter slot routing and the
// phi-destination fix landed.
//
// tests/fuzz/gen_c.py seed 23, shape mixed, saved verbatim: the generator was
// fixed after this (loop counters are no longer assignment targets), so the same
// seed no longer produces this program.
//
// EXIT: 0
// OUTPUT: 167
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(int p0, int p1, double p2, int p3, double p4, double p5, int p6, int p7) {
    if (((-4 / 2) <= -23)) {
        for (int i3 = 0; i3 < 5; i3++) {
            if ((i3 <= i3)) {
                p0 = p1;
            } else {
                p0 = p3;
            }
            if ((p0 < p0)) {
                if ((p0 < i3)) {
                    if ((i3 >= i3)) {
                        p6 = -44;
                        if ((p1 != 45)) {
                            p3 = p7;
                        } else {
                            if ((-51 < p7)) {
                                p6 = p1;
                            } else {
                                if ((i3 > 45)) {
                                    p3 = p3;
                                    p7 = -49;
                                } else {
                                    p7 = p6;
                                }
                            }
                        }
                    } else {
                        if ((58 < i3)) {
                            p3 = p3;
                        } else {
                            p3 = -9;
                            if ((p3 >= p6)) {
                                p3 = -82;
                                p1 = i3;
                            } else {
                                p1 = i3;
                                p3 = p3;
                            }
                        }
                        p1 = i3;
                    }
                    p0 = -48;
                } else {
                    p1 = p7;
                    p6 = -15;
                }
                p1 = p3;
            } else {
                p6 = p1;
            }
            p3 = p7;
        }
    } else {
        for (int i52 = 0; i52 < 3; i52++) {
            if ((i52 > p1)) {
                i52 = p0;
            } else {
                p0 = p0;
            }
            if ((i52 != -87)) {
                p0 = p0;
                if ((p0 <= p0)) {
                    p0 = p0;
                } else {
                    if ((p1 >= i52)) {
                        p0 = 5;
                        i52 = -22;
                    } else {
                        p0 = i52;
                    }
                    i52 = p6;
                }
            } else {
                p1 = p7;
            }
            if ((p1 < p1)) {
                p3 = 2;
            } else {
                if ((p3 >= p1)) {
                    if ((26 == 62)) {
                        p3 = 42;
                    } else {
                        if ((p7 != 95)) {
                            p7 = p0;
                            i52 = p7;
                        } else {
                            p6 = p3;
                            p0 = -86;
                        }
                    }
                } else {
                    if ((p6 >= p6)) {
                        p7 = p7;
                        p7 = p1;
                    } else {
                        if ((p1 >= p6)) {
                            p1 = i52;
                        } else {
                            if ((p6 <= i52)) {
                                p3 = -52;
                                p6 = p6;
                            } else {
                                p1 = p7;
                            }
                        }
                        if ((p1 == i52)) {
                            if ((-72 > p1)) {
                                if ((p7 < -35)) {
                                    if ((p6 > p0)) {
                                        p3 = p0;
                                        if ((70 >= p3)) {
                                            i52 = -79;
                                            p6 = 25;
                                        } else {
                                            i52 = p1;
                                            p6 = -83;
                                        }
                                    } else {
                                        p6 = p1;
                                    }
                                    p1 = p3;
                                } else {
                                    p3 = p0;
                                }
                            } else {
                                i52 = p3;
                                i52 = p0;
                            }
                            i52 = p6;
                        } else {
                            p3 = p0;
                            p1 = p7;
                        }
                    }
                    p7 = i52;
                }
            }
        }
    }
    for (int i69 = 0; i69 < 4; i69++) {
        p7 = p3;
        p3 = (-91 - 98);
        i69 = (-95 - p7);
    }
    return ((((p3 & 255) >> 0) & 255) >> 3);
}

double f1(int p0, double p1, double p2, int p3, double p4, double p5, int p6, double p7, int p8) {
    if ((p6 != ((-96 & 255) << 3))) {
        if ((p3 != p6)) {
            p6 = p8;
            if ((62 >= p0)) {
                p8 = 47;
                if ((43 != -46)) {
                    p0 = 73;
                    for (int i54 = 0; i54 < 3; i54++) {
                        if ((p0 > p8)) {
                            if ((p3 >= i54)) {
                                p0 = i54;
                            } else {
                                p3 = 60;
                            }
                        } else {
                            p3 = p0;
                        }
                        p6 = p8;
                    }
                } else {
                    if ((44 == p3)) {
                        for (int i9 = 0; i9 < 2; i9++) {
                            p8 = i9;
                            p6 = -83;
                            if ((p0 < -18)) {
                                p6 = 9;
                                i9 = p6;
                            } else {
                                if ((p0 >= -25)) {
                                    i9 = p6;
                                    p6 = p3;
                                } else {
                                    if ((p6 >= 79)) {
                                        p8 = p3;
                                        p8 = p8;
                                    } else {
                                        i9 = p3;
                                        if ((i9 != p6)) {
                                            if ((p8 != p0)) {
                                                p0 = p0;
                                                i9 = p8;
                                            } else {
                                                p0 = p8;
                                                i9 = -42;
                                            }
                                        } else {
                                            if ((7 <= 46)) {
                                                if ((p8 >= i9)) {
                                                    if ((p8 < 55)) {
                                                        if ((-67 >= i9)) {
                                                            i9 = p6;
                                                            p8 = -83;
                                                        } else {
                                                            p3 = -88;
                                                            p3 = p8;
                                                        }
                                                        p6 = p8;
                                                    } else {
                                                        i9 = p8;
                                                        if ((p8 > -56)) {
                                                            p8 = p3;
                                                        } else {
                                                            p8 = p3;
                                                            if ((p6 == 81)) {
                                                                if ((p3 == p6)) {
                                                                    if ((p6 != p0)) {
                                                                        if ((i9 != 5)) {
                                                                            p8 = p0;
                                                                        } else {
                                                                            p0 = 92;
                                                                        }
                                                                        p0 = i9;
                                                                    } else {
                                                                        p3 = -97;
                                                                        if ((p0 == p8)) {
                                                                            p3 = p0;
                                                                            if ((p0 != 27)) {
                                                                                p0 = p3;
                                                                                p0 = 16;
                                                                            } else {
                                                                                i9 = 73;
                                                                            }
                                                                        } else {
                                                                            if ((p0 != 91)) {
                                                                                p8 = 21;
                                                                            } else {
                                                                                p0 = p0;
                                                                                p3 = p3;
                                                                            }
                                                                        }
                                                                    }
                                                                } else {
                                                                    p3 = p6;
                                                                }
                                                                p3 = p3;
                                                            } else {
                                                                p6 = p0;
                                                                if ((i9 == p3)) {
                                                                    i9 = 44;
                                                                    p8 = 63;
                                                                } else {
                                                                    p6 = p0;
                                                                }
                                                            }
                                                        }
                                                    }
                                                    p6 = 81;
                                                } else {
                                                    p3 = p3;
                                                    if ((i9 >= p0)) {
                                                        p0 = p6;
                                                    } else {
                                                        p3 = i9;
                                                    }
                                                }
                                            } else {
                                                p8 = p3;
                                                if ((i9 >= p3)) {
                                                    if ((74 > p6)) {
                                                        i9 = i9;
                                                    } else {
                                                        p3 = i9;
                                                        i9 = 2;
                                                    }
                                                    p8 = 62;
                                                } else {
                                                    if ((p8 <= -43)) {
                                                        if ((p3 > p6)) {
                                                            p0 = 62;
                                                        } else {
                                                            if ((0 > i9)) {
                                                                p6 = p8;
                                                            } else {
                                                                p0 = p0;
                                                            }
                                                            p3 = 42;
                                                        }
                                                        p6 = p8;
                                                    } else {
                                                        if ((i9 == 88)) {
                                                            if ((i9 != p6)) {
                                                                p8 = p0;
                                                                i9 = p3;
                                                            } else {
                                                                if ((-6 != i9)) {
                                                                    if ((p0 != 60)) {
                                                                        if ((p8 <= p6)) {
                                                                            i9 = p0;
                                                                        } else {
                                                                            if ((3 == p3)) {
                                                                                p6 = p6;
                                                                                p3 = i9;
                                                                            } else {
                                                                                i9 = p0;
                                                                            }
                                                                            p8 = i9;
                                                                        }
                                                                    } else {
                                                                        i9 = p0;
                                                                    }
                                                                    i9 = p3;
                                                                } else {
                                                                    p0 = p3;
                                                                }
                                                                p0 = p6;
                                                            }
                                                        } else {
                                                            i9 = 30;
                                                        }
                                                    }
                                                    p3 = i9;
                                                }
                                            }
                                            p8 = p0;
                                        }
                                    }
                                    if ((48 > p8)) {
                                        p6 = i9;
                                        if ((13 <= -12)) {
                                            p6 = p6;
                                            p8 = -6;
                                        } else {
                                            if ((25 > p0)) {
                                                if ((p8 == 34)) {
                                                    if ((p0 <= p6)) {
                                                        i9 = i9;
                                                    } else {
                                                        p8 = p0;
                                                    }
                                                    p0 = p8;
                                                } else {
                                                    i9 = -98;
                                                }
                                            } else {
                                                p6 = p6;
                                                p3 = -3;
                                            }
                                            if ((80 != p6)) {
                                                p3 = 67;
                                            } else {
                                                i9 = p6;
                                                p6 = i9;
                                            }
                                        }
                                    } else {
                                        p0 = i9;
                                    }
                                }
                                p0 = p8;
                            }
                        }
                        p6 = p8;
                    } else {
                        if ((-55 >= p6)) {
                            p3 = 48;
                            p8 = p3;
                        } else {
                            p0 = p8;
                        }
                    }
                }
            } else {
                p6 = p3;
                if ((p0 >= 74)) {
                    p0 = p6;
                    if ((p6 != p6)) {
                        p0 = p6;
                    } else {
                        for (int i41 = 0; i41 < 6; i41++) {
                            i41 = -98;
                        }
                        p6 = p3;
                    }
                } else {
                    if ((59 > p8)) {
                        for (int i81 = 0; i81 < 3; i81++) {
                            i81 = 74;
                            if ((p8 >= p3)) {
                                if ((-43 != -94)) {
                                    p8 = p3;
                                } else {
                                    if ((p3 > -35)) {
                                        if ((i81 == p6)) {
                                            if ((-27 != p6)) {
                                                p0 = p8;
                                                if ((p3 < i81)) {
                                                    p3 = p3;
                                                } else {
                                                    if ((p6 == p6)) {
                                                        p0 = -68;
                                                    } else {
                                                        i81 = p6;
                                                    }
                                                    if ((p8 <= 15)) {
                                                        p3 = 58;
                                                        p0 = i81;
                                                    } else {
                                                        p6 = -60;
                                                        p3 = p3;
                                                    }
                                                }
                                            } else {
                                                if ((i81 >= p0)) {
                                                    if ((100 != p0)) {
                                                        if ((p3 > p0)) {
                                                            if ((i81 != p3)) {
                                                                i81 = p6;
                                                            } else {
                                                                p8 = p6;
                                                                i81 = p8;
                                                            }
                                                            if ((-77 != p6)) {
                                                                p0 = p3;
                                                                p0 = p6;
                                                            } else {
                                                                p8 = p8;
                                                            }
                                                        } else {
                                                            if ((p0 < -48)) {
                                                                p6 = i81;
                                                            } else {
                                                                p3 = p3;
                                                            }
                                                        }
                                                    } else {
                                                        p3 = p0;
                                                    }
                                                    i81 = p8;
                                                } else {
                                                    p3 = p3;
                                                    p6 = 54;
                                                }
                                            }
                                            p6 = -43;
                                        } else {
                                            p6 = p6;
                                        }
                                        if ((23 < p3)) {
                                            p6 = i81;
                                            p0 = p3;
                                        } else {
                                            p3 = p8;
                                        }
                                    } else {
                                        if ((-80 != p0)) {
                                            i81 = p8;
                                            p3 = 73;
                                        } else {
                                            p3 = i81;
                                            p3 = p6;
                                        }
                                        p8 = i81;
                                    }
                                }
                            } else {
                                p6 = p6;
                                p6 = 48;
                            }
                            i81 = -1;
                        }
                        p3 = -18;
                    } else {
                        p0 = p6;
                    }
                }
            }
        } else {
            p8 = 54;
        }
    } else {
        if ((p3 >= p8)) {
            p0 = 44;
            p6 = p0;
        } else {
            for (int i44 = 0; i44 < 5; i44++) {
                p0 = p0;
                i44 = p3;
            }
        }
        for (int i39 = 0; i39 < 1; i39++) {
            p6 = -62;
            if ((p6 <= p3)) {
                p8 = -44;
            } else {
                p8 = p3;
                i39 = 42;
            }
            i39 = i39;
        }
    }
    for (int i88 = 0; i88 < 5; i88++) {
        p3 = (-36 - p8);
    }
    for (int i38 = 0; i38 < 6; i38++) {
        p6 = ((p3 & 1023) ^ 698);
        p6 = i38;
    }
    return p4;
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 31;
    int v1 = -4;
    int v2 = -2;
    int v3 = -27;
    int v4 = 38;
    int v5 = -39;
    int v6 = 19;
    int v7 = 38;
    int v8 = -9;
    int v9 = 3;
    double d0 = 23.0;
    double d1 = 1.0;
    double d2 = -16.0;
    double d3 = 20.0;
    double d4 = 4.0;
    double d5 = -4.0;
    for (int i45 = 0; i45 < 3; i45++) {
        v0 = ((-65 & 255) << 3);
    }
    v0 = ((((((v9 & 255) >> 3) & 1023) | 168) & 255) >> 1);
    v6 = f0(-20, ((v6 & 1023) ^ 89), (d2 + 10.0), (v0 / -6), (25.0 - -39.0), d5, ((v8 & 1023) & 222), ((35 & 1023) | 547));
    d2 = f1((v3 / -6), (d4 + d4), (d0 * d0), ((1 & 255) >> 3), (d1 * -39.0), (d0 * d2), (v0 * v6), ((v0 * v3) & 63), ((v4 & 1023) | 206));
    d0 = (d0 + (v7 & 63));
    d1 = (d1 + d3);
    d2 = (d2 + 22.0);
    d3 = (d3 + (d4 * d0));
    d4 = (d4 + (((v5 & 1023) | 151) & 63));
    d5 = (d5 + d3);
    for (int i19 = 0; i19 < 3; i19++) {
        if ((((10 & 255) << 2) != (42 / 7))) {
            arr[(-77) & 7] = arr[(v4) & 7];
        } else {
            arr[(v7) & 7] = (73 % 3);
            if ((v2 >= v5)) {
                v6 = -20;
            } else {
                arr[((i19 / 11)) & 7] = v8;
            }
        }
    }
    v3 = v1;
    v8 = f0(v1, ((v5 & 255) >> 1), (-12.0 * d3), (v8 / 5), d3, (d3 + d1), (v1 - v7), -32);
    d0 = (d0 + d1);
    d1 = (d1 + d5);
    d2 = (d2 + (((v6 & 255) >> 3) & 63));
    d3 = (d3 + d2);
    d4 = (d4 + (d4 * d2));
    d5 = (d5 + 1.0);
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != 331.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
