// Regression test: a `for (i = 0; i < 5; i++)` loop that never terminated.
//
// The splitter rematerialized a `BlockParam` pseudo-op. A BlockParam computes
// nothing -- it declares that the value is already in its register when the
// block starts, put there by a predecessor's phi copy -- so re-emitting it mints
// a VReg that no instruction ever writes, and the allocator hands it a register
// nothing initialises:
//
//   [ 0] v79  = BlockParam(1, 0, I32)      ; the loop counter, allocated RDX
//   [23] v372 = BlockParam(1, 0, I32)      ; remat of the same param, RAX
//   [24] v80  = X86CmpI { imm: 5 }([372])  ; the bound test reads RAX
//
// RAX happened to still hold the phi *source* from the forward edge's
// `mov edx,eax`, so the first iteration tested the right value. The latch
// incremented RDX and jumped back past that copy, leaving RAX at 0 forever:
//
//   mov  edx,ecx     ; i + 1, into the counter's register
//   jmp  <header>    ; lands after the copy that set RAX
//   cmp  eax,0x5     ; still 0
//
// The fix is that cheapness is not recomputability: choose_split_kind now asks
// Op::is_rematerializable, which admits only Iconst, Fconst, StackAddr and
// GlobalAddr. BlockParam, Param, CallResult and LoadResult are all leaves of
// cost ~0 and all name a value that exists at exactly one program point.
//
// tests/fuzz/gen_c.py seed 34 (post loop-counter fix), shape mixed, verbatim.
// cc -O0 and -O2 both print 2567. Pinned to -O0: blitz -O1 cannot allocate
// registers for this program (ROADMAP P0), a separate failure.
//
// FLAGS: -O0
// OUTPUT: 2567
// EXIT: 0
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

double f0(int p0, int p1, double p2, double p3, int p4, int p5, double p6) {
    p4 = (47 - 49);
    p0 = 46;
    return (p2 + (p2 + p3));
}

double f1(double p0, double p1, int p2, int p3, int p4, double p5, int p6, double p7, double p8, double p9) {
    for (int i96 = 0; i96 < 1; i96++) {
        p4 = p3;
        p6 = ((p4 & 1023) & 654);
    }
    p3 = p3;
    return ((-32.0 * p8) - (p0 * p7));
}

int f2(int p0, int p1, double p2, int p3, double p4, int p5, double p6, int p7, double p8, int p9) {
    p9 = (((p1 % 3) & 1023) | 259);
    return ((((-8 & 1023) ^ 95) & 1023) ^ 182);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 13;
    int v1 = -39;
    int v2 = 11;
    int v3 = -31;
    int v4 = -31;
    int v5 = 45;
    int v6 = 45;
    int v7 = -3;
    int v8 = 48;
    int v9 = -11;
    double d0 = 13.0;
    double d1 = 20.0;
    double d2 = -10.0;
    double d3 = -1.0;
    double d4 = -29.0;
    double d5 = 5.0;
    v2 = 100;
    d0 = f0(-28, ((v7 & 1023) ^ 87), (d0 + d1), (-68 & 63), ((v6 & 1023) & 750), ((v8 & 255) << 2), d1);
    v1 = f2(((65 & 1023) & 288), ((-97 & 255) >> 2), (d2 - d4), (66 - -99), (32.0 + 17.0), v0, (1.0 - d5), ((54 & 1023) | 127), (-20.0 - d5), 2);
    d0 = (d0 + d1);
    d1 = (d1 + d2);
    d2 = (d2 + (-18.0 + d1));
    d3 = (d3 + -15.0);
    d4 = (d4 + (((v8 & 255) << 2) & 63));
    d5 = (d5 + d2);
    for (int i42 = 0; i42 < 5; i42++) {
        v9 = v7;
        v2 = v8;
        v9 = ((((v3 & 255) << 0) & 255) >> 2);
    }
    v7 = f2(v9, v5, (d0 + d0), (v3 % 4), (d3 * d5), ((-21 & 1023) ^ 403), -1.0, ((87 & 1023) ^ 1019), ((69 - v9) & 63), 70);
    v3 = f2(((v5 & 255) << 1), (v7 + v2), 13.0, v2, (d2 + 0.0), (-40 / 3), (d3 + d5), -28, (-25.0 * d3), ((v1 & 1023) ^ 49));
    d0 = (d0 + (((v4 & 1023) ^ 991) & 63));
    d1 = (d1 + (v1 & 63));
    d2 = (d2 + (d4 + d0));
    d3 = (d3 + (d3 * d0));
    d4 = (d4 + (d1 + -18.0));
    d5 = (d5 + (d5 + -20.0));
    v9 = (((21 / 11) & 255) << 4);
    d4 = f1((d2 * d4), d1, ((97 & 1023) & 980), (-3 % 2), ((64 & 1023) | 284), d3, v0, (d3 - d5), (((v4 & 1023) | 601) & 63), (d1 - 4.0));
    d0 = (d0 + d1);
    d1 = (d1 + 26.0);
    d2 = (d2 + (d5 + d0));
    d3 = (d3 + (d5 * -13.0));
    d4 = (d4 + (d4 - d1));
    d5 = (d5 + d2);
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != -21244625.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
