// Regression test: a wide mixed-signature program under enough pressure to spill,
// printing 326 at both levels.
//
// Was KNOWN FAILING -- blitz printed -3233 at -O0 and could not allocate at all
// at -O1 -- against 326 from cc at -O0 and -O2. Correct at both levels since the
// block-parameter slot routing and the phi-destination fix landed.
//
// tests/fuzz/gen_c.py seed 12, shape mixed, saved verbatim: the generator was
// fixed after this (loop counters are no longer assignment targets), so the same
// seed no longer produces this program.
//
// EXIT: 0
// OUTPUT: 326
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, ...);

int f0(int p0, int p1, double p2, double p3, double p4, int p5, int p6, int p7, int p8, double p9, int p10, double p11) {
    if ((p6 > p5)) {
        p8 = ((p10 & 255) >> 0);
        if ((p10 < p10)) {
            if ((p0 < p7)) {
                if ((p10 != p1)) {
                    p0 = p7;
                } else {
                    p1 = p6;
                }
                p5 = p8;
            } else {
                p7 = p1;
            }
            p6 = p7;
        } else {
            for (int i14 = 0; i14 < 4; i14++) {
                p1 = p5;
                p8 = p8;
                p5 = i14;
            }
            if ((63 <= p0)) {
                p10 = p6;
            } else {
                for (int i98 = 0; i98 < 2; i98++) {
                    p8 = 83;
                    p10 = p6;
                }
            }
        }
    } else {
        if ((p5 != p5)) {
            p10 = -24;
        } else {
            if ((p1 == p0)) {
                p1 = -96;
            } else {
                if ((p0 <= -5)) {
                    p5 = -86;
                } else {
                    p0 = p8;
                }
            }
        }
        p5 = p1;
    }
    return ((((p7 & 1023) & 50) & 255) >> 2);
}

double f1(int p0, int p1, double p2, int p3, double p4, int p5, int p6, int p7, double p8, int p9) {
    if ((((32 & 1023) ^ 255) == ((p0 & 255) << 0))) {
        p7 = ((-12 & 1023) ^ 896);
        p1 = p0;
    } else {
        for (int i8 = 0; i8 < 4; i8++) {
            p5 = i8;
        }
        p1 = p3;
    }
    return p8;
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 0;
    int v1 = 0;
    int v2 = -49;
    int v3 = 37;
    int v4 = -19;
    int v5 = -47;
    int v6 = 37;
    int v7 = 48;
    int v8 = -12;
    int v9 = 15;
    double d0 = -3.0;
    double d1 = -27.0;
    double d2 = 11.0;
    double d3 = 22.0;
    double d4 = -29.0;
    double d5 = -19.0;
    v5 = v2;
    if (((((v6 / 5) & 255) >> 1) > ((v0 % 8) / 2))) {
        v8 = (((v5 & 255) >> 3) - (v0 * -42));
    } else {
        if (((v0 / -3) >= ((v2 & 1023) ^ 757))) {
            for (int i87 = 0; i87 < 4; i87++) {
                v5 = v6;
                v4 = i87;
            }
        } else {
            v4 = v4;
        }
        if ((v9 < v5)) {
            v6 = 36;
        } else {
            v5 = (v5 + v4);
            for (int i44 = 0; i44 < 1; i44++) {
                if ((v1 >= v5)) {
                    v6 = 71;
                } else {
                    if ((-30 < v4)) {
                        i44 = v9;
                        v5 = v7;
                    } else {
                        i44 = v7;
                        v2 = 36;
                    }
                }
                v1 = v2;
                if ((v7 >= v0)) {
                    v6 = v7;
                    v2 = v2;
                } else {
                    v0 = 66;
                    i44 = v2;
                }
            }
        }
    }
    d1 = f1(v9, v2, (((v6 & 1023) & 781) & 63), v3, (d0 - -7.0), -72, v8, v5, (-11.0 * d2), ((v4 & 1023) ^ 286));
    v1 = f0(v4, (v3 + v6), -12.0, d2, ((96 + v3) & 63), (v6 - -16), (-10 % 8), (v6 * -94), v0, d2, ((v7 & 1023) | 313), d2);
    d0 = (d0 + d3);
    d1 = (d1 + (d5 + -15.0));
    d2 = (d2 + (d2 - d1));
    d3 = (d3 + 19.0);
    d4 = (d4 + (d4 - -13.0));
    d5 = (d5 + (v6 & 63));
    v5 = ((((v5 & 255) >> 3) & 255) << 3);
    v9 = 21;
    if ((((((v3 & 255) << 4) & 255) << 1) != (((-57 / 5) & 1023) ^ 191))) {
        v6 = arr[(((50 & 255) << 0)) & 7];
    } else {
        if (((-54 * v1) == ((-19 & 1023) & 508))) {
            if ((-12 < v5)) {
                v6 = v9;
                v9 = v4;
            } else {
                v7 = v0;
            }
            for (int i5 = 0; i5 < 2; i5++) {
                v3 = -33;
                v9 = v7;
            }
        } else {
            arr[(((v0 & 255) >> 1)) & 7] = (v9 - v0);
            for (int i93 = 0; i93 < 2; i93++) {
                v1 = v8;
                v1 = 56;
                v7 = 55;
            }
        }
    }
    v9 = f0(-50, (79 * v2), d1, d4, d5, (-5 % 7), (v4 * v3), -59, ((v5 & 1023) & 984), (d5 * d3), (24 * v9), d1);
    v2 = f0((v3 * v7), (v4 % 11), d0, (((v7 & 1023) | 758) & 63), (((-84 & 255) >> 1) & 63), 5, v5, (v1 / 7), v1, d1, (-81 % 8), -33.0);
    d0 = (d0 + (d1 + d0));
    d1 = (d1 + (d4 * d0));
    d2 = (d2 + (d5 - 15.0));
    d3 = (d3 + (v7 & 63));
    d4 = (d4 + d3);
    d5 = (d5 + (d3 - d0));
    if ((((((d0 + d1) + d2) + d3) + d4) + d5) != 5530.0) { return 3; }
    printf("%d\n", (((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
