// Regression test: one slot per parameter group is right only when the group is
// one VALUE, and an e-class is one EXPRESSION. Two blocks whose parameters share
// a class and a VReg -- here blocks 42 and 43, parameter 0 of each -- hold
// different values at their own entries, so routing them through one cell made
// term 10 of the sum read -58, the value another term legitimately adds, where 0
// belongs: 1788 became 1730 at -O1 while -O0 stayed right.
//
// Slot routing refuses a group spanning more than one block for that reason.
// 158 lines, gen_c.py seed 14 shape pressure, unreduced.
// EXIT: 0
// OUTPUT: 1788
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

int f0(int p0, double p1, double p2, double p3, int p4, double p5, int p6, double p7) {
    p0 = p4;
    for (int i30 = 0; i30 < 2; i30++) {
        if ((i30 < i30)) {
            p4 = p4;
            p6 = i30;
        } else {
            if ((i30 < -65)) {
                p6 = i30;
            } else {
                p0 = p6;
                p0 = i30;
            }
        }
        p4 = ((p4 & 255) >> 3);
        if ((96 < p4)) {
            p0 = p6;
            p4 = i30;
        } else {
            p0 = p4;
        }
    }
    return ((25 * p0) / -6);
}

double f1(int p0, double p1, int p2, double p3, double p4, int p5, int p6, int p7, int p8, int p9, double p10) {
    p2 = ((((p8 & 255) >> 4) & 255) >> 1);
    p2 = (((p9 % 4) & 1023) ^ 22);
    p7 = (68 + (p8 + p8));
    return p1;
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 41;
    int v1 = 47;
    int v2 = -47;
    int v3 = 29;
    int v4 = 34;
    int v5 = 11;
    int v6 = 22;
    int v7 = -27;
    int v8 = -35;
    int v9 = 25;
    int v10 = 20;
    int v11 = 21;
    int v12 = 27;
    int v13 = 43;
    int v14 = 26;
    int v15 = -47;
    double d0 = -11.0;
    double d1 = 1.0;
    double d2 = -7.0;
    double d3 = 13.0;
    double d4 = -11.0;
    double d5 = 27.0;
    double d6 = 1.0;
    double d7 = 25.0;
    double d8 = 8.0;
    double d9 = 1.0;
    double d10 = 2.0;
    double d11 = 26.0;
    if ((v5 >= (((v14 / 3) & 1023) ^ 757))) {
        v0 = (27 / 11);
        for (int i64 = 0; i64 < 6; i64++) {
            v1 = arr[(70) & 7];
        }
    } else {
        arr[((v11 % 4)) & 7] = arr[((v8 * v5)) & 7];
    }
    d9 = f1(v9, (d1 - d4), v15, (d6 + -38.0), (d7 * -28.0), ((v2 & 1023) & 691), ((v7 & 1023) & 595), (v12 % 2), ((v12 & 255) >> 4), (v14 - v3), (d1 + d6));
    d6 = f1(((-82 & 255) << 4), (v10 & 63), v15, (d11 + d8), (d8 * -25.0), (v4 * v7), (-1 * v3), (30 - v2), (-58 % 5), v6, d8);
    d0 = (d0 + (7.0 * d8));
    d1 = (d1 + (-31.0 + -21.0));
    d2 = (d2 + d11);
    d3 = (d3 + (d1 + d3));
    d4 = (d4 + 39.0);
    d5 = (d5 + (d0 * d5));
    d6 = (d6 + (d11 - 25.0));
    d7 = (d7 + (v2 & 63));
    d8 = (d8 + d0);
    d9 = (d9 + (17.0 - d4));
    d10 = (d10 + -3.0);
    d11 = (d11 + 17.0);
    if (((v11 / 7) >= (((-50 - v10) & 1023) | 500))) {
        for (int i4 = 0; i4 < 6; i4++) {
            v1 = ((v14 & 1023) ^ 586);
        }
    } else {
        v11 = arr[((89 * v9)) & 7];
    }
    v8 = (((((v15 & 1023) ^ 485) & 1023) ^ 136) + ((-53 & 1023) ^ 956));
    v6 = arr[((((-89 & 255) >> 1) - ((-99 & 1023) | 333))) & 7];
    d3 = f1(v7, (-13.0 - d9), (v13 + v13), d0, (2.0 * d8), v4, (v15 / 8), ((v12 & 1023) | 199), (v11 * v10), v4, (d3 - d1));
    d0 = (d0 + (d11 - 6.0));
    d1 = (d1 + (v14 & 63));
    d2 = (d2 + (d2 - d6));
    d3 = (d3 + (d11 - d5));
    d4 = (d4 + (d6 - d11));
    d5 = (d5 + 34.0);
    d6 = (d6 + d6);
    d7 = (d7 + (d2 - d9));
    d8 = (d8 + 34.0);
    d9 = (d9 + (d4 + d6));
    d10 = (d10 + d1);
    d11 = (d11 + (d3 * d5));
    arr[((72 / 11)) & 7] = -58;
    d10 = f1(((v10 & 1023) ^ 905), d2, v8, d11, (d4 * d7), ((v0 & 1023) & 267), ((33 & 1023) ^ 114), ((v10 & 255) >> 2), ((-20 & 1023) & 91), v1, d0);
    d0 = (d0 + (d2 + 28.0));
    d1 = (d1 + (-23.0 + d6));
    d2 = (d2 + (((6 & 1023) ^ 129) & 63));
    d3 = (d3 + d5);
    d4 = (d4 + (d10 - d1));
    d5 = (d5 + (d10 + -28.0));
    d6 = (d6 + (d7 * -14.0));
    d7 = (d7 + d5);
    d8 = (d8 + d0);
    d9 = (d9 + (d8 + d0));
    d10 = (d10 + -6.0);
    d11 = (d11 + (d3 + d7));
    arr[((26 - v5)) & 7] = v8;
    v10 = f0(v12, (d8 + d7), (d1 + 14.0), (d5 - -40.0), v11, d7, (v14 / -6), 4.0);
    d0 = (d0 + 18.0);
    d1 = (d1 + (d5 * 27.0));
    d2 = (d2 + (d1 + d6));
    d3 = (d3 + d0);
    d4 = (d4 + d5);
    d5 = (d5 + d3);
    d6 = (d6 + ((64 * v3) & 63));
    d7 = (d7 + (d10 - d10));
    d8 = (d8 + (((v12 & 255) >> 4) & 63));
    d9 = (d9 + d2);
    d10 = (d10 + (23.0 * d5));
    d11 = (d11 + d11);
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != -2953595.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
