// Regression test: a value that lived and died before a block parameter's own
// `BlockParam` marker took the register that parameter was holding.
//
// The phi copies on the edge write every parameter of a block before its first
// instruction runs; a marker only says where the value is named, and the
// scheduler places the markers by dependence order. Nothing modelled that, so a
// splitter store/reload pair inserted inside the run of markers was given a
// register a later-marked parameter already held. Both verifiers pass on it --
// the register is written before it is read, and no two *modelled* live ranges
// overlap.
//
// Was KNOWN FAILING: blitz -O0 exited 3, the generated program's own float
// guard rejecting the sum.
//
// gen_c.py seed 16, shape pressure, saved unreduced.
//
// EXIT: 0
// OUTPUT: 19361
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

double f0(double p0, double p1, double p2, double p3, int p4, int p5, int p6) {
    for (int i84 = 0; i84 < 5; i84++) {
        p5 = ((87 & 255) >> 1);
        p6 = ((i84 & 255) << 1);
    }
    p6 = 72;
    return (p0 + (p3 + -20.0));
}

int f1(int p0, double p1, double p2, int p3, double p4, int p5, int p6, int p7, double p8, double p9, double p10) {
    for (int i1 = 0; i1 < 5; i1++) {
        p3 = (57 / 7);
    }
    p6 = p0;
    if (((p0 % -3) >= ((p7 & 255) >> 3))) {
        p0 = (p3 - p7);
        if ((97 < p6)) {
            for (int i26 = 0; i26 < 3; i26++) {
                p3 = 29;
            }
            for (int i27 = 0; i27 < 6; i27++) {
                if ((p5 < p3)) {
                    if ((i27 > p7)) {
                        p7 = p6;
                        if ((42 <= i27)) {
                            if ((i27 == -5)) {
                                p6 = p6;
                            } else {
                                p6 = p3;
                            }
                            p3 = p7;
                        } else {
                            if ((i27 > p0)) {
                                p5 = p3;
                                p6 = -63;
                            } else {
                                if ((p5 < p6)) {
                                    p7 = p5;
                                    p5 = p7;
                                } else {
                                    if ((49 > i27)) {
                                        p0 = p5;
                                        p0 = p0;
                                    } else {
                                        p0 = 51;
                                        p5 = p0;
                                    }
                                    p5 = p0;
                                }
                            }
                        }
                    } else {
                        p5 = p5;
                    }
                } else {
                    p0 = 97;
                    if ((p3 > p5)) {
                        p7 = i27;
                        p3 = 14;
                    } else {
                        p0 = p5;
                        p7 = i27;
                    }
                }
                p6 = p0;
                p7 = p3;
            }
        } else {
            p3 = 17;
        }
    } else {
        p3 = 1;
    }
    return ((p0 - p5) + (42 / 4));
}

int f2(double p0, int p1, double p2, double p3, double p4, int p5, double p6) {
    if ((((26 & 1023) & 991) < (p5 + 68))) {
        if ((p1 >= p5)) {
            p5 = 49;
        } else {
            p5 = p1;
        }
        for (int i12 = 0; i12 < 3; i12++) {
            p5 = 11;
            p5 = p5;
            if ((p5 == p5)) {
                p1 = p5;
                p1 = p1;
            } else {
                p1 = 22;
                if ((i12 != p5)) {
                    p1 = p1;
                    p5 = p1;
                } else {
                    if ((i12 >= p1)) {
                        p1 = i12;
                        if ((p5 != -62)) {
                            if ((p1 >= p5)) {
                                p5 = 34;
                                p1 = p5;
                            } else {
                                p5 = i12;
                                p5 = p1;
                            }
                            p5 = i12;
                        } else {
                            p5 = 37;
                            p1 = p5;
                        }
                    } else {
                        p5 = p5;
                        p5 = i12;
                    }
                    p5 = p5;
                }
            }
        }
    } else {
        if ((p1 >= -65)) {
            for (int i30 = 0; i30 < 1; i30++) {
                p1 = p5;
                if ((i30 == p5)) {
                    p5 = 38;
                    if ((7 == 36)) {
                        p1 = p1;
                        p5 = p5;
                    } else {
                        p1 = i30;
                        if ((p1 < p5)) {
                            if ((i30 < i30)) {
                                p5 = 77;
                            } else {
                                p5 = -71;
                            }
                        } else {
                            p1 = p5;
                        }
                    }
                } else {
                    if ((p1 != 60)) {
                        p5 = i30;
                    } else {
                        p5 = p5;
                        p5 = p5;
                    }
                }
                p1 = p1;
            }
        } else {
            if ((p1 > -12)) {
                p5 = p5;
            } else {
                if ((93 <= p5)) {
                    p5 = p1;
                    if ((p5 <= p5)) {
                        for (int i48 = 0; i48 < 4; i48++) {
                            if ((p5 <= i48)) {
                                if ((p1 != p1)) {
                                    if ((p5 > p1)) {
                                        if ((i48 == p1)) {
                                            p5 = p5;
                                        } else {
                                            p5 = p1;
                                        }
                                    } else {
                                        p5 = -45;
                                    }
                                } else {
                                    p5 = p1;
                                    p5 = 69;
                                }
                                p5 = p5;
                            } else {
                                p5 = p5;
                            }
                            if ((p5 == 61)) {
                                p1 = -23;
                                p5 = -94;
                            } else {
                                p1 = i48;
                            }
                            if ((p1 > i48)) {
                                p5 = i48;
                                p1 = p1;
                            } else {
                                p1 = -67;
                                p5 = p5;
                            }
                        }
                    } else {
                        p5 = p5;
                    }
                } else {
                    for (int i91 = 0; i91 < 3; i91++) {
                        p1 = 25;
                        p1 = -47;
                        p5 = p5;
                    }
                    p5 = p1;
                }
            }
            p1 = p1;
        }
    }
    return ((((p5 & 255) << 3) & 1023) ^ 511);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = 9;
    int v1 = 24;
    int v2 = -22;
    int v3 = 32;
    int v4 = -2;
    int v5 = -3;
    int v6 = -45;
    int v7 = 43;
    int v8 = -37;
    int v9 = 40;
    int v10 = -28;
    int v11 = 49;
    int v12 = 45;
    int v13 = -38;
    int v14 = -24;
    int v15 = -14;
    double d0 = 8.0;
    double d1 = 2.0;
    double d2 = 6.0;
    double d3 = -9.0;
    double d4 = 14.0;
    double d5 = -14.0;
    double d6 = 1.0;
    double d7 = -6.0;
    double d8 = -17.0;
    double d9 = -27.0;
    double d10 = 29.0;
    double d11 = -4.0;
    v0 = (((v4 % 4) % 11) + (-61 * v10));
    if ((((v15 & 255) << 1) < (((83 / 8) & 1023) ^ 356))) {
        v6 = v2;
    } else {
        v2 = (v14 % 8);
    }
    for (int i86 = 0; i86 < 1; i86++) {
        arr[(((26 & 1023) ^ 665)) & 7] = (((v1 & 1023) | 91) * ((v5 & 255) >> 1));
    }
    v12 = f1(((v10 & 255) << 0), (v11 & 63), (d6 + d6), v9, (d9 * d8), v5, (v0 / 11), 46, (d5 + d4), (39.0 * d8), (d6 + d6));
    d3 = f0((d1 - d7), d7, (79 & 63), (v5 & 63), ((v1 & 255) << 4), (v2 + v12), (v5 % 11));
    d0 = (d0 + d7);
    d1 = (d1 + (d7 - d2));
    d2 = (d2 + (d7 + d8));
    d3 = (d3 + ((-1 % 16) & 63));
    d4 = (d4 + d0);
    d5 = (d5 + (-19.0 - d7));
    d6 = (d6 + 29.0);
    d7 = (d7 + (d11 + d7));
    d8 = (d8 + d11);
    d9 = (d9 + -8.0);
    d10 = (d10 + (d2 - 2.0));
    d11 = (d11 + (d9 + d8));
    v6 = (((32 % 3) - (v3 + v1)) * ((36 % 3) - ((-57 & 255) >> 1)));
    for (int i6 = 0; i6 < 1; i6++) {
        v5 = (((86 / 3) & 1023) ^ 758);
        if ((v12 != (v15 + v11))) {
            v15 = (-33 - v7);
            v12 = -56;
        } else {
            v1 = v6;
            v8 = -49;
        }
    }
    v1 = f1((v1 - v15), (v0 & 63), d7, (v7 * v7), (11.0 * d6), -58, 31, ((77 & 255) << 2), (d0 - d7), (((v3 & 255) >> 1) & 63), d7);
    d0 = (d0 + (d1 - -32.0));
    d1 = (d1 + (-16.0 + 34.0));
    d2 = (d2 + -38.0);
    d3 = (d3 + (-21.0 + d0));
    d4 = (d4 + ((v12 - v6) & 63));
    d5 = (d5 + -38.0);
    d6 = (d6 + -21.0);
    d7 = (d7 + (d7 - d9));
    d8 = (d8 + (d0 * d4));
    d9 = (d9 + d4);
    d10 = (d10 + (d11 + d4));
    d11 = (d11 + (d11 - d3));
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != 1156.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}
