// KNOWN FAILING under BLITZ_VERIFY only, and expected to be. The plain lit run
// passes; `BLITZ_VERIFY=strict bash tests/lit/run_tests.sh` reports this file
// as a compilation failure, which is the open item at the top of P0.
//
// `verify_register_sharing` finds two VRegs live at once holding XMM12 at block
// 2's exit. The check recomputes liveness from the schedules as emitted;
// `build_interference_into` adds an edge for every simultaneously-live pair, so
// the colouring can only have placed them together if the allocator's own
// liveness never had them live together. One of the two is wrong and the
// verifier cannot say which.
//
// It has no behavioural symptom -- the program prints the right answer at both
// levels and under cc -- so no oracle can hold it and the corpus cannot either.
// A lit test is the only gate that runs the verifier, which is why it lives
// here rather than in `tests/fuzz/corpus/open/`.
//
// gen_c.py seed 148 shape pressure, unreduced: an 80-line reduction exists but
// trips its own double-sum guard and returns 3, so this one is the honest
// artifact. The seed is not durable -- `gen_c.py` only regenerates it until the
// generator changes -- which is why the file is checked in.
//
// FLAGS: -O1
// GENERATED by tests/fuzz/gen_c.py -- do not edit by hand.
//
// Free of undefined behavior by construction: pure expressions, no
// unsequenced side effects, nonzero constant divisors, in-range shift
// counts, indices masked into bounds, constant trip counts.
// Doubles hold integral values and use only + - *, so every result is
// exact and no reference compiler can legally disagree.

extern int printf(char* fmt, int x);

int f0(double p0, int p1, double p2, double p3, int p4, double p5, double p6, int p7, int p8) {
    p4 = ((((p1 & 1023) | 541) & 255) << 2);
    p8 = p4;
    return (34 + ((p7 & 1023) & 591));
}

int f1(int p0, double p1, int p2, int p3, double p4, int p5, int p6, int p7, int p8) {
    for (int i32 = 0; i32 < 3; i32++) {
        p6 = p0;
        if ((i32 <= p6)) {
            p2 = p0;
            if ((p6 > p2)) {
                p0 = 4;
            } else {
                p2 = -98;
                p2 = 2;
            }
        } else {
            p6 = p5;
        }
        if ((p5 == -69)) {
            p8 = p3;
        } else {
            p2 = 13;
        }
    }
    return ((p0 & 1023) ^ 648);
}

double f2(int p0, double p1, int p2, int p3, double p4, double p5, int p6) {
    for (int i29 = 0; i29 < 6; i29++) {
        if ((p3 == i29)) {
            p6 = -16;
        } else {
            p2 = 58;
            p6 = p2;
        }
        if ((p0 != i29)) {
            p3 = p6;
            p2 = i29;
        } else {
            p3 = i29;
        }
        p0 = ((i29 & 1023) ^ 312);
    }
    for (int i33 = 0; i33 < 1; i33++) {
        p6 = ((p0 & 255) << 4);
    }
    p0 = p3;
    return (((-6 & 255) >> 2) & 63);
}

int main() {
    int arr[8];
    arr[0] = -7;
    arr[1] = -4;
    arr[2] = -1;
    arr[3] = 2;
    arr[4] = 5;
    arr[5] = 8;
    arr[6] = 11;
    arr[7] = 14;
    int v0 = -1;
    int v1 = -14;
    int v2 = 26;
    int v3 = 1;
    int v4 = -21;
    int v5 = 13;
    int v6 = 48;
    int v7 = 26;
    int v8 = -50;
    int v9 = 24;
    int v10 = -34;
    int v11 = -30;
    int v12 = 48;
    int v13 = -32;
    int v14 = -28;
    int v15 = 5;
    double d0 = 3.0;
    double d1 = -26.0;
    double d2 = 6.0;
    double d3 = -1.0;
    double d4 = 3.0;
    double d5 = -8.0;
    double d6 = 8.0;
    double d7 = -24.0;
    double d8 = 5.0;
    double d9 = -29.0;
    double d10 = 10.0;
    double d11 = -23.0;
    v1 = ((((v10 & 255) << 4) / 7) / 4);
    arr[(v6) & 7] = v10;
    v1 = arr[(((((v4 & 255) << 3) & 255) >> 3)) & 7];
    v8 = f1((v14 + v7), d3, ((v7 & 1023) | 936), ((v11 & 1023) ^ 98), d10, ((v13 & 1023) | 683), ((v8 & 1023) | 1003), ((v6 & 1023) ^ 258), ((v11 & 1023) ^ 672));
    d0 = (d0 + (d4 * d5));
    d1 = (d1 + d7);
    d2 = (d2 + -35.0);
    d3 = (d3 + -37.0);
    d4 = (d4 + d1);
    d5 = (d5 + 16.0);
    d6 = (d6 + (d4 + 0.0));
    d7 = (d7 + (d3 * -1.0));
    d8 = (d8 + (d2 - -9.0));
    d9 = (d9 + (d6 + d0));
    d10 = (d10 + 38.0);
    d11 = (d11 + (-35.0 - 21.0));
    v4 = (v2 / 8);
    v6 = f0((d6 * -38.0), ((v15 & 1023) | 25), (-24.0 - -9.0), d4, (-54 - v9), (d10 * d2), -12.0, v4, (v4 * v0));
    d0 = (d0 + d7);
    d1 = (d1 + (d2 - d2));
    d2 = (d2 + (d3 - d8));
    d3 = (d3 + (d6 - d10));
    d4 = (d4 + (d8 + -22.0));
    d5 = (d5 + d9);
    d6 = (d6 + (((v10 & 1023) ^ 721) & 63));
    d7 = (d7 + d0);
    d8 = (d8 + -28.0);
    d9 = (d9 + d7);
    d10 = (d10 + (d11 - d10));
    d11 = (d11 + (d5 * d7));
    if ((((((v13 & 255) << 4) & 255) << 4) != -33)) {
        if ((v15 < v12)) {
            for (int i66 = 0; i66 < 6; i66++) {
                v2 = i66;
            }
            v11 = ((v6 & 1023) & 199);
        } else {
            if ((v12 >= v10)) {
                for (int i0 = 0; i0 < 3; i0++) {
                    if ((v4 < v6)) {
                        if ((61 > v0)) {
                            if ((12 <= -18)) {
                                arr[((v8 * v15)) & 7] = v10;
                            } else {
                                v2 = i0;
                                v2 = v0;
                            }
                        } else {
                            v1 = v6;
                        }
                        arr[(i0) & 7] = v8;
                    } else {
                        v1 = v12;
                    }
                }
                v5 = 48;
            } else {
                for (int i41 = 0; i41 < 6; i41++) {
                    v12 = -75;
                    v13 = v5;
                    arr[(46) & 7] = v0;
                }
            }
        }
    } else {
        if (((-73 % 7) <= ((v9 & 1023) & 751))) {
            arr[(((17 & 255) >> 4)) & 7] = v0;
            v6 = ((v3 & 255) << 3);
        } else {
            v4 = arr[(v3) & 7];
            arr[(33) & 7] = arr[(v9) & 7];
        }
        arr[(42) & 7] = (((v3 - v13) & 1023) & 780);
    }
    v2 = ((((v14 * v6) / 7) & 255) << 0);
    v8 = f1(v11, (d1 * d4), (v15 % 3), (v11 + v5), 30.0, v1, ((v11 & 1023) | 431), v5, (-40 - v6));
    v0 = f1(((v7 & 1023) | 356), (d1 - d8), v4, (-64 - v10), d8, 45, v7, v14, ((93 & 255) >> 3));
    d0 = (d0 + (d6 - d1));
    d1 = (d1 + (d8 - d5));
    d2 = (d2 + d2);
    d3 = (d3 + (d2 - d10));
    d4 = (d4 + d2);
    d5 = (d5 + (d6 * d4));
    d6 = (d6 + (v3 & 63));
    d7 = (d7 + (2.0 + d9));
    d8 = (d8 + (d5 - d3));
    d9 = (d9 + (d9 * -24.0));
    d10 = (d10 + d9);
    d11 = (d11 + (d6 * d6));
    v6 = ((((-72 % 4) + -59) & 1023) | 572);
    v12 = f1(((v2 & 1023) ^ 36), (d3 + d9), ((v2 & 1023) | 380), (v15 / -3), d0, v5, ((v1 & 255) >> 4), (-22 / 16), v1);
    v0 = f0(d3, ((20 & 1023) ^ 188), d11, ((59 % 2) & 63), (v8 - 73), (d9 + 30.0), (-1.0 - d10), ((v11 & 255) << 3), (v12 + 88));
    d0 = (d0 + (d0 * d8));
    d1 = (d1 + d4);
    d2 = (d2 + d10);
    d3 = (d3 + (d5 + d10));
    d4 = (d4 + (d6 - d10));
    d5 = (d5 + 7.0);
    d6 = (d6 + (32.0 + d7));
    d7 = (d7 + (-1.0 - 37.0));
    d8 = (d8 + 4.0);
    d9 = (d9 + -28.0);
    d10 = (d10 + ((v1 - v7) & 63));
    d11 = (d11 + d7);
    if ((((((((((((d0 + d1) + d2) + d3) + d4) + d5) + d6) + d7) + d8) + d9) + d10) + d11) != 104096.0) { return 3; }
    printf("%d\n", (((((((((((((((((((((((v0 + v1) + v2) + v3) + v4) + v5) + v6) + v7) + v8) + v9) + v10) + v11) + v12) + v13) + v14) + v15) + arr[(0) & 7]) + arr[(1) & 7]) + arr[(2) & 7]) + arr[(3) & 7]) + arr[(4) & 7]) + arr[(5) & 7]) + arr[(6) & 7]) + arr[(7) & 7]));
    return 0;
}

// EXIT: 0
// OUTPUT: 2514
